define({
  "defaultAreaUnit": "Единицы площади по умолчанию",
  "defaultLengthUnit": "Единицы длины по умолчанию",
  "acres": "Акры",
  "sqMiles": "Кв. мили",
  "sqKilometers": "Кв. километры",
  "hectares": "гектары",
  "sqYards": "Кв. ярды",
  "sqFeet": "Кв. футы",
  "sqFeetUS": "Кв. футы (США)",
  "sqMeters": "Кв. метры",
  "miles": "Мили",
  "kilometers": "Километры",
  "feet": "Футы",
  "feetUS": "Футы (США)",
  "meters": "Метры",
  "yards": "Ярды",
  "nauticalMiles": "Морские мили",
  "showArea": "Площадь",
  "showDistance": "Расстояние",
  "showLocation": "Местоположение",
  "showtools": "Показать инструменты измерений:",
  "allHidedTips": "Необходимо выбрать по крайней мере один инструмент."
});