define({
  "common": {
    "apply": "Aplicar",
    "ok": "Ok",
    "cancel": "Cancelar",
    "yes": "Sim",
    "no": "Não",
    "next": "Avançar",
    "previous": "Anterior",
    "back": "Voltar",
    "selected": "selecionado",
    "name": "Nome",
    "usage": "Uso",
    "settings": "Configurações",
    "home": "Página Inicial",
    "link": "Link",
    "messages": "Mensagens",
    "outputs": "Saídas",
    "title": "Título",
    "thumbnail": "Miniatura",
    "url": "URL",
    "actions": "Ações",
    "layer": "Camada",
    "action": "Ação",
    "input": "Entrada",
    "output": "Saída",
    "type": "Tipo",
    "required": "Exigido",
    "options": "Opções",
    "label": "Rótulo",
    "tooltip": "Dica da Ferramenta",
    "visible": "Visível",
    "symbol": "Símbolo",
    "popup": "Pop-up",
    "upload": "Carregar",
    "execute": "Executar",
    "help": "Ajuda",
    "executing": "Executando",
    "clear": "Limpar",
    "error": "Erro",
    "zoomTo": "Zoom para",
    "attribute": "Atributo",
    "exports": "Exportar",
    "check": "Verificar",
    "save": "Salvar",
    "close": "Fechar",
    "deleteText": "Excluir",
    "map": "Mapa",
    "scene": "Cena",
    "reset": "Redefinir",
    "icon": "Ícone",
    "share": "Compartilhar",
    "view": "Visualizar",
    "newText": "Novo",
    "edit": "Editar",
    "wkid": "WKID",
    "table": "Tabela",
    "zoomIn": "Mais Zoom",
    "zoomOut": "Menos Zoom",
    "continue1": "Continuar",
    "longitude": "Longitude",
    "latitude": "Latitude"
  },
  "errorCode": "Código",
  "errorMessage": "Mensagem",
  "errorDetail": "Detalhe",
  "widgetPlaceholderTooltip": "Para configurar, siga até Widgets e clique no console correspondente",
  "fieldStatistics": {
    "selectField": "Selecionar campo",
    "statistics": "Estatística",
    "field": "Campo",
    "count": "Número de Valores",
    "sum": "Soma de Valores",
    "min": "Mínimo",
    "max": "Máximo",
    "ave": "Média",
    "stddev": "Desvio Padrão"
  },
  "symbolChooser": {
    "preview": "Visualizar",
    "basic": "Básico",
    "arrows": "Setas",
    "business": "Negócio",
    "cartographic": "Cartográfico",
    "nationalParkService": "Serviço do Parque Nacional",
    "outdoorRecreation": "Recreação ao Ar Livre",
    "peoplePlaces": "Lugares e Pessoas",
    "safetyHealth": "Saúde e Segurança",
    "shapes": "Formas",
    "transportation": "Transporte",
    "symbolSize": "Tamanho de Símbolo",
    "color": "Cor",
    "alpha": "Alfa",
    "outlineColor": "Cor do Contorno",
    "outlineWidth": "Largura do Contorno",
    "style": "Estilo",
    "width": "Largura",
    "text": "Texto",
    "fontColor": "Cor da Fonte",
    "fontSize": "Tamanho da Fonte",
    "transparency": "Transparência",
    "solid": "Sólido",
    "dash": "Traço",
    "dot": "Ponto",
    "dashDot": "Traço Ponto",
    "dashDotDot": "Traço Ponto Ponto",
    "customImage": "Imagem Personalizada",
    "chooseFile": "Escolher arquivo",
    "noFileChoosen": "Nenhum arquivo escolhido."
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Transparente"
  },
  "rendererChooser": {
    "domain": "Domínio",
    "use": "Uso",
    "singleSymbol": "Um Único Símbolo",
    "uniqueSymbol": "Símbolos Únicos",
    "color": "Cor",
    "size": "Tamanho",
    "toShow": "Para Mostrar",
    "colors": "Cores",
    "classes": "Classes",
    "symbolSize": "Tamanho de Símbolo",
    "addValue": "Adicionar Valor",
    "setDefaultSymbol": "Configurar Símbolo Padrão",
    "defaultSymbol": "Símbolo Padrão",
    "selectedSymbol": "Símbolo Selecionado",
    "value": "Valor",
    "label": "Rótulo",
    "range": "Intervalo"
  },
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha À Mão Livre",
    "triangle": "Triângulo",
    "extent": "Extensão",
    "circle": "Círculo",
    "ellipse": "Elipse",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono À Mão Livre",
    "text": "Texto",
    "clear": "Apagar"
  },
  "popupConfig": {
    "title": "Título",
    "add": "Adicionar",
    "fields": "Campos",
    "noField": "Nenhum Campo",
    "visibility": "Visível",
    "name": "Nome",
    "alias": "Nome Alternativo",
    "actions": "Ações"
  },
  "includeButton": {
    "include": "Incluir"
  },
  "loadingShelter": {
    "loading": "Carregando"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Nenhum serviço encontrado.",
    "unableConnectTo": "Não foi possível conectar ao",
    "invalidUrlTip": "O URL que você inseriu é inválido ou inacessível."
  },
  "serviceBrowser": {
    "noGpFound": "Nenhum serviço de geoprocessamento encontrado.",
    "unableConnectTo": "Não foi possível conectar ao"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Nenhum serviço de mapa ou da feição encontrado",
    "unableConnectTo": "Não foi possível conectar ao"
  },
  "basicServiceChooser": {
    "validate": "Validar",
    "example": "Exemplo",
    "set": "Configurar"
  },
  "urlInput": {
    "invalidUrl": "URL inválido."
  },
  "urlComboBox": {
    "invalidUrl": "URL inválido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Adicionar um expressão de filtro",
    "addSet": "Adicione um conjunto de expressão",
    "matchMsg": "Obtenha feições na camada que correspondam ao ${any_or_all} das seguintes expressões",
    "matchMsgSet": "${any_or_all} das seguintes expressões neste parâmetro são verdadeiros",
    "all": "Todas",
    "any": "Nenhum",
    "value": "Valor",
    "field": "Campo",
    "unique": "Único",
    "none": "Nenhum",
    "and": "e",
    "valueTooltip": "Inserir valor",
    "fieldTooltip": "Selecionar de campo existente",
    "uniqueValueTooltip": "Selecionar de valores únicos no campo selecionado",
    "stringOperatorIs": "é",
    "stringOperatorIsNot": "não é",
    "stringOperatorStartsWith": "inicia com",
    "stringOperatorEndsWith": "finaliza com",
    "stringOperatorContains": "contém",
    "stringOperatorDoesNotContain": "não contém",
    "stringOperatorIsBlank": "está em branco",
    "stringOperatorIsNotBlank": "não está em branco",
    "dateOperatorIsOn": "está em",
    "dateOperatorIsNotOn": "não está em",
    "dateOperatorIsBefore": "está antes",
    "dateOperatorIsAfter": "está após",
    "dateOperatorDays": "dias",
    "dateOperatorWeeks": "semanas",
    "dateOperatorMonths": "meses",
    "dateOperatorInTheLast": "no último",
    "dateOperatorNotInTheLast": "não no último",
    "dateOperatorIsBetween": "está entre",
    "dateOperatorIsNotBetween": "não está entre",
    "dateOperatorIsBlank": "está em branco",
    "dateOperatorIsNotBlank": "não está em branco",
    "numberOperatorIs": "é",
    "numberOperatorIsNot": "não é",
    "numberOperatorIsAtLeast": "é pelo menos",
    "numberOperatorIsLessThan": "é menor que",
    "numberOperatorIsAtMost": "é na maioria",
    "numberOperatorIsGreaterThan": "é maior que",
    "numberOperatorIsBetween": "está entre",
    "numberOperatorIsNotBetween": "não está entre",
    "numberOperatorIsBlank": "está em branco",
    "numberOperatorIsNotBlank": "não está em branco",
    "string": "Texto",
    "number": "Número",
    "date": "Data",
    "askForValues": "Perguntar por valores",
    "prompt": "Janela de Comando",
    "hint": "Sugestão",
    "error": {
      "invalidParams": "Parâmetros inválidos.",
      "invalidUrl": "URL inválido.",
      "noFilterFields": "As camadas não têm campos que possam ser utilizados para filtrar.",
      "invalidSQL": "Expressão SQL inválida.",
      "cantParseSQL": "Não é possível analisar a expressão SQL."
    },
    "caseSensitive": "Diferença Ortográfica",
    "notSupportCaseSensitiveTip": "Os serviços hospedados não suportam consulta que diferencia maiúsculas de minúsculas.",
    "setFilterTip": "Configure o filtro corretamente.",
    "listValues": "Listar Valores",
    "cascadeFilterTip": "Somente mostrar os valores filtrados por expressões anteriores.",
    "noneCascadeFilterTip": "Todos os valores únicos deste campo",
    "previousCascadeFilterTip": "Valores filtrados por expressões anteriores",
    "allCascadeFilterTip": "Valores filtrados por todas as outras expressões"
  },
  "featureLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "URL da Camada de Entrada",
    "selectLayer": "Seleciona uma camada de feição do mapa atual.",
    "chooseItem": "Escolhe um item da camada de feição.",
    "setServiceUrl": "Insere a URL de serviço da feição ou serviço do mapa.",
    "selectFromOnline": "Adicionar do ArcGIS Online",
    "chooseLayer": "Escolher uma camada de feição."
  },
  "queryableLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "URL da Camada de Entrada",
    "selectLayer": "Selecione uma camada do mapa atual.",
    "chooseItem": "Escolha um item.",
    "setServiceUrl": "Insira a URL do serviço.",
    "selectFromOnline": "Adicionar do ArcGIS Online",
    "chooseLayer": "Escolha uma camada."
  },
  "gpSource": {
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "selectFromOnline": "Adicionar do ArcGIS Online",
    "setServiceUrl": "Insira a URL do serviço de geoprocessamento.",
    "chooseItem": "Escolha um item do serviço de geoprocessamento.",
    "chooseTask": "Escolha uma tarefa de geoprocessamento."
  },
  "itemSelector": {
    "map": "Mapa",
    "selectWebMap": "Escolher Mapa da Web",
    "addMapFromOnlineOrPortal": "Localiza e adiciona um mapa da web em um aplicativo a partir de recursos públicos do ArcGIS Online ou do seu conteúdo privado no ArcGIS Online ou Portal.",
    "searchMapName": "Procurar por nome do mapa...",
    "searchNone": "Não foi possível encontramos o que você procurava. Tente novamente.",
    "groups": "Grupos",
    "noneGroups": "Sem grupos",
    "signInTip": "Sua sessão de login expirou, atualize seu navegador para entrar no seu portal novamente.",
    "signIn": "Entrar",
    "publicMap": "Público",
    "myOrganization": "Minha Organização",
    "myGroup": "Meus Grupos",
    "myContent": "Meu Conteúdo",
    "count": "Contagem",
    "fromPortal": "do Portal",
    "fromOnline": "do ArcGIS.com",
    "noneThumbnail": "Miniatura Não Disponível",
    "owner": "proprietário",
    "signInTo": "Entrar no",
    "lastModified": "Última Modificação",
    "moreDetails": "Mais Detalhes",
    "mostRecent": "Mais Recente",
    "mostViewed": "Mais Visualizado",
    "highestRated": "Maiores Taxas",
    "viewItemDetails": "Visualizar detalhes do item"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "O serviço não suporta consulta."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Não há uma camada apropriada disponível no mapa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapas Base",
    "titleLayers": "Camadas Operacionais",
    "labelLayer": "Nome da Camada",
    "itemZoomTo": "Zoom para",
    "itemTransparency": "Transparência",
    "itemTransparent": "Transparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Mover para cima",
    "itemMoveDown": "Mover para baixo",
    "itemDesc": "Descrição",
    "itemDownload": "Download",
    "itemToAttributeTable": "Abrir Tabela de Atributo"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: O navegador não suporta a API de leitor do arquivo",
    "readError": "Falha ao ler o arquivo.",
    "unknowError": "não foi possível completar as operações",
    "invalidType": "Tipo de arquivo inválido.",
    "cropImage": "Recortar Imagem",
    "exceed": "O tamanho do arquivo excede 1024 KB",
    "enableFlash": "Habilite o Adobe Flash antes de procurar uma imagem.",
    "cropWaining": "Escolha uma fotografia que tenha pelo menos ${width} x ${height} pixels.",
    "toolTip": "Para melhores resultados, a imagem deve ter a largura de ${width} pixels pela altura de ${height} pixels. Outros tamanhos serão ajustados. Os formatos de imagem aceitáveis são: PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Mover para cima",
    "moveDown": "Mover para baixo",
    "deleteRow": "Excluir",
    "edit": "Editar"
  },
  "urlParams": {
    "invalidToken": "Token inválido",
    "validateTokenError": "Erro de rede ou token inválido"
  },
  "exportTo": {
    "exportTo": "Exportar",
    "toCSV": "Exportar para arquivo CSV",
    "toFeatureCollection": "Exportar para Coleção de Feição",
    "toGeoJSON": "Exportar para GeoJSON"
  },
  "appState": {
    "title": "Estado do Aplicativo",
    "restoreMap": "Clique para restaurar a extensão do mapa e visibilidade de camadas de onde você parou."
  },
  "featureActions": {
    "featureActions": "Ações da feição",
    "ZoomTo": "Zoom para",
    "PanTo": "Mover para",
    "Flash": "Destacar",
    "ShowPopup": "Mostrar Pop-up",
    "CreateLayer": "Criar Camada",
    "ShowStatistics": "Estatísticas...",
    "ClearSelection": "Limpar Seleção",
    "ExportToCSV": "Exportar para arquivo CSV",
    "ShowSelectedFeature": "Mostrar Feições Selecionadas",
    "ExportToFeatureCollection": "Exportar para Coleção de Feição",
    "ExportToGeoJSON": "Exportar para GeoJSON",
    "AddMarker": "Adicionar um Marcador",
    "RemoveMarker": "Remover Marcador"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Camada Relacionada",
    "selectedFeatures": "Utilizar feições selecionadas",
    "drawShapesTip": "Desenhar formas para selecionar feições",
    "pleaseDrawShapesTip": "Desenhe formas para selecionar feições",
    "allFeaturesTip": "Todas as feições na camada",
    "selectFeaturesOrDrawShapesTip": "Utilize feições selecionadas nesta camada ou desenhe formas no mapa para limitar feições."
  },
  "searchDistance": {
    "applySearchDistance": "Aplicar uma distância de pesquisa",
    "applySearchDistanceToFeatures": "Aplicar uma distância de pesquisa para feições selecionadas"
  },
  "units": {
    "miles": "Milhas",
    "kilometers": "Quilômetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas Náuticas"
  },
  "featureSetChooser": {
    "select": "Selecionar",
    "dragBox": "Arrastar",
    "dragMouse": "Arraste o mouse",
    "selectByRectangle": "Selecionar por Retângulo",
    "selectFeaturesTip": "Selecione feições arrastando uma caixa ao redor delas no mapa",
    "newSelectionTip": "Criar nova seleção",
    "addSelectionTip": "Adicionar à seleção",
    "removeSelectionTip": "Remover da seleção",
    "selectFromCurrentSelectionTip": "Seleciona da seleção atual",
    "unselectAllSelectionTip": "Cancelar seleção de todas as feições atualmente selecionadas",
    "selectByPolygon": "Selecionar por Polígono",
    "selectByCircle": "Selecionar por Círculo",
    "selectByLine": "Selecionar por Linha",
    "chooseSelectingTools": "Escolha as ferramentas de seleção",
    "darw": "Desenhar",
    "drawShap": "Desenhar uma forma"
  },
  "widgetManager": {
    "createWidgetError": "Erro ao Criar widget",
    "createWidgetSettingPageError": "Erro da página de configuração Criar widget",
    "loadWidgetResourceError": "Erro do recurso Carregar widget"
  },
  "shareOptions": {
    "shareMap": "Escolha quem pode visualizar este aplicativo",
    "shareMapTips": "Seu mapa está atualmente compartilhado com estes usuários",
    "everyone": "Todos",
    "theseGroups": "Estes grupos"
  },
  "shareLink": {
    "email": "e-mail",
    "shareEmail": "E-mail",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Embutir este aplicativo em um site da web",
    "shareEmailSubject": "Compartilhando aplicativo da web:",
    "shareEmailTxt1": "Aqui está um aplicativo da web compartilhado com você utilizando Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Você pode criar e compartilhar seu próprio aplicativo da web com Web AppBuilder for ArcGIS da Esri.",
    "shareEmailTxt3": "Visite http://www.esri.com/software/web-appbuilder para detalhes.",
    "smallSize": "Pequeno",
    "mediumSize": "Médio",
    "largeSize": "Grande",
    "customSize": "Personalizar",
    "embed": "Embutir este aplicativo em um site da web",
    "more": "Opções para Embutir",
    "changeShareSettings": "Alterar Configurações de Compartilhamento",
    "shareLinkText": "Compartilhe um link para este aplicativo",
    "linkOptions": "Opções de Link",
    "linkOptionsUrlParameters": "Selecione parâmetros da URL incluídos no link",
    "currentMapExtent": "Extensão do mapa atual",
    "chooseCenterWithLevel": "Clique no mapa para definir o centro do mapa com nível de zoom",
    "chooseCenterWithScale": "Clique no mapa para definir o centro do mapa com escala do mapa",
    "findLocation": "Encontre o local ou feição e aplique zoom",
    "findLocation_inputPlaceholder": "Seu lugar ou feição",
    "queryFeature": "Consulte uma feição e aplique zoom",
    "addMarker": "Adicione um marcador no mapa",
    "addMarker_titlePlaceholder": "Título de pop-up do marcador",
    "addMarker_symbolURL": "URL de símbolo do marcador",
    "addMarker_label": "Rótulo do marcador",
    "popupTitle": "Título do pop-up",
    "zoomLevel": "Nível de zoom",
    "overwirteMobileLayout": "Substituir tamanho de tela padrão do layout móvel",
    "language": "Configurar idioma de visualização do aplicativo",
    "auth": "Autenticar um usuário automaticamente",
    "linkPreview": "Visualizar link",
    "useShortenLink": "Link curto",
    "shareMapUrlExtent": "Compartilhar extensão de mapa atual",
    "shareToWebTips": "Este aplicativo não está compartilhado com o público. As pessoas podem não conseguir visualizá-lo."
  },
  "webSceneLoader": {
    "webglSupportTip": "Aplicativos da web 3D não são suportados no seu navegador."
  },
  "map": {
    "basemapNotAvailable": "O mapa base não está disponível.",
    "displayDefaultBasemap": "Ao contrário, exibindo o mapa base padrão."
  },
  "popup": {
    "relatedTables": "Tabelas relacionadas:",
    "relatedRecords": "Registros relacionados:",
    "noRelatedRecotds": "Nenhum registro relacionado encontrado"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Há muitas feições em sua seleção. Isto pode levar muito tempo para recuperar e exibi-los no mapa.",
    "askForContinue": "Deseja continuar?"
  },
  "colorPalette": {
    "transparent": "Transparente",
    "custom": "Personalizar"
  },
  "noEditPrivileges": "Sua conta não tem permissão para criar ou modificar dados.",
  "invalidConfiguration": "O Widget não está configurado ou as camadas na configuração não estão mais no mapa.  Abra o aplicativo no modo do construtor e configure novamente o widget."
});