define({
  "common": {
    "apply": "Uygula",
    "ok": "Tamam",
    "cancel": "İptal",
    "yes": "Evet",
    "no": "Hayır",
    "next": "İleri",
    "previous": "Önceki",
    "back": "Geri",
    "selected": "seçili",
    "name": "Ad",
    "usage": "Kullanım",
    "settings": "Ayarlar",
    "home": "Giriş Sayfası",
    "link": "Bağlantı",
    "messages": "İletiler",
    "outputs": "Çıktılar",
    "title": "Başlık",
    "thumbnail": "Küçük Resim",
    "url": "URL",
    "actions": "İşlemler",
    "layer": "Katman",
    "action": "İşlem",
    "input": "Girdi",
    "output": "Çıktı",
    "type": "Tür",
    "required": "Gerekli",
    "options": "Seçenekler",
    "label": "Etiket",
    "tooltip": "Araç ipucu",
    "visible": "Görünür",
    "symbol": "Sembol",
    "popup": "Açılır Menü",
    "upload": "Yükle",
    "execute": "Yürüt",
    "help": "Yardım",
    "executing": "Gerçekleştiriliyor",
    "clear": "Temizle",
    "error": "Hata",
    "zoomTo": "Yakınlaştır",
    "attribute": "Öznitelik",
    "exports": "Dışa Aktar",
    "check": "İşaretle",
    "save": "Kaydet",
    "close": "Kapat",
    "deleteText": "Sil",
    "map": "Harita",
    "scene": "Görünüm",
    "reset": "Sıfırla",
    "icon": "Simge",
    "share": "Paylaş",
    "view": "Görüntüle",
    "newText": "Yeni",
    "edit": "Düzenle",
    "wkid": "WKID",
    "table": "Tablo",
    "zoomIn": "Büyüt",
    "zoomOut": "Küçült",
    "continue1": "Devam",
    "longitude": "Boylam",
    "latitude": "Enlem"
  },
  "errorCode": "Kod",
  "errorMessage": "İleti",
  "errorDetail": "Ayrıntı",
  "widgetPlaceholderTooltip": "Ayarlamak için Araçlar'a gidin ve karşılık gelen yer tutucuyu tıklayın",
  "fieldStatistics": {
    "selectField": "Alan seç",
    "statistics": "İstatistikler",
    "field": "Alan",
    "count": "Değer Sayısı",
    "sum": "Değerler Toplamı",
    "min": "Minimum",
    "max": "Maksimum",
    "ave": "Ortalama",
    "stddev": "Standart Sapma"
  },
  "symbolChooser": {
    "preview": "Önizleme",
    "basic": "Temel",
    "arrows": "Oklar",
    "business": "İş",
    "cartographic": "Kartografik",
    "nationalParkService": "Ulusal Park Hizmeti",
    "outdoorRecreation": "Açık Havada Dinlenme",
    "peoplePlaces": "İnsanların Bulunduğu Mekanlar",
    "safetyHealth": "Güvenlik Sağlık",
    "shapes": "Şekiller",
    "transportation": "Taşımacılık",
    "symbolSize": "Simge Boyutu",
    "color": "Renk",
    "alpha": "Alfa",
    "outlineColor": "Dış Çizgi Rengi",
    "outlineWidth": "Dış Çizgi Genişliği",
    "style": "Stil",
    "width": "Genişlik",
    "text": "Metin",
    "fontColor": "Yazı Tipi Rengi",
    "fontSize": "Yazı Tipi Boyutu",
    "transparency": "Saydamlık",
    "solid": "Dolu",
    "dash": "Tire",
    "dot": "Nokta",
    "dashDot": "Çizgi Nokta",
    "dashDotDot": "Çizgi Nokta Nokta",
    "customImage": "Özel Resim",
    "chooseFile": "Dosya seç",
    "noFileChoosen": "Seçili dosya yok."
  },
  "transparency": {
    "opaque": "Opak",
    "transparent": "Saydam"
  },
  "rendererChooser": {
    "domain": "Etki Alanı",
    "use": "Kullan",
    "singleSymbol": "Tek Bir Simge",
    "uniqueSymbol": "Özel Simgeler",
    "color": "Renk",
    "size": "Boyut",
    "toShow": "Gösterilecek",
    "colors": "Renkler",
    "classes": "Sınıflar",
    "symbolSize": "Simge Boyutu",
    "addValue": "Değer Ekle",
    "setDefaultSymbol": "Varsayılan Simgeyi Ayarla",
    "defaultSymbol": "Varsayılan Sembol",
    "selectedSymbol": "Seçili Simge",
    "value": "Değer",
    "label": "Etiket",
    "range": "Aralık"
  },
  "drawBox": {
    "point": "Nokta",
    "line": "Çizgi",
    "polyline": "Çoklu Çizgi",
    "freehandPolyline": "Serbest Çizim Çoklu Çizgi",
    "triangle": "Üçgen",
    "extent": "Yayılım",
    "circle": "Daire",
    "ellipse": "Elips",
    "polygon": "Alan",
    "freehandPolygon": "Serbest Çizim Alan",
    "text": "Metin",
    "clear": "Temizle"
  },
  "popupConfig": {
    "title": "Başlık",
    "add": "Ekle",
    "fields": "Alanlar",
    "noField": "Alan Yok",
    "visibility": "Görünür",
    "name": "Adı",
    "alias": "Diğer Ad",
    "actions": "İşlemler"
  },
  "includeButton": {
    "include": "Dahil Et"
  },
  "loadingShelter": {
    "loading": "Yükleniyor"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Servis bulunamadı.",
    "unableConnectTo": "Buraya bağlanılamıyor:",
    "invalidUrlTip": "Girdiğiniz URL geçersiz veya erişilemez."
  },
  "serviceBrowser": {
    "noGpFound": "Coğrafi işlem servisi bulunamadı.",
    "unableConnectTo": "Buraya bağlanılamıyor:"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Harita servisi ya da detay servisi bulunamadı",
    "unableConnectTo": "Buraya bağlanılamıyor:"
  },
  "basicServiceChooser": {
    "validate": "Doğrula",
    "example": "Örnek",
    "set": "Ayarla"
  },
  "urlInput": {
    "invalidUrl": "Geçersiz URL."
  },
  "urlComboBox": {
    "invalidUrl": "Geçersiz URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Bir filtre ifadesi ekle",
    "addSet": "İfade kümesi ekle",
    "matchMsg": "Katmanda, aşağıdaki ifadenin ${any_or_all} kadarı ile eşleşen detayları al",
    "matchMsgSet": "Bu setteki aşağıdaki ifadelerin ${any_or_all} doğru",
    "all": "Tümü",
    "any": "Bir Kısmı",
    "value": "Değer",
    "field": "Alan",
    "unique": "Tek",
    "none": "Hiçbiri",
    "and": "ve",
    "valueTooltip": "Değer gir",
    "fieldTooltip": "Mevcut alandan seç",
    "uniqueValueTooltip": "Seçili alandaki tek değerlerden seç",
    "stringOperatorIs": "alanı şu olanlar",
    "stringOperatorIsNot": "alanı şu olmayanlar",
    "stringOperatorStartsWith": "alanı şununla başlayanlar",
    "stringOperatorEndsWith": "alanı şununla bitenler",
    "stringOperatorContains": "alanı şunu içerenler",
    "stringOperatorDoesNotContain": "alanı şunu içermeyenler",
    "stringOperatorIsBlank": "alanı boş olanlar",
    "stringOperatorIsNotBlank": "alanı boş olmayanlar",
    "dateOperatorIsOn": "alanı şu tarihte olanlar",
    "dateOperatorIsNotOn": "alanı şu tarihte olmayanlar",
    "dateOperatorIsBefore": "alanı şu tarihten önce olanlar",
    "dateOperatorIsAfter": "alanı şu tarihten sonra olanlar",
    "dateOperatorDays": "gün içinde",
    "dateOperatorWeeks": "hafta içinde",
    "dateOperatorMonths": "ay içinde",
    "dateOperatorInTheLast": "alanı son şu dönemde olanlar",
    "dateOperatorNotInTheLast": "alanı son şu dönemde olmayanlar",
    "dateOperatorIsBetween": "alanı şu tarihler arasında olanlar",
    "dateOperatorIsNotBetween": "alanı şu tarihler arasında olmayanlar",
    "dateOperatorIsBlank": "alanı boş olanlar",
    "dateOperatorIsNotBlank": "alanı boş olmayanlar",
    "numberOperatorIs": "alanı şu olanlar",
    "numberOperatorIsNot": "alanı şu olmayanlar",
    "numberOperatorIsAtLeast": "alanı en az şu olanlar",
    "numberOperatorIsLessThan": "alanı şundan küçük olanlar",
    "numberOperatorIsAtMost": "alanı en çok şu olanlar",
    "numberOperatorIsGreaterThan": "alanı şundan büyük olanlar",
    "numberOperatorIsBetween": "alanı şu tarihler arasında olanlar",
    "numberOperatorIsNotBetween": "alanı şu tarihler arasında olmayanlar",
    "numberOperatorIsBlank": "alanı boş olanlar",
    "numberOperatorIsNotBlank": "alanı boş olmayanlar",
    "string": "Dize",
    "number": "Rakam",
    "date": "Tarih",
    "askForValues": "Değer iste",
    "prompt": "İstem",
    "hint": "İpucu",
    "error": {
      "invalidParams": "Geçersiz parametreler.",
      "invalidUrl": "Geçersiz URL.",
      "noFilterFields": "Katmanın filtre için kullanılabilecek hiçbir alanı yok.",
      "invalidSQL": "Geçersiz SQL ifadesi.",
      "cantParseSQL": "SQL ifadesi ayrıştırılamadı."
    },
    "caseSensitive": "Büyük/Küçük Harf Duyarlı",
    "notSupportCaseSensitiveTip": "Barındırılan hizmetler büyük küçük harf duyarlı sorgulamayı desteklemez.",
    "setFilterTip": "Filtreyi düzgün şekilde ayarlayın.",
    "listValues": "Değer Listesi",
    "cascadeFilterTip": "Yalnızca önceki ifadeler tarafından filtrelenen değerler gösterilsin.",
    "noneCascadeFilterTip": "Bu alana ait benzersiz değerlerin tümü",
    "previousCascadeFilterTip": "Önceki ifadeler tarafından filtrelenen değerler",
    "allCascadeFilterTip": "Diğer tüm ifadeler tarafından filtrelenen değerler"
  },
  "featureLayerSource": {
    "layer": "Katman",
    "browse": "Gözat",
    "selectFromMap": "Haritadan seç",
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si ekle",
    "inputLayerUrl": "Girdi Katmanı URL'si",
    "selectLayer": "Geçerli haritadan bir detay katmanı seçin.",
    "chooseItem": "Bir detay katmanı öğesi seçin.",
    "setServiceUrl": "Detay servisinin ya da harita servisinin URL'sini girin.",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "chooseLayer": "Bir özellik katmanı seçin."
  },
  "queryableLayerSource": {
    "layer": "Katman",
    "browse": "...",
    "selectFromMap": "Haritadan seç",
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si ekle",
    "inputLayerUrl": "Girdi Katmanı URL'si",
    "selectLayer": "Geçerli haritadan bir katman seçin.",
    "chooseItem": "Öğe seçin.",
    "setServiceUrl": "Hizmetin URL'sini girin.",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "chooseLayer": "Katman seçmek için kullanılır."
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS'ten ekle",
    "addServiceUrl": "Servis URL'si Ekle",
    "selectFromOnline": "ArcGIS Online'dan Ekle",
    "setServiceUrl": "Coğrafi işlem hizmetinin URL'sini girin.",
    "chooseItem": "Bir coğrafi işlem hizmet öğesi seçin.",
    "chooseTask": "Bir coğrafi işlem görevi seçin."
  },
  "itemSelector": {
    "map": "Harita",
    "selectWebMap": "Web Haritası Seç",
    "addMapFromOnlineOrPortal": "ArcGIS Online genel kaynaklarından veya ArcGIS Online veya Portal'daki özel içeriğinizden gelen uygulamada bir web haritası bulun ve buraya ekleyin.",
    "searchMapName": "Harita adına göre ara...",
    "searchNone": "Aradığınızı bulamadık. Yeniden deneyin.",
    "groups": "Gruplar",
    "noneGroups": "Grup yok",
    "signInTip": "Oturumunuzun süresi doldu, portalınızda yeniden oturum açmak için tarayıcınızı yenileyin.",
    "signIn": "Hesabınıza",
    "publicMap": "Genel",
    "myOrganization": "Kuruluşum",
    "myGroup": "Gruplarım",
    "myContent": "İçeriğim",
    "count": "Sayım",
    "fromPortal": "Portal'dan",
    "fromOnline": "ArcGIS.com'dan",
    "noneThumbnail": "Küçük Resim Yok",
    "owner": "Sahibi",
    "signInTo": "Şurada oturum aç",
    "lastModified": "Son Değiştirme",
    "moreDetails": "Diğer Ayrıntılar",
    "mostRecent": "En Son",
    "mostViewed": "En Çok Görüntülenen",
    "highestRated": "En Yüksek Derecelendirmeli",
    "viewItemDetails": "Öğe ayrıntılarını görüntüle"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Hizmet sorgulamayı desteklemiyor."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Haritada kullanılabilir uygun katman yok."
  },
  "layerInfosMenu": {
    "titleBasemap": "Altlık haritaları",
    "titleLayers": "Operasyonel Katmanlar",
    "labelLayer": "Katman Adı",
    "itemZoomTo": "Şuna Yakınlaştır",
    "itemTransparency": "Saydamlık",
    "itemTransparent": "Saydam",
    "itemOpaque": "Opak",
    "itemMoveUp": "Yukarı taşı",
    "itemMoveDown": "Aşağı taşı",
    "itemDesc": "Açıklama",
    "itemDownload": "İndir",
    "itemToAttributeTable": "Öznitelik Tablosunu Aç"
  },
  "imageChooser": {
    "unsupportReaderAPI": "YAPILACAK: Tarayıcı, dosya okuyucu API'sini desteklemiyor",
    "readError": "Dosya okunamadı.",
    "unknowError": "işlemler tamamlanamıyor",
    "invalidType": "Geçersiz dosya türü.",
    "cropImage": "Görüntüyü Kırp",
    "exceed": "Dosya boyutu 1024 KB'yi aşamaz",
    "enableFlash": "Bir resme gitmeden önce Adobe Flash uygulamasını etkinleştirin.",
    "cropWaining": "Çözünürlüğü en az ${width} x ${height} piksel olan bir fotoğraf seçin.",
    "toolTip": "En iyi sonuç için görüntü ${width} piksel genişliğinde ve ${height} piksel yüksekliğinde olmalıdır. Diğer boyutlar sığacak şekilde ayarlanır. Kabul edilen görüntü biçimleri: PNG, GIF ve JPEG."
  },
  "simpleTable": {
    "moveUp": "Yukarı taşı",
    "moveDown": "Aşağı taşı",
    "deleteRow": "Sil",
    "edit": "Düzenle"
  },
  "urlParams": {
    "invalidToken": "Geçersiz belirteç",
    "validateTokenError": "Geçersiz belirteç veya Ağ hatası"
  },
  "exportTo": {
    "exportTo": "Dışa Aktar",
    "toCSV": "CSV dosyasına gönder",
    "toFeatureCollection": "Detay Koleksiyonuna Aktar",
    "toGeoJSON": "GeoJSON//'a Aktar"
  },
  "appState": {
    "title": "Uygulama Durumu",
    "restoreMap": "Harita yayılımını ve katman görünürlüğünü bıraktığınız yerden geri yüklemek için tıklayın."
  },
  "featureActions": {
    "featureActions": "Detay işlemleri",
    "ZoomTo": "Yakınlaştır",
    "PanTo": "Kaydır",
    "Flash": "Parlat",
    "ShowPopup": "Açılan Pencere Göster",
    "CreateLayer": "Katman Oluştur",
    "ShowStatistics": "İstatistikler...",
    "ClearSelection": "Seçimi Temizle",
    "ExportToCSV": "CSV dosyasına gönder",
    "ShowSelectedFeature": "Seçili Detayları Göster",
    "ExportToFeatureCollection": "Detay Koleksiyonuna Aktar",
    "ExportToGeoJSON": "GeoJSON//'a Aktar",
    "AddMarker": "İşaretleyici ekle",
    "RemoveMarker": "İşaretleyiciyi kaldır"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "İlgili katman",
    "selectedFeatures": "Seçili detayları kullan",
    "drawShapesTip": "Detay seçmek için şekil çizin",
    "pleaseDrawShapesTip": "Detay seçmek için şekil çizin",
    "allFeaturesTip": "Katmandaki tüm detaylar",
    "selectFeaturesOrDrawShapesTip": "Bu katmanda seçili detayları kullanın veya detayları sınırlandırmak için şekil çizin."
  },
  "searchDistance": {
    "applySearchDistance": "Arama mesafesi uygula",
    "applySearchDistanceToFeatures": "Seçili detaylara bir arama mesafesi uygulayın"
  },
  "units": {
    "miles": "Mil",
    "kilometers": "Kilometre",
    "feet": "Fit",
    "meters": "Metre",
    "yards": "Yarda",
    "nauticalMiles": "Deniz Mili"
  },
  "featureSetChooser": {
    "select": "Seç",
    "dragBox": "Sürükle",
    "dragMouse": "Fareyi sürükleyin",
    "selectByRectangle": "Dikdörtgenle Seç",
    "selectFeaturesTip": "Haritada etrafına kutu çizerek detay seçin",
    "newSelectionTip": "Yeni seçim oluşturun",
    "addSelectionTip": "Seçime ekle",
    "removeSelectionTip": "Seçimden kaldır",
    "selectFromCurrentSelectionTip": "Aktif seçimden seç",
    "unselectAllSelectionTip": "Geçerli durumda seçili tüm detayların seçimini kaldırın",
    "selectByPolygon": "Alana Göre Seç",
    "selectByCircle": "Daireyle Seç",
    "selectByLine": "Çizgiyle Seç",
    "chooseSelectingTools": "Seçim araçlarını belirleyin.",
    "darw": "Çiz",
    "drawShap": "Şekil çiz"
  },
  "widgetManager": {
    "createWidgetError": "Araç oluşturma hatası",
    "createWidgetSettingPageError": "Araç oluşturma ayar sayfası hatası",
    "loadWidgetResourceError": "Araç kaynağı yükleme hatası"
  },
  "shareOptions": {
    "shareMap": "Bu uygulamayı kimlerin görebileceğini seçin",
    "shareMapTips": "Uygulamanız şu anda bu kişilerle paylaşılıyor",
    "everyone": "Herkes",
    "theseGroups": "Bu gruplar"
  },
  "shareLink": {
    "email": "e-posta",
    "shareEmail": "E-posta",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Bu uygulamayı bir web sitesine yerleştir",
    "shareEmailSubject": "Web uygulamasını paylaşma:",
    "shareEmailTxt1": "İşte karşınızda Web AppBuilder for ArcGIS kullanılarak sizinle paylaşılan bir web uygulaması.",
    "shareEmailTxt2": "Esri Web AppBuilder for ArcGIS ile kendi web uygulamanızı oluşturabilir ve paylaşabilirsiniz.",
    "shareEmailTxt3": "Ayrıntılar için http://www.esri.com/software/web-appbuilder adresine gidin.",
    "smallSize": "Küçük",
    "mediumSize": "Orta",
    "largeSize": "Büyük",
    "customSize": "Özel",
    "embed": "Bu uygulamayı bir web sitesine yerleştir",
    "more": "Katıştırma Seçenekleri",
    "changeShareSettings": "Paylaşım Ayarlarını Değiştir",
    "shareLinkText": "Bu uygulama bağlantısını paylaş",
    "linkOptions": "Bağlantı Seçenekleri",
    "linkOptionsUrlParameters": "Bağlantıya eklenen URL parametrelerini seç",
    "currentMapExtent": "Mevcut harita boyutu",
    "chooseCenterWithLevel": "Haritaya tıklayarak haritanın merkezini yakınlaştırma düzeyi ile tanımlayın",
    "chooseCenterWithScale": "Haritaya tıklayarak haritanın merkezini harita ölçeği ile tanımlayın",
    "findLocation": "Konumu veya detayı bulun ve yakınlaştırın",
    "findLocation_inputPlaceholder": "Yeriniz veya detayınız",
    "queryFeature": "Bir detayı sorgulayın ve yakınlaştırın",
    "addMarker": "Haritaya bir işaretçi ekleyin",
    "addMarker_titlePlaceholder": "İşaretçi açılır penceresinin başlığı",
    "addMarker_symbolURL": "İşaretçi simgesi URL'si",
    "addMarker_label": "İşaretçi etiketi",
    "popupTitle": "Açılır pencere başlığı",
    "zoomLevel": "Yakınlaştırma düzeyi",
    "overwirteMobileLayout": "Mobil yerleşimin varsayılan ekran boyutunun üzerine yazın",
    "language": "Uygulamanın ekran dilini ayarlayın",
    "auth": "Kullanıcının kimliğini otomatik olarak doğrulayın",
    "linkPreview": "Bağlantı önizlemesi",
    "useShortenLink": "Kısa bağlantı",
    "shareMapUrlExtent": "Geçerli harita yayılımını paylaş",
    "shareToWebTips": "Bu uygulama başkalarıyla paylaşılmıyor. İnsanlar bunu görüntüleyemeyebilir."
  },
  "webSceneLoader": {
    "webglSupportTip": "3B web haritaları tarayıcınızda desteklenmiyor."
  },
  "map": {
    "basemapNotAvailable": "Altlık harita mevcut değil.",
    "displayDefaultBasemap": "Bunun yerine varsayılan altlık harita görüntüleniyor."
  },
  "popup": {
    "relatedTables": "İlgili tablolar:",
    "relatedRecords": "İlgili kayıtlar:",
    "noRelatedRecotds": "İlgili kayıt bulunamadı"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Seçiminizde çok fazla detay var. Bunların alınması ve harita üzerinde görüntülenmesi uzun sürebilir.",
    "askForContinue": "Devam etmek istiyor musunuz?"
  },
  "colorPalette": {
    "transparent": "Saydam",
    "custom": "Özel"
  },
  "noEditPrivileges": "Hesabınızın veri oluşturma veya değiştirme izni yok.",
  "invalidConfiguration": "Araç yapılandırılmamış veya yapılandırmadaki katmanlar artık haritada değil. Uygulamayı oluşturucu modda açın ve aracı yeniden yapılandırın."
});