define({
  "defaultAreaUnit": "デフォルトの面積単位",
  "defaultLengthUnit": "デフォルトの長さ単位",
  "acres": "エーカー",
  "sqMiles": "平方マイル",
  "sqKilometers": "平方キロメートル",
  "hectares": "ヘクタール",
  "sqYards": "平方ヤード",
  "sqFeet": "平方フィート",
  "sqFeetUS": "平方フィート (米国)",
  "sqMeters": "平方メートル",
  "miles": "マイル",
  "kilometers": "キロメートル",
  "feet": "フィート",
  "feetUS": "フィート (米国)",
  "meters": "メートル",
  "yards": "ヤード",
  "nauticalMiles": "海里",
  "showArea": "面積",
  "showDistance": "距離",
  "showLocation": "位置",
  "showtools": "計測ツールを表示:",
  "allHidedTips": "少なくとも 1 つのツールが選択されている必要があります。"
});