define({
  "id": "ID",
  "state": "Secara default, koordinat akan ditampilkan sama dengan sistem koordinat peta saat ini. Untuk mendapatkan koordinat dengan sistem koordinat lain, Anda harus menambahkannya dan menentukan transformasi yang tepat.",
  "outputUnit": "Unit Output",
  "wkid": "WKID Output",
  "label": "Nama Sistem Koordinat Output",
  "transformationWkid": "Transformasi WKID",
  "transformationLabel": "Transformasi Label",
  "transformForward": "Transformasikan ke Depan",
  "actions": "Tindakan",
  "warning": "Masukkan referensi spasial WKID yang valid!",
  "tfWarning": "Masukkan transformasi datum WKID yang valid!",
  "spinnerLabel": "Bulatkan koordinat menjadi: ",
  "decimalPlace": "decimal places",
  "separator": "Tampilkan pemisah ribuan",
  "getVersionError": "Tidak dapat memperoleh versi Geometry Service.",
  "add": "Tambahkan Sistem Koordinat Output",
  "edit": "Edit Sistem Koordinat",
  "output": "Sistem Koordinat Output",
  "cName": "Nama Sistem Koordinat",
  "units": "Unit Tampilan: ",
  "datum": "Transformasi Datum",
  "tName": "Nama Transformasi",
  "tWKIDPlaceHolder": "transformasi WKID",
  "forward": "Gunakan transformasi ke depan",
  "ok": "Ya",
  "cancel": "Batal",
  "olderVersion": "Geometry service tidak mendukung operasi transformasi",
  "REPEATING_ERROR": " Terdapat sistem koordinat di daftar output.",
  "Default": "Default",
  "Inches": "Inci",
  "Foot": "Kaki",
  "Yards": "Yard",
  "Miles": "Mil",
  "Nautical_Miles": "Mil Laut",
  "Millimeters": "Milimeter",
  "Centimeters": "Sentimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Desimeter",
  "Decimal_Degrees": "Derajat Desimal",
  "Degree_Minutes_Seconds": "Derajat Menit Detik",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Urutan tampilan kordinat:",
  "lonLatTips": "Garis Bujur / Garis Lintang (X, Y)",
  "latLonTips": "Garis Lintang / Garis Bujur (Y, X)"
});