define({
  "common": {
    "apply": "Aplicar",
    "ok": "Ok",
    "cancel": "Cancelar",
    "yes": "Sim",
    "no": "Não",
    "next": "Seguinte",
    "previous": "Anterior",
    "back": "Regressar",
    "selected": "selecionadas",
    "name": "Nome",
    "usage": "Utilização",
    "settings": "Configurações",
    "home": "Início",
    "link": "Ligação",
    "messages": "Mensagens",
    "outputs": "Dados de Saída",
    "title": "Título",
    "thumbnail": "Miniatura",
    "url": "URL",
    "actions": "Ações",
    "layer": "Camada",
    "action": "Ação",
    "input": "Introdução",
    "output": "Saída",
    "type": "Tipo",
    "required": "Exigido",
    "options": "Opções",
    "label": "Rótulo",
    "tooltip": "Conselho de utilização",
    "visible": "Visível",
    "symbol": "Símbolo",
    "popup": "Janela popup",
    "upload": "Carregar",
    "execute": "Executar",
    "help": "Ajuda",
    "executing": "A executar",
    "clear": "Limpar",
    "error": "Erro",
    "zoomTo": "Efectuar zoom para",
    "attribute": "Atributo",
    "exports": "Exportar",
    "check": "Verificar",
    "save": "Guardar",
    "close": "Fechar",
    "deleteText": "Excluir",
    "map": "Mapa",
    "scene": "Cena 3D",
    "reset": "Redefinir",
    "icon": "Ícone",
    "share": "Partilhar",
    "view": "Ver",
    "newText": "Novo",
    "edit": "Editar",
    "wkid": "WKID",
    "table": "Tabela",
    "zoomIn": "Aumentar Zoom",
    "zoomOut": "Reduzir zoom",
    "continue1": "Continuar",
    "longitude": "Longitude",
    "latitude": "Latitude"
  },
  "errorCode": "Código",
  "errorMessage": "Mensagem",
  "errorDetail": "Detalhe",
  "widgetPlaceholderTooltip": "Para configurar, vá a Widgets e clique no placehorlder correspondente",
  "fieldStatistics": {
    "selectField": "Selecionar Campo",
    "statistics": "Estatísticas",
    "field": "Campo",
    "count": "Número de Valores",
    "sum": "Soma de Valores",
    "min": "Mínimo",
    "max": "Máximo",
    "ave": "Média",
    "stddev": "Desvio Padrão"
  },
  "symbolChooser": {
    "preview": "Pré-Visualizar",
    "basic": "Básico",
    "arrows": "Setas",
    "business": "Negócio",
    "cartographic": "Cartográfico",
    "nationalParkService": "Serviço Parque Nacional",
    "outdoorRecreation": "Lazer Outdoor",
    "peoplePlaces": "Locais de Pessoas",
    "safetyHealth": "Segurança Saúde",
    "shapes": "Formas",
    "transportation": "Transportes",
    "symbolSize": "Tamanho de Símbolos",
    "color": "Cor",
    "alpha": "Alfa",
    "outlineColor": "Cor de Contorno",
    "outlineWidth": "Largura do Contorno",
    "style": "Estilo",
    "width": "Largura",
    "text": "Texto",
    "fontColor": "Cor da Letra",
    "fontSize": "Tamanho de letra",
    "transparency": "Transparência",
    "solid": "Sólido",
    "dash": "Traço",
    "dot": "Ponto",
    "dashDot": "Traço Ponto",
    "dashDotDot": "Traço Ponto Ponto",
    "customImage": "Imagem Personalizada",
    "chooseFile": "Escolher ficheiro",
    "noFileChoosen": "Nenhum ficheiro escolhido."
  },
  "transparency": {
    "opaque": "Opaco",
    "transparent": "Transparente"
  },
  "rendererChooser": {
    "domain": "Domínio",
    "use": "Utilize",
    "singleSymbol": "Um Único Símbolo",
    "uniqueSymbol": "Símbolos Únicos",
    "color": "Cor",
    "size": "Tamanho",
    "toShow": "Para Exibir",
    "colors": "Cores",
    "classes": "Classes",
    "symbolSize": "Tamanho de Símbolos",
    "addValue": "Adicionar Valor",
    "setDefaultSymbol": "Definir Símbolo Padrão",
    "defaultSymbol": "Símbolo Padrão",
    "selectedSymbol": "Símbolo Selecionado",
    "value": "Valor",
    "label": "Rótulo",
    "range": "Intervalo"
  },
  "drawBox": {
    "point": "Ponto",
    "line": "Linha",
    "polyline": "Polilinha",
    "freehandPolyline": "Polilinha À Mão Livre",
    "triangle": "Triângulo",
    "extent": "Extensão",
    "circle": "Círculo",
    "ellipse": "Elipse",
    "polygon": "Polígono",
    "freehandPolygon": "Polígono À Mão Livre",
    "text": "Texto",
    "clear": "Apagar"
  },
  "popupConfig": {
    "title": "Título",
    "add": "Adicionar",
    "fields": "Campos",
    "noField": "Sem Campo",
    "visibility": "Visível",
    "name": "Nome",
    "alias": "Nome Alternativo",
    "actions": "Acções"
  },
  "includeButton": {
    "include": "Incluir"
  },
  "loadingShelter": {
    "loading": "A carregar"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Não foram encontrados serviços.",
    "unableConnectTo": "Impossível ligar a",
    "invalidUrlTip": "O URL que introduziu é inválido ou encontra-se inacessível."
  },
  "serviceBrowser": {
    "noGpFound": "Não foram encontrados serviços de geoprocessamento.",
    "unableConnectTo": "Impossível ligar a"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Não foram encontrados serviços MapServer ou FeatureServer",
    "unableConnectTo": "Impossível ligar a"
  },
  "basicServiceChooser": {
    "validate": "Validar",
    "example": "Exemplo",
    "set": "Definir"
  },
  "urlInput": {
    "invalidUrl": "Url inválido."
  },
  "urlComboBox": {
    "invalidUrl": "Url inválido."
  },
  "filterBuilder": {
    "addAnotherExpression": "Adicionar uma expressão de filtro",
    "addSet": "Adicionar uma expressão definida",
    "matchMsg": "Obter elementos na camada que correspondam a ${any_or_all} das expressões seguintes",
    "matchMsgSet": "${any_or_all} (d)as expressões seguintes neste conjunto são verdadeiras",
    "all": "Todas",
    "any": "Qualquer",
    "value": "Valor",
    "field": "Campo",
    "unique": "Único",
    "none": "Nenhum",
    "and": "e",
    "valueTooltip": "Introduzir valor",
    "fieldTooltip": "Escolher a partir de campo existente",
    "uniqueValueTooltip": "Escolher a partir de valores únicos no campo selecionado",
    "stringOperatorIs": "é",
    "stringOperatorIsNot": "não é",
    "stringOperatorStartsWith": "começa por",
    "stringOperatorEndsWith": "acaba em",
    "stringOperatorContains": "contém",
    "stringOperatorDoesNotContain": "não contém",
    "stringOperatorIsBlank": "está vazio",
    "stringOperatorIsNotBlank": "não está vazio",
    "dateOperatorIsOn": "é em",
    "dateOperatorIsNotOn": "não é em",
    "dateOperatorIsBefore": "é anterior a",
    "dateOperatorIsAfter": "é posterior a",
    "dateOperatorDays": "dias",
    "dateOperatorWeeks": "semanas",
    "dateOperatorMonths": "meses",
    "dateOperatorInTheLast": "nos(as) últimos(as)",
    "dateOperatorNotInTheLast": "não nos(as) últimos(as)",
    "dateOperatorIsBetween": "é entre",
    "dateOperatorIsNotBetween": "não é entre",
    "dateOperatorIsBlank": "está vazio",
    "dateOperatorIsNotBlank": "não está vazio",
    "numberOperatorIs": "é",
    "numberOperatorIsNot": "não é",
    "numberOperatorIsAtLeast": "é no mínimo",
    "numberOperatorIsLessThan": "é inferior a",
    "numberOperatorIsAtMost": "é no máximo",
    "numberOperatorIsGreaterThan": "é superior a",
    "numberOperatorIsBetween": "é entre",
    "numberOperatorIsNotBetween": "não é entre",
    "numberOperatorIsBlank": "está vazio",
    "numberOperatorIsNotBlank": "não está vazio",
    "string": "Texto",
    "number": "Número",
    "date": "Data",
    "askForValues": "Solicitar valores",
    "prompt": "Solicitação",
    "hint": "Dica",
    "error": {
      "invalidParams": "Parâmetros inválidos.",
      "invalidUrl": "Url inválido.",
      "noFilterFields": "A camada não tem quaisquer campos que possam ser utilizados para filtragem.",
      "invalidSQL": "Expressão sql inválida.",
      "cantParseSQL": "Impossível analisar a expressão sql."
    },
    "caseSensitive": "Diferencia Tamanho de Letra",
    "notSupportCaseSensitiveTip": "Os serviços alojados não suportam consultas que diferenciam maiúsculas de minúsculas.",
    "setFilterTip": "Por favor, defina o filtro corretamente.",
    "listValues": "Listar Valores",
    "cascadeFilterTip": "Apenas valores filtrados por expressões anteriores.",
    "noneCascadeFilterTip": "Todos os valores únicos deste campo",
    "previousCascadeFilterTip": "Valores filtrados por expressões anteriores",
    "allCascadeFilterTip": "Valores filtrados por todas as restantes expressões"
  },
  "featureLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "Url da Camada de Entrada",
    "selectLayer": "Selecionar uma camada de elementos do mapa atual.",
    "chooseItem": "Escolher um item da camada de elementos.",
    "setServiceUrl": "Introduzir o URL do serviço de elementos ou serviço de mapa.",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "chooseLayer": "Escolha uma camada de elementos."
  },
  "queryableLayerSource": {
    "layer": "Camada",
    "browse": "Procurar",
    "selectFromMap": "Selecionar do Mapa",
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "inputLayerUrl": "Url da Camada de Entrada",
    "selectLayer": "Seleccionar uma camada do mapa actual.",
    "chooseItem": "Escolher um item.",
    "setServiceUrl": "Introduza o URL do serviço.",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "chooseLayer": "Escolher uma camada."
  },
  "gpSource": {
    "selectFromPortal": "Adicionar do Portal for ArcGIS",
    "addServiceUrl": "Adicionar URL de Serviço",
    "selectFromOnline": "Adicionar de ArcGIS Online",
    "setServiceUrl": "Introduza o URL do serviço de geoprocessamento.",
    "chooseItem": "Escolha um item de serviço de geoprocessamento.",
    "chooseTask": "Escolha uma tarefa de geoprocessamento."
  },
  "itemSelector": {
    "map": "Mapa",
    "selectWebMap": "Selecionar Mapa Web",
    "addMapFromOnlineOrPortal": "Encontre e adicione um mapa web na aplicação a partir dos recursos públicos ArcGIS Online ou do seu conteúdo privado, no ArcGIS Online ou no Portal.",
    "searchMapName": "Pesquisar por nome do mapa...",
    "searchNone": "Não conseguimos encontrar aquilo que procura. Por favor, tente outra pesquisa.",
    "groups": "Grupos",
    "noneGroups": "Sem grupos",
    "signInTip": "Por favor, inicie sessão para aceder ao seu conteúdo privado.",
    "signIn": "Iniciar sessão",
    "publicMap": "Público",
    "myOrganization": "A Organização",
    "myGroup": "Os Meus Grupos",
    "myContent": "O Meu Conteúdo",
    "count": "Contagem",
    "fromPortal": "do Portal",
    "fromOnline": "de ArcGIS.com",
    "noneThumbnail": "Imagem Miniatura Indisponível",
    "owner": "proprietário",
    "signInTo": "Iniciar sessão em",
    "lastModified": "Última Modificação",
    "moreDetails": "Mais Detalhes",
    "mostRecent": "Mais Recente",
    "mostViewed": "Mais Visualizado",
    "highestRated": "Maior Classificação",
    "viewItemDetails": "Visualizar detalhes do item"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "O serviço não suporta consultas."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Não existe uma camada apropriada disponível no mapa."
  },
  "layerInfosMenu": {
    "titleBasemap": "Mapas base",
    "titleLayers": "Camadas Operacionais",
    "labelLayer": "Nome da Camada",
    "itemZoomTo": "Efetuar zoom para",
    "itemTransparency": "Transparência",
    "itemTransparent": "Transparente",
    "itemOpaque": "Opaco",
    "itemMoveUp": "Mover para cima",
    "itemMoveDown": "Mover para baixo",
    "itemDesc": "Descrição",
    "itemDownload": "Descarregar",
    "itemToAttributeTable": "Abrir tabela de atributos"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: O navegador não suporta o API de leitor de ficheiros",
    "readError": "Falha ao ler o ficheiro.",
    "unknowError": "impossível completar operações",
    "invalidType": "Tipo de ficheiro inválido.",
    "cropImage": "Recortar Imagem",
    "exceed": "O tamanho do ficheiro não pode exceder 1024 KB",
    "enableFlash": "Por favor, ative o Adobe Flash antes de navegar até uma imagem.",
    "cropWaining": "Por favor escolha uma fotografa que tenha pelo menos ${width} x ${height} pixels.",
    "toolTip": "Para obter melhores resultados, a imagem deverá ter ${width} pixéis de largura por ${height} pixéis de altura. Outros tamanhos serão ajustados para caberem. Os formatos de imagem aceitáveis são: PNG, GIF e JPEG."
  },
  "simpleTable": {
    "moveUp": "Mover para cima",
    "moveDown": "Mover para baixo",
    "deleteRow": "Eliminar",
    "edit": "Editar"
  },
  "urlParams": {
    "invalidToken": "Token inválido",
    "validateTokenError": "Token inválido ou erro de Rede"
  },
  "exportTo": {
    "exportTo": "Exportar",
    "toCSV": "Exportar para ficheiro CSV",
    "toFeatureCollection": "Exportar para Coleção de Elementos",
    "toGeoJSON": "Exportar para GeoJSON"
  },
  "appState": {
    "title": "Estado de Aplicação",
    "restoreMap": "Clique para restaurar a extensão de mapa e camadas de visibilidade de onde saiu."
  },
  "featureActions": {
    "featureActions": "Acções de elementos",
    "ZoomTo": "Efectuar zoom para",
    "PanTo": "Mover para",
    "Flash": "Flash",
    "ShowPopup": "Mostrar janela popup",
    "CreateLayer": "Criar Camada",
    "ShowStatistics": "Estatísticas...",
    "ClearSelection": "Limpar Seleção",
    "ExportToCSV": "Exportar para ficheiro CSV",
    "ShowSelectedFeature": "Exibir Elementos Selecionados",
    "ExportToFeatureCollection": "Exportar para Coleção de Elementos",
    "ExportToGeoJSON": "Exportar para GeoJSON",
    "AddMarker": "Adicionar um Marcador",
    "RemoveMarker": "Remover Marcador"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Camada relacionada",
    "selectedFeatures": "Utilizar elementos seleccionados",
    "drawShapesTip": "Desenhar formas para selecionar elementos",
    "pleaseDrawShapesTip": "Por favor, desenhe formas para selecionar elementos",
    "allFeaturesTip": "Todos os elementos presentes na camada",
    "selectFeaturesOrDrawShapesTip": "Por favor, utilize elementos selecionados nesta camada ou desenhe formas no mapa para limitar elementos."
  },
  "searchDistance": {
    "applySearchDistance": "Aplique uma distância de pesquisa",
    "applySearchDistanceToFeatures": "Aplicar uma distência de seleção para os elementos selecionados"
  },
  "units": {
    "miles": "Milhas",
    "kilometers": "Quilómetros",
    "feet": "Pés",
    "meters": "Metros",
    "yards": "Jardas",
    "nauticalMiles": "Milhas Náuticas"
  },
  "featureSetChooser": {
    "select": "Seleccionar",
    "dragBox": "Arrastar",
    "dragMouse": "Arrastar o ponteiro do rato",
    "selectByRectangle": "Seleccionar por Rectângulo",
    "selectFeaturesTip": "Selecionar elementos arrastando uma caixa ao redor dos mesmos no mapa",
    "newSelectionTip": "Criar nova seleção",
    "addSelectionTip": "Adicionar à seleção",
    "removeSelectionTip": "Remover da seleção",
    "selectFromCurrentSelectionTip": "Selecionar da seleção atual",
    "unselectAllSelectionTip": "Desselecionar todos os elementos atualmente selecionados",
    "selectByPolygon": "Seleccionar por Polígono",
    "selectByCircle": "Seleccionar por Círculo",
    "selectByLine": "Seleccionar por linha",
    "chooseSelectingTools": "Escolha ferramentas de seleção",
    "darw": "Desenhar",
    "drawShap": "Desenhar a forma"
  },
  "widgetManager": {
    "createWidgetError": "Criar erro de widget",
    "createWidgetSettingPageError": "Criar erro de página de definição de widget",
    "loadWidgetResourceError": "Carregar erro de recurso de widget"
  },
  "shareOptions": {
    "shareMap": "Escolher quem pode visualizar esta aplicação",
    "shareMapTips": "A sua aplicação está atualmente partilhada com estas pessoas",
    "everyone": "Todos",
    "theseGroups": "Estes grupos"
  },
  "shareLink": {
    "email": "correio eletrónico",
    "shareEmail": "Correio Eletrónico",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Incorporar este mapa num site web",
    "shareEmailSubject": "Incorporar esta aplicação num site web",
    "shareEmailTxt1": "Aqui está uma aplicação web partilhada consigo utilizando o Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Pode criar e partilhar a sua própria aplicação com o Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Visite http://www.esri.com/software/web-appbuilder para obter detalhes.",
    "smallSize": "Pequeno",
    "mediumSize": "Média",
    "largeSize": "Grande",
    "customSize": "Personalizar",
    "embed": "Incorporar este mapa num site web",
    "more": "Opções de Incorporação",
    "changeShareSettings": "Alterar Definições de Partilha",
    "shareLinkText": "Partilhar uma ligação para esta aplicação",
    "linkOptions": "Opções de Ligação",
    "linkOptionsUrlParameters": "Selecionar parâmetros de URL incluídos na ligação",
    "currentMapExtent": "Mapa extensão actual",
    "chooseCenterWithLevel": "Clicar no mapa para definir o centro do mapa com nível de zoom",
    "chooseCenterWithScale": "Clicar no mapa para definir o centro do mapa com escala de mapa",
    "findLocation": "Encontrar a localização ou elemento e aplicar zoom no mesmo",
    "findLocation_inputPlaceholder": "O seu local ou elemento",
    "queryFeature": "Consultar um elemento e aplicar zoom ao mesmo",
    "addMarker": "Adicionar um marcador no mapa",
    "addMarker_titlePlaceholder": "Título da janela pop-up do marcador",
    "addMarker_symbolURL": "URL de símbolo do marcador",
    "addMarker_label": "Rótulo do marcador",
    "popupTitle": "Título da janela Pop-up",
    "zoomLevel": "Nível de Zoom",
    "overwirteMobileLayout": "Substituir dimensão de ecrã predefinida para o layout móvel",
    "language": "Definir idioma de exibição da aplicação",
    "auth": "Autenticar um utilizador automaticamente",
    "linkPreview": "Pré-visualização da ligação",
    "useShortenLink": "Ligação curta",
    "shareMapUrlExtent": "Partilhar a atual extensão de mapa",
    "shareToWebTips": "Esta aplicação não está partilhada com o público. As pessoas poderão não ser capazes de visualizá-la."
  },
  "webSceneLoader": {
    "webglSupportTip": "As aplicações web 3D não são suportadas no seu navegador."
  },
  "map": {
    "basemapNotAvailable": "O Mapa Base não se encontra disponível.",
    "displayDefaultBasemap": "Exibir o mapa base predefinido ao invés."
  },
  "popup": {
    "relatedTables": "Tabelas relacionadas:",
    "relatedRecords": "Registos relacionados:",
    "noRelatedRecotds": "Não foram encontrados registos relacionados"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Existem demasiados elementos na sua seleção. Poderá demorar bastante a obtê-los e a exibi-los no mapa.",
    "askForContinue": "Deseja continuar?"
  },
  "colorPalette": {
    "transparent": "Transparente",
    "custom": "Personalizar"
  },
  "noEditPrivileges": "A sua conta não tem permissão para criar ou modificar dados.",
  "invalidConfiguration": "O widget não se encontra configurado ou as camadas da configuração já não se encontram no mapa.  Por favor, abra a aplicação no modo de builder e reconfigure o widget."
});