define(
   ({
    showArcgisBasemaps: "Grundkarten des Portals einbeziehen",
    settings: "Einstellungen",
    add: "Zum Hinzufügen einer neuen Grundkarte klicken",
    edit: "Eigenschaften",
    title: "Titel",
    titlePH: "Titel der Grundkarte",
    thumbnail: "Miniaturansicht",
    thumbnailHint: "Zum Aktualisieren auf das Bild klicken",
    url: "URL",
    urlPH: "Layer-URL",
    addlayer: "Grundkarte hinzufügen",
    actions: "Aktionen",
    warning: "Falsche Eingabe",
    save: "Zurück und Speichern",
    back: "Zurück und Abbrechen",
    addUrl: "URL hinzufügen",
    autoCheck: "Automatisch überprüfen",
    checking: "Wird überprüft...",
    ok: "OK",
    cancel: "Abbrechen",
    result: "Speichern erfolgreich",
    spError: "Alle Grundkarten, die der Galerie hinzugefügt wurden, müssen denselben Raumbezug aufweisen.",
    invalidTitle1:"Die Grundkarte '",
    invalidTitle2:"' ist bereits vorhanden. Wählen Sie einen anderen Titel aus.",
    invalidBasemapUrl1: "Dieser Layer-Typ kann nicht als Grundkarte verwendet werden.",
    invalidBasemapUrl2: "Die Grundkarte, die Sie hinzufügen, weist einen anderen Raumbezug als die aktuelle Karte auf.",
    addBaselayer: "Grundkarten-Layer hinzufügen"
  })
);