define({
  "common": {
    "apply": "تطبيق",
    "ok": "موافق",
    "cancel": "إلغاء الأمر",
    "yes": "نعم",
    "no": "لا",
    "next": "التالي",
    "previous": "السابق",
    "back": "السابق",
    "selected": "محدد",
    "name": "الاسم",
    "usage": "الاستخدام",
    "settings": "إعدادات",
    "home": "الصفحة الرئيسية",
    "link": "ارتباط",
    "messages": "رسائل",
    "outputs": "المخرجات",
    "title": "العنوان",
    "thumbnail": "صورة مصغرة",
    "url": "عنوان URL",
    "actions": "الأفعال",
    "layer": "طبقة",
    "action": "إجراء",
    "input": "المدخل",
    "output": "الناتج",
    "type": "النوع",
    "required": "مطلوب",
    "options": "خيارات",
    "label": "لافتة التسمية",
    "tooltip": "تلميح الأدوات",
    "visible": "مرئي",
    "symbol": "رمز",
    "popup": "العناصر المنبثقة",
    "upload": "تحميل",
    "execute": "تنفيذ",
    "help": "مساعدة",
    "executing": "تنفيذ",
    "clear": "مسح",
    "error": "خطأ",
    "zoomTo": "تكبير/تصغير إلى",
    "attribute": "بيانات جدولية",
    "exports": "تصدير",
    "check": "تحقق",
    "save": "حفظ",
    "close": "إغلاق",
    "deleteText": "حذف",
    "map": "خريطة",
    "scene": "مشهد",
    "reset": "إعادة تعيين",
    "icon": "أيقونة",
    "share": "مشاركة",
    "view": "عرض",
    "newText": "جديد",
    "edit": "تحرير",
    "wkid": "WKID",
    "table": "جدول",
    "zoomIn": "التكبير",
    "zoomOut": "التصغير.",
    "continue1": "متابعة",
    "longitude": "خط طول",
    "latitude": "خط عرض"
  },
  "errorCode": "كود",
  "errorMessage": "رسالة",
  "errorDetail": "تفاصيل",
  "widgetPlaceholderTooltip": "لتعينها، انتقل إلى عناصر واجهة الاستخدام وانقر على العناصر المتطابقة",
  "fieldStatistics": {
    "selectField": "حدد الحقل",
    "statistics": "الإحصائيات",
    "field": "حقل",
    "count": "رقم القيم",
    "sum": "مجموع القيم",
    "min": "الحد الأدنى",
    "max": "الحد الأقصى",
    "ave": "المتوسط",
    "stddev": "انحراف معياري"
  },
  "symbolChooser": {
    "preview": "معاينة",
    "basic": "أساسي",
    "arrows": "الأسهم",
    "business": "أعمال تجارية",
    "cartographic": "رسم الخرائط",
    "nationalParkService": "خدمة المتنزه الوطني",
    "outdoorRecreation": "ترفيه خارجي",
    "peoplePlaces": "أماكن التجمعات",
    "safetyHealth": "الصحة العامة",
    "shapes": "الأشكال",
    "transportation": "نقل",
    "symbolSize": "حجم الرمز",
    "color": "لون",
    "alpha": "ألفا",
    "outlineColor": "اللون الأساسي",
    "outlineWidth": "العرض التفصيلي",
    "style": "نمط",
    "width": "العرض",
    "text": "النص",
    "fontColor": "لون الخط",
    "fontSize": "حجم الخط",
    "transparency": "معدل الشفافية:",
    "solid": "متصل",
    "dash": "شَرطَة",
    "dot": "نقطة",
    "dashDot": "شَرطَة ونقطة",
    "dashDotDot": "شَرطَة ونقطتين",
    "customImage": "صور مخصصة",
    "chooseFile": "اختيار ملف",
    "noFileChoosen": "لم يتم اختيار الملف."
  },
  "transparency": {
    "opaque": "غير شفاف",
    "transparent": "شفاف"
  },
  "rendererChooser": {
    "domain": "مجال",
    "use": "استخدام",
    "singleSymbol": "رمز أحادي",
    "uniqueSymbol": "رموز فريدة",
    "color": "لون",
    "size": "الحجم",
    "toShow": "لإظهار",
    "colors": "ألوان",
    "classes": "تصنيفات",
    "symbolSize": "حجم الرمز",
    "addValue": "إضافة قيمة",
    "setDefaultSymbol": "تعيين الرمز الافتراضي",
    "defaultSymbol": "الرمز الافتراضي",
    "selectedSymbol": "الرمز المحدد",
    "value": "قيمة",
    "label": "التسمية",
    "range": "النطاق"
  },
  "drawBox": {
    "point": "نقطة",
    "line": "الخط",
    "polyline": "متعدد الخطوط",
    "freehandPolyline": "خط يدوي حر متعدد",
    "triangle": "مثلث",
    "extent": "المدى",
    "circle": "دائرة",
    "ellipse": "قطع ناقص",
    "polygon": "مضلع",
    "freehandPolygon": "مضلع مسوم بخط يدوي حر",
    "text": "النص",
    "clear": "مسح"
  },
  "popupConfig": {
    "title": "عنوان",
    "add": "إضافة",
    "fields": "حقول",
    "noField": "لا توجد حقول",
    "visibility": "مرئي",
    "name": "الاسم",
    "alias": "اسم مستعار",
    "actions": "إجراءات"
  },
  "includeButton": {
    "include": "تضمين"
  },
  "loadingShelter": {
    "loading": "تحميل"
  },
  "basicServiceBrowser": {
    "noServicesFound": "لا توجد خدمات",
    "unableConnectTo": "يتعذر الاتصال بـ",
    "invalidUrlTip": "عنوان URL الذي أدخلته غير صحيح أو يتعذر الوصول إليه."
  },
  "serviceBrowser": {
    "noGpFound": "لا توجد خدمة معالجة جغرافية.",
    "unableConnectTo": "يتعذر الاتصال بـ"
  },
  "layerServiceBrowser": {
    "noServicesFound": "لا توجد خدمة خريطة أو خدمة معالم",
    "unableConnectTo": "يتعذر الاتصال بـ"
  },
  "basicServiceChooser": {
    "validate": "تحقق",
    "example": "مثال",
    "set": "تعيين"
  },
  "urlInput": {
    "invalidUrl": "عنوان URL غير صحيح."
  },
  "urlComboBox": {
    "invalidUrl": "عنوان URL غير صحيح."
  },
  "filterBuilder": {
    "addAnotherExpression": "إضافة تعبير عامل تصفية",
    "addSet": "إضافة مجموعة التعبيرات",
    "matchMsg": "الحصول على المعالم في الطبقة التي تُطابق ${any_or_all} في التعبيرات التالية",
    "matchMsgSet": "${any_or_all} من التعبيرات التالية في هذه المجموعة صحيح",
    "all": "جميع",
    "any": "أي من",
    "value": "قيمة",
    "field": "حقل",
    "unique": "فريد",
    "none": "بلا",
    "and": "و",
    "valueTooltip": "أدخل قيمة",
    "fieldTooltip": "اختيار من حقل حالي",
    "uniqueValueTooltip": "اختيار من قيم فريدة في حقل مُحدد",
    "stringOperatorIs": "هو",
    "stringOperatorIsNot": "ليس",
    "stringOperatorStartsWith": "البدء بـ",
    "stringOperatorEndsWith": "الانتهاء بـ",
    "stringOperatorContains": "يحتوي على",
    "stringOperatorDoesNotContain": "لا يحتوي على",
    "stringOperatorIsBlank": "فارغ",
    "stringOperatorIsNotBlank": "ليس فارغًا",
    "dateOperatorIsOn": "هو",
    "dateOperatorIsNotOn": "ليس",
    "dateOperatorIsBefore": "قبل",
    "dateOperatorIsAfter": "بعد",
    "dateOperatorDays": "يوم",
    "dateOperatorWeeks": "أسبوع",
    "dateOperatorMonths": "شهر",
    "dateOperatorInTheLast": "في آخر",
    "dateOperatorNotInTheLast": "ليس في الآخر",
    "dateOperatorIsBetween": "بين",
    "dateOperatorIsNotBetween": "ليس بين",
    "dateOperatorIsBlank": "فارغ",
    "dateOperatorIsNotBlank": "ليس فارغًا",
    "numberOperatorIs": "هو",
    "numberOperatorIsNot": "ليس",
    "numberOperatorIsAtLeast": "على الأقل",
    "numberOperatorIsLessThan": "أقل من",
    "numberOperatorIsAtMost": "في الغالب",
    "numberOperatorIsGreaterThan": "أكبر من",
    "numberOperatorIsBetween": "بين",
    "numberOperatorIsNotBetween": "ليس بين",
    "numberOperatorIsBlank": "فارغ",
    "numberOperatorIsNotBlank": "ليس فارغًا",
    "string": "سلسلة",
    "number": "عدد",
    "date": "التاريخ",
    "askForValues": "اسأل عن القيم",
    "prompt": "ترقية",
    "hint": "تلميح",
    "error": {
      "invalidParams": "معلمات غير صحيحة.",
      "invalidUrl": "عنوان URL غير صحيح.",
      "noFilterFields": "لا توجد حقول بالطبقة يمكن استخدامها للتصفية.",
      "invalidSQL": "تعبير SQL غير صحيح.",
      "cantParseSQL": "يتعذر توزيع تعبير SQL."
    },
    "caseSensitive": "تحسس حالة الأحرف",
    "notSupportCaseSensitiveTip": "الخدمات المستضافة لا تدعم الاستعلام الحساس للحالة.",
    "setFilterTip": "يرجى تعيين عامل التصفية بشكل صحيح.",
    "listValues": "قيم القائمة",
    "cascadeFilterTip": "عرض القيم التي يتم تصفيتها بواسطة التعبيرات السابقة.",
    "noneCascadeFilterTip": "جميع القيم المميزة لهذا الحقل",
    "previousCascadeFilterTip": "القيم التي يتم تصفيتها بواسطة التعبيرات السابقة",
    "allCascadeFilterTip": "القيم التي يتم تصفيتها بواسطة جميع التعبيرات الأخرى"
  },
  "featureLayerSource": {
    "layer": "طبقة",
    "browse": "استعراض",
    "selectFromMap": "تحديد من الخريطة",
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "inputLayerUrl": "إدخال عنوان URL للطبقة",
    "selectLayer": "تحديد طبقة معالم من الخريطة الحالية.",
    "chooseItem": "اختيار من عنصر طبقة معالم.",
    "setServiceUrl": "أدخل عنوان URL لخدمة المعالم أو خدمة الخريطة.",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "chooseLayer": "اختر طبقة معلم."
  },
  "queryableLayerSource": {
    "layer": "الطبقة",
    "browse": "مربع حوار",
    "selectFromMap": "تحديد من الخريطة",
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "inputLayerUrl": "إدخال عنوان URL للطبقة",
    "selectLayer": "حدد طبقة من الخريطة الحالية.",
    "chooseItem": "اختر عنصر.",
    "setServiceUrl": "أدخل عنوان URL للخدمة.",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "chooseLayer": "اختيار الطبقة"
  },
  "gpSource": {
    "selectFromPortal": "إضافة من Portal for ArcGIS",
    "addServiceUrl": "إضافة عنوان URL للخدمة",
    "selectFromOnline": "إضافة من ArcGIS Online",
    "setServiceUrl": "أدخل عنوان URL لخدمة المعالجة الجغرافية.",
    "chooseItem": "اختر عنصر خدمة المعالجة الجغرافية.",
    "chooseTask": "اختر مهمة المعالجة الجغرافية."
  },
  "itemSelector": {
    "map": "خريطة",
    "selectWebMap": "اختر خريطة الويب",
    "addMapFromOnlineOrPortal": "العثور على خريطة الويب وإضافتها للاستخدام في التطبيق من موارد ArcGIS Online العامة أو المحتويات الخاصة في ArcGIS Online أو البوابة الإلكترونية.",
    "searchMapName": "ابحث باستخدام اسم الخريطة...",
    "searchNone": "يتعذر إيجاد ما تبحث عنه. يرجى المحاولة مرة أخرى.",
    "groups": "مجموعات",
    "noneGroups": "لا توجد مجموعات",
    "signInTip": "انتهت صلاحية جلسة تسجيل الدخول، يرجى تنشيط المتصفح لتسجيل الدخول للمدخل مرة أخرى.",
    "signIn": "تسجيل الدخول",
    "publicMap": "عام",
    "myOrganization": "المنظمة",
    "myGroup": "المجموعات",
    "myContent": "المحتوى",
    "count": "عدد",
    "fromPortal": "من البوابة الإلكترونية",
    "fromOnline": "من ArcGIS.com",
    "noneThumbnail": "الصورة المصغرة غير متاحة",
    "owner": "المالك",
    "signInTo": "تسجيل الدخول إلى",
    "lastModified": "آخر تعديل",
    "moreDetails": "المزيد من التفاصيل",
    "mostRecent": "الأحدث",
    "mostViewed": "الأكثر مشاهدةً",
    "highestRated": "الأعلى تصنيفًا",
    "viewItemDetails": "عرض تفاصيل العنصر"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "الخدمة لا تدعم الاستعلام."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "لا تتوفر طبقة مناسبة داخل الخريطة."
  },
  "layerInfosMenu": {
    "titleBasemap": "خرائط الأساس",
    "titleLayers": "الطبقات التشغيلية",
    "labelLayer": "اسم الطبقة",
    "itemZoomTo": "تكبير إلى",
    "itemTransparency": "معدل الشفافية:",
    "itemTransparent": "شفاف",
    "itemOpaque": "غير شفاف",
    "itemMoveUp": "نقل لأعلى",
    "itemMoveDown": "نقل لأسفل",
    "itemDesc": "الوصف",
    "itemDownload": "تنزيل",
    "itemToAttributeTable": "فتح جدول البيانات الجدولية"
  },
  "imageChooser": {
    "unsupportReaderAPI": "قائمة المهام: المستعرض لا يدعم API لقارئ الملف",
    "readError": "فشل قراءة الملف.",
    "unknowError": "يتعذر إكمال العمليات",
    "invalidType": "نوع الملف غير صحيح.",
    "cropImage": "قص الصورة",
    "exceed": "لا يجوز أن يتجاوز حجم الملف 1024 كيلوبايت",
    "enableFlash": "الرجاء تمكين Adobe Flash قبل استعراض الصور.",
    "cropWaining": "يرجى اختيار صورة على الأقل ${عرض} x ${طول} بكسل.",
    "toolTip": "للحصول على أفضل نتيجة، ينبغي أن يكون حجم الصورة ${width} بيكسل وارتفاعها ${height} بيكسل. سيتم تعديل الأحجام الأخرى للملائمة. تنسيقات الصورة المقبولة هي PNG وGIF وJPEG."
  },
  "simpleTable": {
    "moveUp": "نقل لأعلى",
    "moveDown": "نقل لأسفل",
    "deleteRow": "حذف",
    "edit": "تحرير"
  },
  "urlParams": {
    "invalidToken": "رمز مميز غير صالح",
    "validateTokenError": "رمز مميز غير صحيح أو خطأ بالشبكة"
  },
  "exportTo": {
    "exportTo": "تصدير",
    "toCSV": "تصدير لملف CSV",
    "toFeatureCollection": "التصدير إلى مجموعة المعالم",
    "toGeoJSON": "التصدير إلى GeoJSON"
  },
  "appState": {
    "title": "حالة التطبيق",
    "restoreMap": "انقر لاستعادة مدى الخريطة ورؤية الطبقات حيث توقفت."
  },
  "featureActions": {
    "featureActions": "إجراءات المعالم",
    "ZoomTo": "تكبير/تصغير إلى",
    "PanTo": "التحريك إلى",
    "Flash": "وميض",
    "ShowPopup": "إظهار القائمة المنبثقة",
    "CreateLayer": "إنشاء طبقة",
    "ShowStatistics": "الإحصائيات...",
    "ClearSelection": "مسح التحديد",
    "ExportToCSV": "تصدير لملف CSV",
    "ShowSelectedFeature": "عرض المعالم المحددة",
    "ExportToFeatureCollection": "التصدير إلى مجموعة المعالم",
    "ExportToGeoJSON": "التصدير إلى GeoJSON",
    "AddMarker": "إضافة علامة",
    "RemoveMarker": "إزالة علامة"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "الطبقات المرتبطة",
    "selectedFeatures": "استخدام المعالم المحددة",
    "drawShapesTip": "رسم الأشكال لتحديد المعالم",
    "pleaseDrawShapesTip": "يرجى رسم أشكال لتحديد المعالم",
    "allFeaturesTip": "كل المعالم في الطبقة",
    "selectFeaturesOrDrawShapesTip": "يرجى استخدام المعالم المحددة في هذه الطبقة أو رسم أشكال على الخريطة لتحديد المعالم."
  },
  "searchDistance": {
    "applySearchDistance": "تطبيق مسافة البحث",
    "applySearchDistanceToFeatures": "قم بتطبيق مسافة بحث للمعالم المحددة"
  },
  "units": {
    "miles": "أميال",
    "kilometers": "كيلومترات",
    "feet": "قدم",
    "meters": "أمتار",
    "yards": "ياردات",
    "nauticalMiles": "أميال محايدة"
  },
  "featureSetChooser": {
    "select": "تحديد",
    "dragBox": "سحب",
    "dragMouse": "اسحب الماوس",
    "selectByRectangle": "تحديد بواسطة مستطيل",
    "selectFeaturesTip": "حدد المعالم بسحب المربع حولها على الخريطة",
    "newSelectionTip": "إنشاء تحديد جديد",
    "addSelectionTip": "إضافة للاختيارات",
    "removeSelectionTip": "إزالة من التحديد",
    "selectFromCurrentSelectionTip": "تحديد من التحديد الحالي",
    "unselectAllSelectionTip": "ألغ تحديد كل المعالم المحددة حاليًا",
    "selectByPolygon": "تحديد بواسطة المضلع",
    "selectByCircle": "تحديد بواسطة دائرة",
    "selectByLine": "تحديد بواسطة خط",
    "chooseSelectingTools": "اختر أدوات التحديد",
    "darw": "رسم",
    "drawShap": "رسم شكل"
  },
  "widgetManager": {
    "createWidgetError": "خطأ في إنشاء عنصر واجهة المستخدم",
    "createWidgetSettingPageError": "خطأ في صفحة إعدادات إنشاء عنصر واجهة المستخدم",
    "loadWidgetResourceError": "خطأ في تحميل مورد عنصر واجهة المستخدم"
  },
  "shareOptions": {
    "shareMap": "اختر المستخدمين الذين يمكنهم عرض هذا التطبيق",
    "shareMapTips": "تم مشاركة تطبيقك مع هؤلاء المستخدمين الآن",
    "everyone": "الكل",
    "theseGroups": "هذه المجموعات"
  },
  "shareLink": {
    "email": "البريد الإلكتروني",
    "shareEmail": "البريد الإلكتروني",
    "facebook": "facebook",
    "shareFacebook": "فيس بوك",
    "twitter": "twitter",
    "shareTwitter": "تويتر",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "تضمين هذا التطبيق في موقع ويب",
    "shareEmailSubject": "مشاركة تطبيق الويب:",
    "shareEmailTxt1": "هنا يوجد تطبيق ويب تم مشاركته معك باستخدام Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "يمكنك إنشاء تطبيق الويب الخاص بك ومشاركته مع Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "تفضل بزيارة http://www.esri.com/software/web-appbuilder للتفاصيل.",
    "smallSize": "صغير",
    "mediumSize": "متوسط",
    "largeSize": "كبير",
    "customSize": "تخصيص",
    "embed": "تضمين هذا التطبيق في موقع ويب",
    "more": "الخيارات المضمنة",
    "changeShareSettings": "تغيير إعدادات المشاركة",
    "shareLinkText": "مشاركة رابط لهذا التطبيق",
    "linkOptions": "خيارات الرابط",
    "linkOptionsUrlParameters": "حدد معلمات عنوان URL المُضمّن في الرابط",
    "currentMapExtent": "مدى الخريطة الحالي",
    "chooseCenterWithLevel": "انقر على الخريطة لتعريف مركز الخريطة بمستوى التكبير/التصغير",
    "chooseCenterWithScale": "انقر على الخريطة لتعريف مركز الخريطة بمقياس الخريطة",
    "findLocation": "ابحث عن الموقع أو المعلم وقم بالتكبير/التصغير",
    "findLocation_inputPlaceholder": "موقعك أو مَعلَمَك",
    "queryFeature": "استعلم عن معلم وقم بتكبيره/تصغيره",
    "addMarker": "أضف علامة على الخريطة",
    "addMarker_titlePlaceholder": "عنوان العنصر المنبثق للعلامة",
    "addMarker_symbolURL": "عنوان URL لرمز العلامة",
    "addMarker_label": "تسمية العلامة",
    "popupTitle": "عنوان النافذة المنبثقة",
    "zoomLevel": "مستوى التكبير/التصغير",
    "overwirteMobileLayout": "استبدال حجم الشاشة الافتراضي لتخطيط الجوّال",
    "language": "قم بتعيين لغة عرض التطبيق",
    "auth": "مصادقة مستخدم تلقائيًا",
    "linkPreview": "معاينة الرابط",
    "useShortenLink": "رابط قصير",
    "shareMapUrlExtent": "مشاركة نطاق الخريطة الحالي",
    "shareToWebTips": "لم يتم مشاركة هذا التطبيق مع كل المستخدمين، وقد يتعذر عليهم عرضه."
  },
  "webSceneLoader": {
    "webglSupportTip": "تطبيقات الويب ثلاثية الأبعاد غير مدعومة في المستعرض."
  },
  "map": {
    "basemapNotAvailable": "لم تتوافر خريطة الأساس.",
    "displayDefaultBasemap": "عرض خريطة الأساس الافتراضية بدلاً من ذلك."
  },
  "popup": {
    "relatedTables": "الجداول ذات الصلة:",
    "relatedRecords": "السجلات ذات الصلة:",
    "noRelatedRecotds": "لم يتم العثور على سجلات ذات صلة"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "يوجد الكثير جدًا من المعالم في التحديد الخاص بك. قد يستغرق وقتًا طويلاً لاستعادتهم وعرضهم على الخريطة.",
    "askForContinue": "هل تريد المتابعة؟"
  },
  "colorPalette": {
    "transparent": "شفاف",
    "custom": "تخصيص"
  },
  "noEditPrivileges": "لا يحتوي حسابك على أذونات لإنشاء أو تعديل البيانات.",
  "invalidConfiguration": "لم يتم تكوين عنصر واجهة المستخدم أو أن الطبقات التي توجد في التكوين لم تُعد موجودة في الخريطة. يرجى فتح التطبيق في وضع المُنشئ وإعادة تكوين عنصر واجهة المستخدم."
});