define({
  "defaultAreaUnit": "Unitate de suprafaţă implicită",
  "defaultLengthUnit": "Unitate de lungime implicită",
  "acres": "Acri",
  "sqMiles": "Mile pătrate",
  "sqKilometers": "Kilometri pătraţi",
  "hectares": "Hectare",
  "sqYards": "Yarzi pătraţi",
  "sqFeet": "Picioare pătrate",
  "sqFeetUS": "Picior pătrat (SUA)",
  "sqMeters": "Metri pătraţi",
  "miles": "Mile",
  "kilometers": "Kilometri",
  "feet": "Ft",
  "feetUS": "Picioare (SUA)",
  "meters": "Metri",
  "yards": "Yarzi",
  "nauticalMiles": "Mile marine",
  "showArea": "Suprafaţă",
  "showDistance": "Distanţă",
  "showLocation": "Locaţie",
  "showtools": "Afişare instrumente de măsură:",
  "allHidedTips": "Trebuie selectat cel puţin un instrument."
});