define({
  "defaultAreaUnit": "ברירת מחדל ליחידת שטח",
  "defaultLengthUnit": "ברירת מחדל ליחידת אורך",
  "acres": "אקרים",
  "sqMiles": "מיילים רבועים",
  "sqKilometers": "קילומטרים רבועים",
  "hectares": "הקטרים",
  "sqYards": "יארדים רבועים",
  "sqFeet": "רגל רבוע",
  "sqFeetUS": "רגל רבוע (ארה\"ב)",
  "sqMeters": "מטרים רבועים",
  "miles": "מיילים",
  "kilometers": "קילומטרים",
  "feet": "רגל",
  "feetUS": "רגל (ארה\"ב)",
  "meters": "מטרים",
  "yards": "יארד",
  "nauticalMiles": "מיילים ימיים",
  "showArea": "שטח",
  "showDistance": "מרחק",
  "showLocation": "מיקום",
  "showtools": "הצג כלי מדידה:",
  "allHidedTips": "יש לבחור לפחות כלי אחד."
});