define({
  "defaultAreaUnit": "預設面積單位",
  "defaultLengthUnit": "預設長度單位",
  "acres": "英畝",
  "sqMiles": "平方英里",
  "sqKilometers": "平方公里",
  "hectares": "公頃",
  "sqYards": "平方碼",
  "sqFeet": "平方英呎",
  "sqFeetUS": "平方英呎 (美制)",
  "sqMeters": "平方公尺",
  "miles": "英里",
  "kilometers": "公里",
  "feet": "英呎",
  "feetUS": "英呎 (美制)",
  "meters": "公尺",
  "yards": "碼",
  "nauticalMiles": "海浬",
  "showArea": "面積",
  "showDistance": "距離",
  "showLocation": "位置",
  "showtools": "顯示測量工具:",
  "allHidedTips": "必須至少選擇一個工具。"
});