define(
   ({
    showArcgisBasemaps: "כלול מפות בסיס של הפורטל",
    settings: "הגדרות",
    add: "לחץ להוספת מפת בסיס חדשה",
    edit: "מאפיינים",
    title: "כותרת",
    titlePH: "כותרת מפת בסיס",
    thumbnail: "תמונה ממוזערת",
    thumbnailHint: "לחץ על התמונה לעדכון",
    url: "URL",
    urlPH: "כתובת URL של שכבה",
    addlayer: "הוסף מפת בסיס",
    actions: "פעולות",
    warning: "קלט לא תקין",
    save: "חזור ושמור",
    back: "חזור ובטל",
    addUrl: "הוסף URL",
    autoCheck: "בדיקה אוטומטית",
    checking: "בודק...",
    ok: "אישור",
    cancel: "ביטול",
    result: "נשמר בהצלחה",
    spError: "היחוס המרחבי בכל מפות הבסיס המתווספות לגלריה חייב להיות זהה.",
    invalidTitle1:"מפת בסיס בשם '",
    invalidTitle2:"' כבר קיימת. בחר כותרת אחרת.",
    invalidBasemapUrl1: "שכבה מסוג זה אינה יכולה לשמש כמפת בסיס.",
    invalidBasemapUrl2: "היחוס המרחבי במפת הבסיס שאתה מוסיף שונה מזה הקיים במפה הנוכחית.",
    addBaselayer: "הוסף שכבה של מפת בסיס"
  })
);