define({
  "sourceSetting": "Configurações da Fonte de Pesquisa",
  "instruction": "Adicione e configure serviços de geocódigo ou camadas de feição como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
  "add": "Adicionar Fonte de Pesquisa",
  "addGeocoder": "Adicionar Geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Configurar Origem da Camada",
  "setGeocoderURL": "Configurar URL do Geocodificador",
  "searchableLayer": "Camada de Feição",
  "name": "Nome",
  "countryCode": "Códigos de Região e País",
  "countryCodeEg": "por exemplo ",
  "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
  "generalSetting": "Configurações Gerais",
  "allPlaceholder": "Texto de local reservado para pesquisar todos: ",
  "showInfoWindowOnSelect": "Mostrar pop-up do local ou feição localizada",
  "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
  "zoomScale": "Escala de Zoom",
  "locatorUrl": "URL do Geocodificador",
  "locatorName": "Nome do Geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportado. O widget suporta serviço de geocodificação 10.0 e superior.",
  "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
  "layerSource": "Origem da Camada",
  "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
  "placeholder": "Texto do Placeholder",
  "searchFields": "Pesquisar Campos",
  "displayField": "Campo de Visualização",
  "exactMatch": "Combinação Exata",
  "maxSuggestions": "Máximo de Sugestões",
  "maxResults": "Máximo de Resultados",
  "enableLocalSearch": "Habilitar pesquisa de local",
  "minScale": "Escala Mín",
  "minScaleHint": "Quando a escala do mapa for maior que esta escala, a pesquisa de local será aplicada",
  "radius": "Raio",
  "radiusHint": "Especifica o raio de uma área ao redor do centro do mapa atual que é utilizado para impulsionar o grau de candidatos de geocodificação de forma que os candidatos mais próximos ao local sejam retornados primeiro",
  "meters": "Metros",
  "setSearchFields": "Configurar Campos de Pesquisa",
  "set": "Configurar",
  "fieldSearchable": "pesquisável",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "ok": "OK",
  "cancel": "Cancelar",
  "invalidUrlTip": "A URL ${URL} é inválida ou inacessível."
});