define({
  "sourceSetting": "Definições de Fonte de Pesquisa",
  "instruction": "Adicionar e configurar serviços de geocodificação ou camadas de elemento como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
  "add": "Adicionar Fonte de Pesquisa",
  "addGeocoder": "Adicionar um Geocoder",
  "geocoder": "Geocodificador",
  "setLayerSource": "Definir Fonte de Camada",
  "setGeocoderURL": "Definir URL Geocodificador",
  "searchableLayer": "Camada de Elementos",
  "name": "Nome",
  "countryCode": "Código(s) de País ou Região",
  "countryCodeEg": "e.g ",
  "countryCodeHint": "Ao deixar este valor em branco irá pesquisar em todos os países e regiões",
  "generalSetting": "Configurações Gerais",
  "allPlaceholder": "Texto de placeholder para pesquisar todos: ",
  "showInfoWindowOnSelect": "Exibir janela pop-up para o elemento ou local encontrado.",
  "searchInCurrentMapExtent": "Procurar apenas na extensão de mapa actual.",
  "zoomScale": "Escala de Zoom",
  "locatorUrl": "Geocoder URL",
  "locatorName": "Nome do Geocoder",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportada. O widget suporta serviço de geocodificação 10.0 e posterior.",
  "locatorTips": "Sugestões não estão disponíveis porque o serviço de geocodificação não suporta a capacidade sugerida.",
  "layerSource": "Camada Fonte",
  "searchLayerTips": "Sugestões não estão disponíveis porque o serviço de elemento não suporta capacidades de paginação.",
  "placeholder": "Local de introdução de texto",
  "searchFields": "Campos de Pesquisa",
  "displayField": "Exibir Campo",
  "exactMatch": "Correspondência Exacta",
  "maxSuggestions": "Sugestões Máximas",
  "maxResults": "Resultados Máximos",
  "enableLocalSearch": "Ativar pesquisa local",
  "minScale": "Escala Mínima",
  "minScaleHint": "Quando a escala do mapa é superior a esta escala, será aplicada a pesquisa local",
  "radius": "Raio",
  "radiusHint": "Especifica o raio de uma área em torno do atual centro do mapa, que é utilizada para impulsionar a classificação de candidatos a geocodificação para que os candidatos que se encontram mais perto do local sejam apresentados nas primeiras posições.",
  "meters": "Metros",
  "setSearchFields": "Definir Campos de Pesquisa",
  "set": "Definir",
  "fieldSearchable": "pesquisável",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "ok": "OK",
  "cancel": "Cancelar",
  "invalidUrlTip": "O URL ${URL} é inválido ou inacessível."
});