define({
  "defaultAreaUnit": "Unidade de área predefinida",
  "defaultLengthUnit": "Unidade de comprimento predefinida",
  "acres": "Acres",
  "sqMiles": "Milhas quadradas",
  "sqKilometers": "Quilómetros quadrados",
  "hectares": "Hectares",
  "sqYards": "Jardas quadradas",
  "sqFeet": "Pés quadrados",
  "sqFeetUS": "Pés quadrados (EUA)",
  "sqMeters": "Metros quadrados",
  "miles": "Milhas",
  "kilometers": "Quilómetros",
  "feet": "Pés",
  "feetUS": "Pés (EUA)",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Exibir ferramentas de medição:",
  "allHidedTips": "Tem de ser selecionada pelo menos uma ferramenta."
});