define({
  "defaultAreaUnit": "Standardflächeneinheit",
  "defaultLengthUnit": "Standardlängeneinheit",
  "acres": "Acres",
  "sqMiles": "Quadratmeilen",
  "sqKilometers": "Quadratkilometer",
  "hectares": "Hektar",
  "sqYards": "Quadratyard",
  "sqFeet": "Quadratfuß",
  "sqFeetUS": "Quadratfuß (US)",
  "sqMeters": "Quadratmeter",
  "miles": "Meilen",
  "kilometers": "Kilometer",
  "feet": "Fuß",
  "feetUS": "Fuß (US)",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Seemeilen",
  "showArea": "Fläche",
  "showDistance": "Entfernung",
  "showLocation": "Standort",
  "showtools": "Messwerkzeuge anzeigen:",
  "allHidedTips": "Es sollte mindestens ein Werkzeug ausgewählt werden."
});