define(
   ({
    showArcgisBasemaps: "Includi mappe di base del portale",
    settings: "Impostazioni",
    add: "Fare clic per aggiungere una nuova mappa di base",
    edit: "Proprietà",
    title: "Titolo",
    titlePH: "Titolo mappa di base",
    thumbnail: "Anteprima",
    thumbnailHint: "Fare clic sull\'immagine per aggiornare",
    url: "URL",
    urlPH: "URL layer",
    addlayer: "Aggiungi mappa di base",
    actions: "Azioni",
    warning: "Input errato",
    save: "Torna e salva",
    back: "Torna e annulla",
    addUrl: "Aggiungi URL",
    autoCheck: "Verifica automatica",
    checking: "Verifica in corso...",
    ok: "OK",
    cancel: "Annulla",
    result: "Salvataggio riuscito",
    spError: "Tutte le mappe di base aggiunte alla galleria devono avere lo stesso riferimento spaziale.",
    invalidTitle1:"Una mappa di base '",
    invalidTitle2:"' esiste già. Scegliere un altro titolo.",
    invalidBasemapUrl1: "Questo tipo di layer non può essere utilizzato come mappa di base.",
    invalidBasemapUrl2: "La mappa di base che si sta aggiungendo ha un riferimento spaziale diverso dalla mappa corrente.",
    addBaselayer: "Aggiungi layer mappa base"
  })
);