define({
  "defaultAreaUnit": "Standard arealenhet",
  "defaultLengthUnit": "Standard lengdeenhet",
  "acres": "Acre",
  "sqMiles": "mile²",
  "sqKilometers": "km²",
  "hectares": "Hektar",
  "sqYards": "yard²",
  "sqFeet": "fot²",
  "sqFeetUS": "fot² (USA)",
  "sqMeters": "m²",
  "miles": "Miles",
  "kilometers": "Kilometer",
  "feet": "Fot",
  "feetUS": "fot (USA)",
  "meters": "Meter",
  "yards": "Yards",
  "nauticalMiles": "Nautiske mil",
  "showArea": "Område",
  "showDistance": "Avstand",
  "showLocation": "Lokasjon",
  "showtools": "Vis måleverktøy:",
  "allHidedTips": "Du må velge minst ett verktøy."
});