define({
  root: ({
    defaultAreaUnit: "Default area unit",
    defaultLengthUnit: "Default length unit",
    acres: "Acres",
    sqMiles: "Sq miles",
    sqKilometers: "Sq kilometers",
    hectares: "Hectares",
    sqYards: "Sq yards",
    sqFeet: "Sq feet",
    sqFeetUS: "Sq feet (US)",
    sqMeters: "Sq meters",
    miles: "Miles",
    kilometers: "Kilometers",
    feet: "Feet",
    feetUS: "Feet (US)",
    meters: "Meters",
    yards: "Yards",
    nauticalMiles: "Nautical miles",
    showArea: "Area",
    showDistance: "Distance",
    showLocation: "Location",
    showtools: "Show measurement tools:",
    allHidedTips: "At least one tool should be selected."
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});