define({
  "defaultAreaUnit": "Podrazumevana jedinica površine",
  "defaultLengthUnit": "Podrazumevana jedinica dužine",
  "acres": "Ari",
  "sqMiles": "Kvadratne milje",
  "sqKilometers": "Kvadratni kilometri",
  "hectares": "Hektari",
  "sqYards": "Kvadratni jardi",
  "sqFeet": "Kvadratne stope",
  "sqFeetUS": "Kvadratne stope (SAD)",
  "sqMeters": "Kvadratni metri",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "feetUS": "Stope (SAD)",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "showArea": "Površina",
  "showDistance": "Rastojanje",
  "showLocation": "Lokacija",
  "showtools": "Prikaži alate za merenje:",
  "allHidedTips": "Bar jedan alat treba da bude izabran."
});