define({
  "defaultAreaUnit": "Unidade de área padrão",
  "defaultLengthUnit": "Unidade de comprimento padrão",
  "acres": "Acres",
  "sqMiles": "Milhas quadradas",
  "sqKilometers": "Quilômetros quadrados",
  "hectares": "Hectares",
  "sqYards": "Jardas quadradas",
  "sqFeet": "Pés quadrados",
  "sqFeetUS": "Pés quadrados (US)",
  "sqMeters": "Metros quadrados",
  "miles": "Milhas",
  "kilometers": "Quilômetros",
  "feet": "Pés",
  "feetUS": "Pés (US)",
  "meters": "Metros",
  "yards": "Jardas",
  "nauticalMiles": "Milhas náuticas",
  "showArea": "Área",
  "showDistance": "Distância",
  "showLocation": "Localização",
  "showtools": "Mostrar ferramentas de medição:",
  "allHidedTips": "Pelo menos uma ferramenta deve ser selecionada."
});