define({
  "defaultAreaUnit": "Varsayılan alan birimi",
  "defaultLengthUnit": "Varsayılan uzunluk birimi",
  "acres": "İngiliz Dönümü",
  "sqMiles": "Mil kare",
  "sqKilometers": "Kilometre kare",
  "hectares": "Hektar",
  "sqYards": "Yarda kare",
  "sqFeet": "Fit kare",
  "sqFeetUS": "Feet kare (ABD)",
  "sqMeters": "Metre kare",
  "miles": "Mil",
  "kilometers": "Kilometre",
  "feet": "Fit",
  "feetUS": "Feet (ABD)",
  "meters": "Metre",
  "yards": "Yarda",
  "nauticalMiles": "Deniz mili",
  "showArea": "Alan",
  "showDistance": "Mesafe",
  "showLocation": "Konum",
  "showtools": "Ölçüm araçlarını göster:",
  "allHidedTips": "En az bir araç seçilmelidir."
});