define({
  "defaultAreaUnit": "默认面积单位",
  "defaultLengthUnit": "默认长度单位",
  "acres": "英亩",
  "sqMiles": "平方英里",
  "sqKilometers": "平方千米",
  "hectares": "公顷",
  "sqYards": "平方码",
  "sqFeet": "平方英尺",
  "sqFeetUS": "平方英尺(US)",
  "sqMeters": "平方米",
  "miles": "英里",
  "kilometers": "千米",
  "feet": "英尺",
  "feetUS": "英尺(US)",
  "meters": "米",
  "yards": "码",
  "nauticalMiles": "海里",
  "showArea": "面积",
  "showDistance": "距离",
  "showLocation": "位置",
  "showtools": "显示测量工具:",
  "allHidedTips": "必须至少选择一个工具。"
});