define({
  "common": {
    "apply": "Taikyti",
    "ok": "Gerai",
    "cancel": "Atšaukti",
    "yes": "Taip",
    "no": "Ne",
    "next": "Kitas",
    "previous": "Ankstesnis",
    "back": "Atgal",
    "selected": "pažymėta",
    "name": "Pavadinimas",
    "usage": "Naudojimas",
    "settings": "Nuostatos",
    "home": "Pradžia",
    "link": "Nuoroda",
    "messages": "Pranešimai",
    "outputs": "Išvestys",
    "title": "Pavadinimas",
    "thumbnail": "Miniatiūra",
    "url": "URL",
    "actions": "Veiksmai",
    "layer": "Sluoksnis",
    "action": "Veiksmas",
    "input": "Įvestis",
    "output": "Išvestis",
    "type": "Tipas",
    "required": "Privalomas",
    "options": "Parinktys",
    "label": "Žymė",
    "tooltip": "Įrankio užuomina",
    "visible": "Matoma",
    "symbol": "Simbolis",
    "popup": "Iškylantis langas",
    "upload": "Įkelti",
    "execute": "Vykdyti",
    "help": "Pagalba",
    "executing": "Vykdoma",
    "clear": "Valyti",
    "error": "Klaida",
    "zoomTo": "Parodyti visą",
    "attribute": "Aprašas",
    "exports": "Eksportuoti",
    "check": "Tikrinti",
    "save": "Įrašyti",
    "close": "Uždaryti",
    "deleteText": "Pašalinti",
    "map": "Žemėlapis",
    "scene": "Scena",
    "reset": "Atkurti",
    "icon": "Piktograma",
    "share": "Bendrinti",
    "view": "Peržiūrėti",
    "newText": "Naujas",
    "edit": "Redaguoti",
    "wkid": "WKID",
    "table": "Lentelė",
    "zoomIn": "Artinti",
    "zoomOut": "Tolinti",
    "continue1": "Tęsti",
    "longitude": "Ilguma",
    "latitude": "Platuma"
  },
  "errorCode": "Kodas",
  "errorMessage": "Pranešimas",
  "errorDetail": "Išsamiau",
  "widgetPlaceholderTooltip": "Norėdami nustatyti, eikite į valdiklių dalį ir spustelėkite atitinkamą vietą",
  "fieldStatistics": {
    "selectField": "Pažymėti lauką",
    "statistics": "Statistika",
    "field": "Laukas",
    "count": "Reikšmių skaičius",
    "sum": "Reikšmių suma",
    "min": "Minimumas",
    "max": "Maksimumas",
    "ave": "Vidutinis",
    "stddev": "Standartinis nuokrypis"
  },
  "symbolChooser": {
    "preview": "Peržiūra",
    "basic": "Bazinis",
    "arrows": "Rodyklės",
    "business": "Verslas",
    "cartographic": "Kartografijos",
    "nationalParkService": "Nacionalinių parkų tarnyba",
    "outdoorRecreation": "Pramogos lauke",
    "peoplePlaces": "Žmonių susibūrimo vietos",
    "safetyHealth": "Sauga ir sveikata",
    "shapes": "Formos",
    "transportation": "Transportas",
    "symbolSize": "Simbolio dydis",
    "color": "Spalva",
    "alpha": "Alfa",
    "outlineColor": "Kontūro spalva",
    "outlineWidth": "Kontūro plotis",
    "style": "Stilius",
    "width": "Plotis",
    "text": "Tekstas",
    "fontColor": "Šrifto spalva",
    "fontSize": "Šrifto dydis",
    "transparency": "Permatomumas",
    "solid": "Vientisas",
    "dash": "Brūkšnys",
    "dot": "Taškas",
    "dashDot": "Brūkšnys taškas",
    "dashDotDot": "Brūkšnys taškas taškas",
    "customImage": "Adaptuotas vaizdas",
    "chooseFile": "Pasirinkite failą",
    "noFileChoosen": "Nepasirinktas joks failas."
  },
  "transparency": {
    "opaque": "Nepermatomas",
    "transparent": "Permatomas"
  },
  "rendererChooser": {
    "domain": "Domenas",
    "use": "Naudoti",
    "singleSymbol": "Vieną simbolį",
    "uniqueSymbol": "Skirtingus simbolius",
    "color": "Spalva",
    "size": "Dydis",
    "toShow": "Rodyti",
    "colors": "Spalvos",
    "classes": "Klasės",
    "symbolSize": "Simbolio dydis",
    "addValue": "Pridėti reikšmę",
    "setDefaultSymbol": "Nustatyti numatytąjį simbolį",
    "defaultSymbol": "Numatytasis simbolis",
    "selectedSymbol": "Pasirinktas simbolis",
    "value": "Reikšmė",
    "label": "Žymė",
    "range": "Intervalas"
  },
  "drawBox": {
    "point": "Taškas",
    "line": "Linija",
    "polyline": "Kreivė",
    "freehandPolyline": "Laisvai piešiama kreivė",
    "triangle": "Trikampis",
    "extent": "Aprėptis",
    "circle": "Apskritimas",
    "ellipse": "Elipsė",
    "polygon": "Poligonas",
    "freehandPolygon": "Laisvai piešiamas poligonas",
    "text": "Tekstas",
    "clear": "Valyti"
  },
  "popupConfig": {
    "title": "Pavadinimas",
    "add": "Pridėti",
    "fields": "Laukai",
    "noField": "Lauko nėra",
    "visibility": "Matoma",
    "name": "Pavadinimas",
    "alias": "Pseudonimas",
    "actions": "Veiksmai"
  },
  "includeButton": {
    "include": "Įtraukti"
  },
  "loadingShelter": {
    "loading": "Kraunama"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie",
    "invalidUrlTip": "URL, kurį nurodėte yra arba neteisingas, arba nepasiekiamas."
  },
  "serviceBrowser": {
    "noGpFound": "Geoduomenų apdorojimo paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Žemėlapių paslaugų arba elementų paslaugų nerasta.",
    "unableConnectTo": "Nepavyksta prisijungti prie"
  },
  "basicServiceChooser": {
    "validate": "Tikrinti",
    "example": "Pavyzdys",
    "set": "Nustatyti"
  },
  "urlInput": {
    "invalidUrl": "Neleistinas URL."
  },
  "urlComboBox": {
    "invalidUrl": "Neleistinas URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Pridėti filtro sąlygą",
    "addSet": "Pridėti išraiškų rinkinį",
    "matchMsg": "Gauti elementus sluoksnyje, kurie atitinka šias sąlygas: ${any_or_all}",
    "matchMsgSet": "${any_or_all} iš grupėje esančių sąlygų yra teisinga (-os)",
    "all": "Viskas",
    "any": "Bet kuri",
    "value": "Reikšmė",
    "field": "Laukas",
    "unique": "Unikalios",
    "none": "Nėra",
    "and": "ir",
    "valueTooltip": "Įveskite reikšmę",
    "fieldTooltip": "Pasirinkite iš esamo lauko",
    "uniqueValueTooltip": "Pažymėtame lauke pasirinkite unikalias reikšmes",
    "stringOperatorIs": "yra",
    "stringOperatorIsNot": "nėra",
    "stringOperatorStartsWith": "prasideda su",
    "stringOperatorEndsWith": "baigiasi su",
    "stringOperatorContains": "įraše yra",
    "stringOperatorDoesNotContain": "įraše nėra",
    "stringOperatorIsBlank": "yra tuščias",
    "stringOperatorIsNotBlank": "nėra tuščias",
    "dateOperatorIsOn": "yra ant",
    "dateOperatorIsNotOn": "yra ne ant",
    "dateOperatorIsBefore": "yra prieš",
    "dateOperatorIsAfter": "yra po",
    "dateOperatorDays": "dienos",
    "dateOperatorWeeks": "savaitės",
    "dateOperatorMonths": "mėnesiai",
    "dateOperatorInTheLast": "yra paskutinis",
    "dateOperatorNotInTheLast": "nėra paskutinis",
    "dateOperatorIsBetween": "yra tarp",
    "dateOperatorIsNotBetween": "nėra tarp",
    "dateOperatorIsBlank": "yra tuščias",
    "dateOperatorIsNotBlank": "nėra tuščias",
    "numberOperatorIs": "yra",
    "numberOperatorIsNot": "nėra",
    "numberOperatorIsAtLeast": "yra mažiausia (bent)",
    "numberOperatorIsLessThan": "yra mažiau nei",
    "numberOperatorIsAtMost": "yra daugiausia",
    "numberOperatorIsGreaterThan": "yra daugiau nei",
    "numberOperatorIsBetween": "yra tarp",
    "numberOperatorIsNotBetween": "nėra tarp",
    "numberOperatorIsBlank": "yra tuščias",
    "numberOperatorIsNotBlank": "nėra tuščias",
    "string": "Eilutė",
    "number": "Skaičius",
    "date": "Data",
    "askForValues": "Klausti reikšmių",
    "prompt": "Įveskite",
    "hint": "Užuomina",
    "error": {
      "invalidParams": "Neleistini parametrai.",
      "invalidUrl": "Neleistinas URL.",
      "noFilterFields": "Sluoksnyje nėra laukų, kurie gali būti naudojami filtravimui.",
      "invalidSQL": "Neleistina SQL sąlyga.",
      "cantParseSQL": "Nepavyksta išanalizuoti SQL sąlygos."
    },
    "caseSensitive": "Didžiosios ir mažosios raidės skirtingos",
    "notSupportCaseSensitiveTip": "Patalpintos paslaugos nepalaiko užklausos, kurioje skiriamos didžiosios ir mažosios raidės.",
    "setFilterTip": "Nustatykite filtrą tinkamai.",
    "listValues": "Sąrašo reikšmės",
    "cascadeFilterTip": "Rodyti tik ankstesnių išraiškų atrinktas reikšmes.",
    "noneCascadeFilterTip": "Visos unikalios šio lauko reikšmės",
    "previousCascadeFilterTip": "Reikšmės išfiltruotos pagal ankstesnes išraiškas",
    "allCascadeFilterTip": "Reikšmės išfiltruotos pagal visas kitas išraiškas"
  },
  "featureLayerSource": {
    "layer": "Sluoksnis",
    "browse": "Parinkti",
    "selectFromMap": "Pasirinkti iš žemėlapio",
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "inputLayerUrl": "Įvesties sluoksnio URL",
    "selectLayer": "Pasirinkite elementų sluoksnį iš dabartinio žemėlapio.",
    "chooseItem": "Pasirinkite elementų sluoksnio elementą.",
    "setServiceUrl": "Įveskite elementų paslaugos arba žemėlapių paslaugos URL.",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "chooseLayer": "Pasirinkite elementų sluoksnį."
  },
  "queryableLayerSource": {
    "layer": "Sluoksnis",
    "browse": "Parinkti",
    "selectFromMap": "Pasirinkti iš žemėlapio",
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "inputLayerUrl": "Įvesties sluoksnio URL",
    "selectLayer": "Pasirinkite sluoksnį iš esamo žemėlapio.",
    "chooseItem": "Pasirinkite elementą.",
    "setServiceUrl": "Įveskite paslaugos URL.",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "chooseLayer": "Pasirinkite sluoksnį."
  },
  "gpSource": {
    "selectFromPortal": "Pridėti iš Portal for ArcGIS",
    "addServiceUrl": "Pridėti paslaugos URL",
    "selectFromOnline": "Pridėti iš ArcGIS Online",
    "setServiceUrl": "Įveskite geoduomenų apdorojimo paslaugos URL.",
    "chooseItem": "Pasirinkite geoduomenų apdorojimo paslaugos elementą.",
    "chooseTask": "Pasirinkite geoduomenų apdorojimo užduotį."
  },
  "itemSelector": {
    "map": "Žemėlapis",
    "selectWebMap": "Pasirinkti žemėlapį",
    "addMapFromOnlineOrPortal": "ArcGIS Online viešuosiuose ištekliuose arba privačiame turinyje, esančiame ArcGIS Online arba Portal, raskite ir pridėkite aplikacijoje interneto žemėlapį.",
    "searchMapName": "Ieškoti pagal žemėlapio pavadinimą...",
    "searchNone": "Nepavyko rasti jūsų ieškomo elemento. Bandykite dar kartą.",
    "groups": "Grupės",
    "noneGroups": "Grupių nėra",
    "signInTip": "Baigėsi prisijungimo laikas, atnaujinkite naršyklės langą, kad vėl prisijungtumėte prie portalo.",
    "signIn": "Prisijunkite",
    "publicMap": "Vieša",
    "myOrganization": "Organizacija",
    "myGroup": "Mano Grupės",
    "myContent": "Turinys",
    "count": "Viso",
    "fromPortal": "iš portalo",
    "fromOnline": "iš ArcGIS.com",
    "noneThumbnail": "Miniatiūros nėra",
    "owner": "savininkas",
    "signInTo": "Prisijungti į",
    "lastModified": "Pakeitimo data",
    "moreDetails": "Išsamiau",
    "mostRecent": "Naujausi",
    "mostViewed": "Dažniausiai žiūrimi",
    "highestRated": "Aukščiausiai įvertinti",
    "viewItemDetails": "Elemento aprašas"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Paslauga nepalaiko užklausos."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Žemėlapyje tinkamų sluoksnių nėra."
  },
  "layerInfosMenu": {
    "titleBasemap": "Pagrindo žemėlapiai",
    "titleLayers": "Darbiniai sluoksniai",
    "labelLayer": "Sluoksnio pavadinimas",
    "itemZoomTo": "Parodyti visą",
    "itemTransparency": "Permatomumas",
    "itemTransparent": "Permatomas",
    "itemOpaque": "Nepermatomas",
    "itemMoveUp": "Pakelti aukštyn",
    "itemMoveDown": "Nuleisti žemyn",
    "itemDesc": "Aprašas",
    "itemDownload": "Atsiųsti",
    "itemToAttributeTable": "Atidaryti atributų lentelę"
  },
  "imageChooser": {
    "unsupportReaderAPI": "UŽDUOTIS: naršyklė nepalaiko failo skaitytuvo API",
    "readError": "Nepavyko nuskaityti failo.",
    "unknowError": "nepavyko įvykdyti operacijų",
    "invalidType": "Neleistinas failo tipas.",
    "cropImage": "Apkarpyti atvaizdą",
    "exceed": "Failo dydis negali viršyti 1024 KB",
    "enableFlash": "Prieš naršydami vaizdą įjunkite Adobe Flash.",
    "cropWaining": "Pasirinkite bent ${width} x ${height} pikselių dydžio nuotrauką.",
    "toolTip": "Geriausiam rezultatui naudokite paveikslėlį, kuris būtų ${width} piks. pločio ${height} piks. ilgio. Kitų išmatavimų paveikslėliai talpinimo metu bus automatiškai pakoreguoti. Tinkami paveikslėlių formatai: PNG, GIF ir JPEG."
  },
  "simpleTable": {
    "moveUp": "Pakelti aukštyn",
    "moveDown": "Nuleisti žemyn",
    "deleteRow": "Ištrinti",
    "edit": "Redaguoti"
  },
  "urlParams": {
    "invalidToken": "Netinkamas prieigos raktas",
    "validateTokenError": "Netinkamas prieigos raktas arba tinklo klaida"
  },
  "exportTo": {
    "exportTo": "Eksportuoti",
    "toCSV": "Eksportuoti į CSV formato failą",
    "toFeatureCollection": "Eksportuoti į elementų rinkinį",
    "toGeoJSON": "Eksportuoti į GeoJSON"
  },
  "appState": {
    "title": "Aplikacijos būsena",
    "restoreMap": "Spustelėkite, kad atkurtumėte naudotą žemėlapio aprėptį ir matomus sluoksnius"
  },
  "featureActions": {
    "featureActions": "Elementų veiksmai",
    "ZoomTo": "Parodyti visą",
    "PanTo": "Pereiti į",
    "Flash": "Blykstė",
    "ShowPopup": "Rodyti iškylantį langą",
    "CreateLayer": "Kurti sluoksnį",
    "ShowStatistics": "Statistika...",
    "ClearSelection": "Valyti atranką",
    "ExportToCSV": "Eksportuoti į CSV formato failą",
    "ShowSelectedFeature": "Rodyti pažymėtus elementus",
    "ExportToFeatureCollection": "Eksportuoti į elementų rinkinį",
    "ExportToGeoJSON": "Eksportuoti į GeoJSON",
    "AddMarker": "Pridėti ženklą",
    "RemoveMarker": "Pašalinti ženklą"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Susijęs sluoksnis",
    "selectedFeatures": "Naudokite pažymėtus elementus",
    "drawShapesTip": "Norėdami pažymėti elementus, brėžkite figūras",
    "pleaseDrawShapesTip": "Norėdami pažymėti elementus, brėžkite figūras",
    "allFeaturesTip": "Visi elementai, esantys sluoksnyje",
    "selectFeaturesOrDrawShapesTip": "Naudokite šiame sluoksnyje pažymėtus elementus arba, brėždami žemėlapyje figūras, apribokite elementus."
  },
  "searchDistance": {
    "applySearchDistance": "Taikyti paieškos nuotolį",
    "applySearchDistanceToFeatures": "Norėdami pažymėti elementus, taikykite paieškos nuotolį"
  },
  "units": {
    "miles": "Mylios",
    "kilometers": "Kilometrai",
    "feet": "Pėdos",
    "meters": "Metrai",
    "yards": "Jardai",
    "nauticalMiles": "Jūrmylės"
  },
  "featureSetChooser": {
    "select": "Pažymėti",
    "dragBox": "Vilkite",
    "dragMouse": "Vilkite pelę",
    "selectByRectangle": "Pažymėti apibrėžiant stačiakampį",
    "selectFeaturesTip": "Pažymėti elementus žemėlapyje apibrėžiant juos stačiakampiu",
    "newSelectionTip": "Kurti naują atranką",
    "addSelectionTip": "Pridėti prie atrankos",
    "removeSelectionTip": "Panaikinti atranką",
    "selectFromCurrentSelectionTip": "Pasirinkti iš esamos atrankos",
    "unselectAllSelectionTip": "Panaikinti visų šiuo metu pažymėtų elementų atranką",
    "selectByPolygon": "Pasirinkti pagal poligoną",
    "selectByCircle": "Pasirinkti pagal apskritimą",
    "selectByLine": "Pasirinkti pagal liniją",
    "chooseSelectingTools": "Nurodykite pasirinkimo įrankius",
    "darw": "Piešti",
    "drawShap": "Piešti figūrą"
  },
  "widgetManager": {
    "createWidgetError": "Klaida kuriant valdiklį",
    "createWidgetSettingPageError": "Klaida kuriant valdiklio nustatymų langą",
    "loadWidgetResourceError": "Klaida užkraunant valdiklio resursus"
  },
  "shareOptions": {
    "shareMap": "Pasirinti, kas galės matyti šį žemėlapį",
    "shareMapTips": "Aplikacija bendrinama su šiais asmenimis",
    "everyone": "Visi",
    "theseGroups": "Šios grupės"
  },
  "shareLink": {
    "email": "el. paštas",
    "shareEmail": "El. paštas",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Įterpti šią aplikaciją į interneto svetainę",
    "shareEmailSubject": "Internetinės aplikacijos bendrinimas:",
    "shareEmailTxt1": "Ši internetinė aplikacija bendrinama su jumis naudojant Web AppBuilder for ArcGIS.",
    "shareEmailTxt2": "Galite kurti ir bendrinti savo internetines aplikacijas naudodami Esri Web AppBuilder for ArcGIS.",
    "shareEmailTxt3": "Daugiau informacijos rasite http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Mažas",
    "mediumSize": "Vidutinė",
    "largeSize": "Didelis",
    "customSize": "Adaptuotas",
    "embed": "Įterpti šią aplikaciją į interneto svetainę",
    "more": "Įterpti parinktis",
    "changeShareSettings": "Keisti bendrinimo parametrus",
    "shareLinkText": "Bendrinti nuorodą į šią aplikaciją",
    "linkOptions": "Nuorodos parinktys",
    "linkOptionsUrlParameters": "Pasirinkite URL parametrus, įtrauktus į nuorodą",
    "currentMapExtent": "Esama žemėlapio aprėptis",
    "chooseCenterWithLevel": "Spustelėkite žemėlapį, jei norite nustatyti žemėlapio centrą naudodami pritraukimo lygį",
    "chooseCenterWithScale": "Spustelėkite žemėlapį, jei norite nustatyti žemėlapio centrą naudodami žemėlapio mastelį",
    "findLocation": "Raskite vietą arba elementą ir priartinkite iki jo",
    "findLocation_inputPlaceholder": "Jūsų vieta arba elementas",
    "queryFeature": "Pateikite užklausą apie elementą ir priartinkite iki jo",
    "addMarker": "Pridėkite žymeklį žemėlapyje",
    "addMarker_titlePlaceholder": "Žymeklio iškylančiojo lango pavadinimas",
    "addMarker_symbolURL": "Žymeklio simbolio URL",
    "addMarker_label": "Žymeklio žymė",
    "popupTitle": "Iškylančio lango pavadinimas",
    "zoomLevel": "Didinimo lygis",
    "overwirteMobileLayout": "Perrašykite mobiliojo maketo numatytąjį ekrano dydį",
    "language": "Nustatykite aplikacijos kalbą",
    "auth": "Autentikuokite vartotoją automatiškai",
    "linkPreview": "Nuorodos peržiūra",
    "useShortenLink": "Trumpoji nuoroda",
    "shareMapUrlExtent": "Bendrinti esamo žemėlapio aprėptį",
    "shareToWebTips": "Ši aplikacija nėra bendrinama viešai. Vartotojams ji gali būti nepasiekiama."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D interenetinės aplikacijos jūsų naršyklėje nepalaikomos."
  },
  "map": {
    "basemapNotAvailable": "Pagrindo žemėlapis nepasiekiamas.",
    "displayDefaultBasemap": "Vietoje to rodyti numatytąjį pagrindo žemėlapį."
  },
  "popup": {
    "relatedTables": "Susijusios lentelės:",
    "relatedRecords": "Susiję įrašai:",
    "noRelatedRecotds": "Susijusių įrašų nerasta"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Jūsų pasirinkime per daug elementų. Gali užtrukti, kol bus jie bus nuskaityti ir parodyti žemėlapyje.",
    "askForContinue": "Ar norite tęsti?"
  },
  "colorPalette": {
    "transparent": "Permatomas",
    "custom": "Adaptuotas"
  },
  "noEditPrivileges": "Jūsų paskyra neturi teisės kurti arba modifikuoti duomenų.",
  "invalidConfiguration": "Valdiklis nesukonfigūruotas arba konfigūracijos sluoksnių žemėlapyje nebėra. Atidarykite aplikaciją kūrimo režime ir iš naujo sukonfigūruokite valdiklį."
});