define({
  "defaultAreaUnit": "Pindala vaikeühik",
  "defaultLengthUnit": "Pikkuse vaikeühik",
  "acres": "Aakrit",
  "sqMiles": "Ruutmiilides",
  "sqKilometers": "Ruutkilomeetrites",
  "hectares": "Hektarit",
  "sqYards": "Ruutjardides",
  "sqFeet": "Ruutjalgades",
  "sqFeetUS": "Ruutjalgades (USA)",
  "sqMeters": "Ruutmeetrites",
  "miles": "Miili",
  "kilometers": "Kilomeetrit",
  "feet": "Jalga",
  "feetUS": "Jalga (USA)",
  "meters": "Meetrit",
  "yards": "Jardi",
  "nauticalMiles": "Meremiili",
  "showArea": "Pindala",
  "showDistance": "Vahemaa",
  "showLocation": "Asukoht",
  "showtools": "Kuva mõõtmise tööriistad:",
  "allHidedTips": "Valida tuleb vähemalt üks tööriist."
});