define({
  "sourceSetting": "Pengaturan Sumber Pencarian",
  "instruction": "Tambah dan konfigurasikan geocode service atau feature layer fitur sebagai sumber pencarian. Sumber yang ditentukan ini menentukan apa yang dapat dicari dalam kotak pencarian.",
  "add": "Tambah Sumber Pencarian",
  "addGeocoder": "Tambah Geocoder",
  "geocoder": "Geocoder",
  "setLayerSource": "Atur Sumber Layer",
  "setGeocoderURL": "Atur URL Geocoder",
  "searchableLayer": "Feature Layer",
  "name": "Nama",
  "countryCode": "Kode Negara atau Wilayah",
  "countryCodeEg": "mis. ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "generalSetting": "Pengaturan Umum",
  "allPlaceholder": "Teks placehoder untuk mencari semua: ",
  "showInfoWindowOnSelect": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
  "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
  "zoomScale": "Skala Zoom",
  "locatorUrl": "URL Geocoder",
  "locatorName": "Nama Geocoder",
  "locatorExample": "Contoh",
  "locatorWarning": "Versi geocode service tidak didukung. Widget mendukung geocode service versi 10.0 dan lebih tinggi.",
  "locatorTips": "Saran tidak tersedia karena geocode service tidak mendukung kemampuan saran.",
  "layerSource": "Sumber Layer",
  "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
  "placeholder": "Teks Placeholder",
  "searchFields": "Kolom Pencarian",
  "displayField": "Tampilkan Kolom",
  "exactMatch": "Persis",
  "maxSuggestions": "Saran Maksimum",
  "maxResults": "Hasil Maksimum",
  "enableLocalSearch": "Aktifkan pencarian lokal",
  "minScale": "Skala Min",
  "minScaleHint": "Apabila skala peta lebih besar daripada skala ini, pencarian lokal akan diterapkan",
  "radius": "Radius",
  "radiusHint": "Menentukan radius dari area di sekitar pusat peta saat ini yang digunakan untuk mendorong peringkat calon geocoding sehingga calon terdekat dengan lokasi dimunculkan terlebih dahulu",
  "meters": "Meter",
  "setSearchFields": "Atur Kolom Pencarian",
  "set": "Atur",
  "fieldSearchable": "dapat dicari",
  "fieldName": "Nama",
  "fieldAlias": "Alias",
  "ok": "YA",
  "cancel": "Batal",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses."
});