define({
  "defaultAreaUnit": "Noklusējuma laukuma mērvienība",
  "defaultLengthUnit": "Noklusējuma garuma mērvienība",
  "acres": "Akri",
  "sqMiles": "Kvadrātjūdzes",
  "sqKilometers": "Kvadrātkilometri",
  "hectares": "Hektāri",
  "sqYards": "Kvadrātjardi",
  "sqFeet": "Kvadrātpēdas",
  "sqFeetUS": "Kvdrātpēdas (ASV)",
  "sqMeters": "Kvadrātmetri",
  "miles": "Jūdzes",
  "kilometers": "Kilometri",
  "feet": "Pēdas",
  "feetUS": "Pēdas (ASV)",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Jūras jūdzes",
  "showArea": "Laukums",
  "showDistance": "Distance",
  "showLocation": "Izvietojums",
  "showtools": "Rādīt mērīšanas rīkus:",
  "allHidedTips": "Ir jāatlasa vismaz viens rīks."
});