define({
  "defaultAreaUnit": "Zadana jedinica površine",
  "defaultLengthUnit": "Zadana jedinica duljine",
  "acres": "Jutra",
  "sqMiles": "Kvadratne milje",
  "sqKilometers": "Kvadratni kilometri",
  "hectares": "Hektari",
  "sqYards": "Kvadratni jardi",
  "sqFeet": "Kvadratne stope",
  "sqFeetUS": "Kvadratne stope (SAD)",
  "sqMeters": "Kvadratni metri",
  "miles": "Milje",
  "kilometers": "Kilometri",
  "feet": "Stope",
  "feetUS": "Stope (SAD)",
  "meters": "Metri",
  "yards": "Jardi",
  "nauticalMiles": "Nautičke milje",
  "showArea": "Površina",
  "showDistance": "Udaljenost",
  "showLocation": "Lokacija",
  "showtools": "Prikaži alate za mjerenje:",
  "allHidedTips": "Treba odabrati barem jedan alat."
});