define(
   ({
    showArcgisBasemaps: "包括 Portal 的底圖",
    settings: "設置",
    add: "按一下以新增新底圖",
    edit: "設定",
    title: "標題",
    titlePH: "底圖標題",
    thumbnail: "縮圖",
    thumbnailHint: "按一下圖片進行更新",
    url: "URL",
    urlPH: "圖層 URL",
    addlayer: "新增底圖",
    actions: "操作",
    warning: "輸入不正確",
    save: "返回並儲存",
    back: "返回並取消",
    addUrl: "新增 URL",
    autoCheck: "自動檢查",
    checking: "正在檢查...",
    ok: "確定",
    cancel: "取消",
    result: "已成功儲存",
    spError: "新增到圖庫的所有底圖必須具有相同的空間參考。",
    invalidTitle1:"底圖 '",
    invalidTitle2:"' 已存在。請選擇其它標題。",
    invalidBasemapUrl1: "此類型的圖層不能做為底圖。",
    invalidBasemapUrl2: "您正在新增的底圖與目前地圖擁有不同的空間參考。",
    addBaselayer: "新增底圖圖層"
  })
);