define({
  "sourceSetting": "Kaynak Ayarlarını Ara",
  "instruction": "Coğrafi kodlama hizmetlerini veya detay katmanlarını arama kaynağı olarak ekleyin ve yapılandırın. Belirtilen bu kaynaklar arama kutusunda neyin aranabileceğini belirler.",
  "add": "Arama Kaynağı Ekle",
  "addGeocoder": "Coğrafi Kodlayıcı Ekle",
  "geocoder": "Coğrafi Kodlayıcı",
  "setLayerSource": "Kaynak Katmanı Ayarla",
  "setGeocoderURL": "Coğrafi Kodlayıcı URL'si Düzenle",
  "searchableLayer": "Detay Katmanı",
  "name": "Ad",
  "countryCode": "Ülke veya Bölge Kodları",
  "countryCodeEg": "örneğin ",
  "countryCodeHint": "Bu değer boş bırakılırsa tüm ülkeler ve bölgeler aranır",
  "generalSetting": "Genel Ayarlar",
  "allPlaceholder": "Tümünü aramak için yer tutucu metin: ",
  "showInfoWindowOnSelect": "Bulunan detay veya konum için açılır pencere göster",
  "searchInCurrentMapExtent": "Yalnızca geçerli harita yayılımını ara",
  "zoomScale": "Yakınlaştırma Ölçeği",
  "locatorUrl": "Coğrafi Kodlayıcı URL'si",
  "locatorName": "Coğrafi Kodlayıcı Adı",
  "locatorExample": "Örnek",
  "locatorWarning": "Coğrafi kodlama servisinin bu sürümü desteklenmiyor. Araç, 10.0 veya üstü sürümdeki coğrafi kodlama servisini destekliyor.",
  "locatorTips": "Coğrafi kodlama hizmeti öneri özelliğini desteklemediğinden öneriler kullanılamıyor.",
  "layerSource": "Katman Kaynağı",
  "searchLayerTips": "Detay hizmeti sayfalama özelliğini desteklemediğinden öneriler kullanılamıyor.",
  "placeholder": "Yer Tutucu Metni",
  "searchFields": "Arama Alanları",
  "displayField": "Alan Görüntüle",
  "exactMatch": "Tam Eşleşme",
  "maxSuggestions": "Maksimum Öneri Sayısı",
  "maxResults": "Maksimum Sonuç Sayısı",
  "enableLocalSearch": "Yerel aramayı etkinleştir",
  "minScale": "Min Ölçek",
  "minScaleHint": "Harita ölçeği bu ölçekten daha büyük olduğunda yerel arama uygulanır",
  "radius": "Yarıçap",
  "radiusHint": "Coğrafi kodlama adaylarının sıralamasını yükseltmek için kullanılan geçerli harita merkezi etrafındaki bir alanın yarı çapını belirtir, böylelikle konuma en yakın olan adaylar öncelikli olarak döndürülür",
  "meters": "Metre",
  "setSearchFields": "Arama Alanlarını Ayarla",
  "set": "Ayarla",
  "fieldSearchable": "aranabilir",
  "fieldName": "Ad",
  "fieldAlias": "Takma Ad",
  "ok": "Tamam",
  "cancel": "İptal",
  "invalidUrlTip": "${URL} URL'si geçersiz veya erişilemez durumda."
});