define({
  "defaultAreaUnit": "Unité de surface par défaut",
  "defaultLengthUnit": "Unité de longueur par défaut",
  "acres": "Acres",
  "sqMiles": "Milles carrés",
  "sqKilometers": "Kilomètres carrés",
  "hectares": "Hectares",
  "sqYards": "Yards carrés",
  "sqFeet": "Pieds carrés",
  "sqFeetUS": "Pieds carrés (US)",
  "sqMeters": "Mètres carrés",
  "miles": "Miles",
  "kilometers": "Kilomètres",
  "feet": "Pieds",
  "feetUS": "Pieds (US)",
  "meters": "Mètres",
  "yards": "Yards",
  "nauticalMiles": "Milles marins",
  "showArea": "Surface",
  "showDistance": "Distance",
  "showLocation": "Emplacement",
  "showtools": "Afficher les outils de mesure :",
  "allHidedTips": "Au moins un outil doit être sélectionné."
});