define({
  "common": {
    "apply": "Übernehmen",
    "ok": "OK",
    "cancel": "Abbrechen",
    "yes": "Ja",
    "no": "Nein",
    "next": "Weiter",
    "previous": "Zurück",
    "back": "Zurück",
    "selected": "ausgewählte",
    "name": "Name",
    "usage": "Verwendung",
    "settings": "Einstellungen",
    "home": "Startseite",
    "link": "Link",
    "messages": "Meldungen",
    "outputs": "Ausgaben",
    "title": "Titel",
    "thumbnail": "Miniaturansicht",
    "url": "URL",
    "actions": "Aktionen",
    "layer": "Layer",
    "action": "Aktion",
    "input": "Eingabe",
    "output": "Ausgabe",
    "type": "Typ",
    "required": "Erforderlich",
    "options": "Optionen",
    "label": "Beschriftung",
    "tooltip": "Quickinfo",
    "visible": "Sichtbar",
    "symbol": "Symbol",
    "popup": "Pop-up",
    "upload": "Hochladen",
    "execute": "Ausführen",
    "help": "Hilfe",
    "executing": "Wird ausgeführt",
    "clear": "Löschen",
    "error": "Fehler",
    "zoomTo": "Zoomen auf",
    "attribute": "Attribut",
    "exports": "Exportieren",
    "check": "Überprüfen",
    "save": "Speichern",
    "close": "Schließen",
    "deleteText": "Löschen",
    "map": "Karte",
    "scene": "Szene",
    "reset": "Zurücksetzen",
    "icon": "Symbol",
    "share": "Freigeben",
    "view": "Anzeigen",
    "newText": "Neu",
    "edit": "Bearbeiten",
    "wkid": "WKID",
    "table": "Tabelle",
    "zoomIn": "Vergrößern",
    "zoomOut": "Verkleinern",
    "continue1": "Fortfahren",
    "longitude": "Längengrad",
    "latitude": "Breitengrad"
  },
  "errorCode": "Code",
  "errorMessage": "Meldung",
  "errorDetail": "Detail",
  "widgetPlaceholderTooltip": "Zum Einrichten zu Widgets wechseln und auf den entsprechenden Platzhalter klicken",
  "fieldStatistics": {
    "selectField": "Feld auswählen",
    "statistics": "Statistiken",
    "field": "Feld",
    "count": "Anzahl der Werte",
    "sum": "Summe der Werte",
    "min": "Minimum",
    "max": "Maximum",
    "ave": "Durchschnitt",
    "stddev": "Standardabweichung"
  },
  "symbolChooser": {
    "preview": "Vorschau",
    "basic": "Standard",
    "arrows": "Pfeile",
    "business": "Gewerbe",
    "cartographic": "Kartografisch",
    "nationalParkService": "National Park Service",
    "outdoorRecreation": "Erholung im Freien",
    "peoplePlaces": "Öffentliche Plätze",
    "safetyHealth": "Sicherheit und Gesundheit",
    "shapes": "Shapes",
    "transportation": "Verkehr",
    "symbolSize": "Symbolgröße",
    "color": "Farbe",
    "alpha": "Alpha",
    "outlineColor": "Umrissfarbe",
    "outlineWidth": "Umrissbreite",
    "style": "Style",
    "width": "Breite",
    "text": "Text",
    "fontColor": "Schriftfarbe",
    "fontSize": "Schriftgröße",
    "transparency": "Transparenz",
    "solid": "Durchgezogen",
    "dash": "Gestrichelt",
    "dot": "Punkt",
    "dashDot": "Strich-Punkt",
    "dashDotDot": "Strich-Punkt-Punkt",
    "customImage": "Benutzerdefiniertes Bild",
    "chooseFile": "Datei auswählen",
    "noFileChoosen": "Keine Datei ausgewählt."
  },
  "transparency": {
    "opaque": "Nicht transparent",
    "transparent": "Transparent"
  },
  "rendererChooser": {
    "domain": "Domäne",
    "use": "Verwenden",
    "singleSymbol": "Ein Symbol",
    "uniqueSymbol": "Einzelsymbole",
    "color": "Farbe",
    "size": "Größe",
    "toShow": "Anzeigen",
    "colors": "Farben",
    "classes": "Klassen",
    "symbolSize": "Symbolgröße",
    "addValue": "Wert hinzufügen",
    "setDefaultSymbol": "Standardsymbol festlegen",
    "defaultSymbol": "Standardsymbol",
    "selectedSymbol": "Ausgewähltes Symbol",
    "value": "Wert",
    "label": "Beschriftung",
    "range": "Bereich"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Linie",
    "polyline": "Polylinie",
    "freehandPolyline": "Freihand-Polylinie",
    "triangle": "Dreieck",
    "extent": "Ausdehnung",
    "circle": "Kreis",
    "ellipse": "Ellipse",
    "polygon": "Polygon",
    "freehandPolygon": "Freihand-Polygon",
    "text": "Text",
    "clear": "Auswahl aufheben"
  },
  "popupConfig": {
    "title": "Titel",
    "add": "Hinzufügen",
    "fields": "Felder",
    "noField": "Kein Feld",
    "visibility": "Sichtbar",
    "name": "Name",
    "alias": "Alias",
    "actions": "Aktionen"
  },
  "includeButton": {
    "include": "Einbinden"
  },
  "loadingShelter": {
    "loading": "Wird geladen"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Keinen Service gefunden.",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden",
    "invalidUrlTip": "Die eingegebene URL ist ungültig oder es kann nicht darauf zugegriffen werden."
  },
  "serviceBrowser": {
    "noGpFound": "Keinen Geoverarbeitungsservice gefunden.",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Keinen Kartenservice oder Feature-Service gefunden",
    "unableConnectTo": "Verbindung kann nicht hergestellt werden"
  },
  "basicServiceChooser": {
    "validate": "Überprüfen",
    "example": "Beispiel",
    "set": "Festlegen"
  },
  "urlInput": {
    "invalidUrl": "Ungültige URL."
  },
  "urlComboBox": {
    "invalidUrl": "Ungültige URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Filterausdruck hinzufügen",
    "addSet": "Eine Gruppe von Ausdrücken hinzufügen",
    "matchMsg": "Features im Layer abrufen, bei denen ${any_or_all} der folgenden Ausdrücke zutreffen",
    "matchMsgSet": "${any_or_all} der folgenden Ausdrücke dieser Abfrage erfüllen die Bedingung",
    "all": "Alle",
    "any": "Einige",
    "value": "Wert",
    "field": "Feld",
    "unique": "Eindeutig",
    "none": "Keine",
    "and": "und",
    "valueTooltip": "Wert eingeben",
    "fieldTooltip": "Aus vorhandenem Feld auswählen",
    "uniqueValueTooltip": "Aus eindeutigen Werten im ausgewählten Feld auswählen",
    "stringOperatorIs": "ist",
    "stringOperatorIsNot": "ist nicht",
    "stringOperatorStartsWith": "beginnt mit",
    "stringOperatorEndsWith": "endet mit",
    "stringOperatorContains": "enthält",
    "stringOperatorDoesNotContain": "enthält nicht",
    "stringOperatorIsBlank": "ist leer",
    "stringOperatorIsNotBlank": "ist nicht leer",
    "dateOperatorIsOn": "ist am",
    "dateOperatorIsNotOn": "ist nicht am",
    "dateOperatorIsBefore": "ist vor",
    "dateOperatorIsAfter": "ist nach",
    "dateOperatorDays": "Tagen",
    "dateOperatorWeeks": "Wochen",
    "dateOperatorMonths": "Monate",
    "dateOperatorInTheLast": "in den letzten",
    "dateOperatorNotInTheLast": "nicht in den letzten",
    "dateOperatorIsBetween": "liegt zwischen",
    "dateOperatorIsNotBetween": "liegt nicht zwischen",
    "dateOperatorIsBlank": "ist leer",
    "dateOperatorIsNotBlank": "ist nicht leer",
    "numberOperatorIs": "ist",
    "numberOperatorIsNot": "ist nicht",
    "numberOperatorIsAtLeast": "ist mindestens",
    "numberOperatorIsLessThan": "ist kleiner als",
    "numberOperatorIsAtMost": "ist höchstens",
    "numberOperatorIsGreaterThan": "ist größer als",
    "numberOperatorIsBetween": "liegt zwischen",
    "numberOperatorIsNotBetween": "liegt nicht zwischen",
    "numberOperatorIsBlank": "ist leer",
    "numberOperatorIsNotBlank": "ist nicht leer",
    "string": "String",
    "number": "Zahl",
    "date": "Datum",
    "askForValues": "Werte abfragen",
    "prompt": "Eingabeaufforderung",
    "hint": "Hinweis",
    "error": {
      "invalidParams": "Ungültige Parameter.",
      "invalidUrl": "Ungültige URL.",
      "noFilterFields": "Der Layer verfügt über keine Felder, die gefiltert werden können.",
      "invalidSQL": "Ungültiger SQL-Ausdruck.",
      "cantParseSQL": "SQL-Ausdruck kann nicht geparst werden."
    },
    "caseSensitive": "Groß-/Kleinschreibung beachten",
    "notSupportCaseSensitiveTip": "Gehostete Services unterstützen keine Abfragen, bei denen zwischen Groß- und Kleinschreibung unterschieden wird.",
    "setFilterTip": "Legen Sie den Filter ordnungsgemäß fest.",
    "listValues": "Listenwerte",
    "cascadeFilterTip": "Nur Werte anzeigen, die nach vorherigen Ausdrücken gefiltert wurden",
    "noneCascadeFilterTip": "Alle eindeutigen Werte dieses Feldes",
    "previousCascadeFilterTip": "Nach vorherigen Ausdrücken gefilterte Werte",
    "allCascadeFilterTip": "Nach allen anderen Ausdrücken gefilterte Werte"
  },
  "featureLayerSource": {
    "layer": "Layer",
    "browse": "Durchsuchen",
    "selectFromMap": "Aus Karte auswählen",
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "inputLayerUrl": "Eingabe-Layer-URL",
    "selectLayer": "Feature-Layer aus aktueller Karte auswählen.",
    "chooseItem": "Ein Feature-Layer-Element auswählen.",
    "setServiceUrl": "Geben Sie die URL des Feature-Service oder des Kartenservice ein.",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "chooseLayer": "Wählen Sie einen Feature-Layer aus."
  },
  "queryableLayerSource": {
    "layer": "Layer",
    "browse": "Durchsuchen",
    "selectFromMap": "Aus Karte auswählen",
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "inputLayerUrl": "Eingabe-Layer-URL",
    "selectLayer": "Wählen Sie einen Layer aus der aktuellen Karte aus.",
    "chooseItem": "Wählen Sie ein Element aus.",
    "setServiceUrl": "Geben Sie die URL des Service ein.",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "chooseLayer": "Wählen Sie einen Layer aus."
  },
  "gpSource": {
    "selectFromPortal": "Aus Portal for ArcGIS hinzufügen",
    "addServiceUrl": "Service-URL hinzufügen",
    "selectFromOnline": "Aus ArcGIS Online hinzufügen",
    "setServiceUrl": "Geben Sie die URL des Geoverarbeitungsservice an.",
    "chooseItem": "Wählen Sie ein Geoverarbeitungsserviceelement aus.",
    "chooseTask": "Wählen Sie einen Geoverarbeitungs-Task aus."
  },
  "itemSelector": {
    "map": "Karte",
    "selectWebMap": "Webkarte auswählen",
    "addMapFromOnlineOrPortal": "Suchen Sie in der Anwendung eine Webkarte in den öffentlichen ArcGIS Online-Ressourcen oder Ihren privaten Inhalten in ArcGIS Online oder Portal und fügen Sie sie hinzu.",
    "searchMapName": "Nach Kartenname suchen...",
    "searchNone": "Die gesuchten Informationen konnten nicht gefunden werden. Versuchen Sie es erneut.",
    "groups": "Gruppen",
    "noneGroups": "Keine Gruppen",
    "signInTip": "Ihre Anmeldesitzung ist abgelaufen. Aktualisieren Sie Ihren Browser, um sich erneut bei Ihrem Portal anzumelden.",
    "signIn": "Anmelden",
    "publicMap": "Öffentlich",
    "myOrganization": "Eigene Organisation",
    "myGroup": "Eigene Gruppen",
    "myContent": "Eigene Inhalte",
    "count": "Anzahl",
    "fromPortal": "aus Portal",
    "fromOnline": "aus ArcGIS.com",
    "noneThumbnail": "Miniaturansicht nicht verfügbar",
    "owner": "Besitzer",
    "signInTo": "Melden Sie sich an bei",
    "lastModified": "Zuletzt geändert",
    "moreDetails": "Mehr Details",
    "mostRecent": "Neueste",
    "mostViewed": "Die meisten Aufrufe",
    "highestRated": "Höchste Bewertung",
    "viewItemDetails": "Elementdetails anzeigen"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Der Service unterstützt keine Abfragen."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "In der Karte ist kein geeigneter Layer verfügbar."
  },
  "layerInfosMenu": {
    "titleBasemap": "Grundkarten",
    "titleLayers": "Operationale Layer",
    "labelLayer": "Layer-Name",
    "itemZoomTo": "Zoomen auf",
    "itemTransparency": "Transparenz",
    "itemTransparent": "Transparent",
    "itemOpaque": "Nicht transparent",
    "itemMoveUp": "Nach oben verschieben",
    "itemMoveDown": "Nach unten verschieben",
    "itemDesc": "Beschreibung",
    "itemDownload": "Herunterladen",
    "itemToAttributeTable": "Attributtabelle öffnen"
  },
  "imageChooser": {
    "unsupportReaderAPI": "Der Browser unterstützt die Datei-Reader-API nicht.",
    "readError": "Die Datei kann nicht gelesen werden.",
    "unknowError": "Vorgänge können nicht abgeschlossen werden.",
    "invalidType": "Ungültiger Dateityp.",
    "cropImage": "Bild zuschneiden",
    "exceed": "Dateigröße darf 1024 KB nicht überschreiten",
    "enableFlash": "Aktivieren Sie Adobe Flash, bevor Sie nach einem Bild suchen.",
    "cropWaining": "Wählen Sie ein Foto mit einem Format von mindestens ${width} x ${height} Pixel aus.",
    "toolTip": "Optimale Ergebnisse erzielen Sie mit einer Bildgröße von ${width} x ${height} Pixel (Breite x Höhe). Andere Größen werden angepasst. Zulässige Bildformate sind: PNG, GIF und JPEG."
  },
  "simpleTable": {
    "moveUp": "Nach oben verschieben",
    "moveDown": "Nach unten verschieben",
    "deleteRow": "Löschen",
    "edit": "Bearbeiten"
  },
  "urlParams": {
    "invalidToken": "Ungültiges Token",
    "validateTokenError": "Ungültiges Token oder Netzwerkfehler"
  },
  "exportTo": {
    "exportTo": "Exportieren",
    "toCSV": "In CSV-Datei exportieren",
    "toFeatureCollection": "In Feature-Sammlung exportieren",
    "toGeoJSON": "In GeoJSON exportieren"
  },
  "appState": {
    "title": "App-Status",
    "restoreMap": "Klicken Sie, um den zuvor erreichten Status der Kartenausdehnung und der Layer-Sichtbarkeit wiederherzustellen."
  },
  "featureActions": {
    "featureActions": "Feature-Aktionen",
    "ZoomTo": "Zoomen auf",
    "PanTo": "Schwenken auf",
    "Flash": "Aufblinken lassen",
    "ShowPopup": "Popup-Text anzeigen",
    "CreateLayer": "Layer erstellen",
    "ShowStatistics": "Statistiken...",
    "ClearSelection": "Feature-Auswahl aufheben",
    "ExportToCSV": "In CSV-Datei exportieren",
    "ShowSelectedFeature": "Ausgewählte Features anzeigen",
    "ExportToFeatureCollection": "In Feature-Sammlung exportieren",
    "ExportToGeoJSON": "In GeoJSON exportieren",
    "AddMarker": "Marker hinzufügen",
    "RemoveMarker": "Marker entfernen"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Zugehöriger Layer",
    "selectedFeatures": "Ausgewählte Features verwenden",
    "drawShapesTip": "Shapes zum Auswählen von Features zeichnen",
    "pleaseDrawShapesTip": "Zeichnen Sie Shapes, um Features auszuwählen.",
    "allFeaturesTip": "Alle Features des Layers",
    "selectFeaturesOrDrawShapesTip": "Verwenden Sie ausgewählte Features in diesem Layer, oder stellen Sie Shapes auf der Karte dar, um die Anzahl der Features zu begrenzen."
  },
  "searchDistance": {
    "applySearchDistance": "Eine Suchentfernung anwenden",
    "applySearchDistanceToFeatures": "Eine Suchentfernung auf ausgewählte Features anwenden"
  },
  "units": {
    "miles": "Meilen",
    "kilometers": "Kilometer",
    "feet": "Fuß",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Seemeilen"
  },
  "featureSetChooser": {
    "select": "Auswählen",
    "dragBox": "Ziehen",
    "dragMouse": "Die Maus ziehen",
    "selectByRectangle": "Mit Rechteck auswählen",
    "selectFeaturesTip": "Features durch Aufziehen eines Feldes auf der Karte auswählen",
    "newSelectionTip": "Neue Auswahl erstellen",
    "addSelectionTip": "Zur Auswahl hinzufügen",
    "removeSelectionTip": "Aus Auswahl entfernen",
    "selectFromCurrentSelectionTip": "Aus der aktuellen Auswahl selektieren",
    "unselectAllSelectionTip": "Auswahl aller aktuell ausgewählten Features aufheben",
    "selectByPolygon": "Mit Polygon auswählen",
    "selectByCircle": "Mit Kreis auswählen",
    "selectByLine": "Mit Linie auswählen",
    "chooseSelectingTools": "Auswahlwerkzeuge auswählen",
    "darw": "Darstellen",
    "drawShap": "Ein Shape zeichnen"
  },
  "widgetManager": {
    "createWidgetError": "Fehler beim Erstellen des Widgets",
    "createWidgetSettingPageError": "Fehler beim Erstellen der Seite für Widget-Einstellungen",
    "loadWidgetResourceError": "Fehler beim Laden der Widget-Ressource"
  },
  "shareOptions": {
    "shareMap": "Festlegen, wer diese App anzeigen kann",
    "shareMapTips": "Ihre App ist derzeit für diese Personen freigegeben",
    "everyone": "Alle",
    "theseGroups": "Diese Gruppen"
  },
  "shareLink": {
    "email": "E-Mail",
    "shareEmail": "E-Mail",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Diese App in eine Website einbetten",
    "shareEmailSubject": "Freigeben der Web-App:",
    "shareEmailTxt1": "Im Folgenden finden Sie eine Web-App, die mit Web AppBuilder for ArcGIS für Sie freigegeben wurde.",
    "shareEmailTxt2": "Sie können Ihre eigene Web-App mit Esri Web AppBuilder for ArcGIS erstellen und freigeben.",
    "shareEmailTxt3": "Weitere Informationen finden Sie unter \"http://www.esri.com/software/web-appbuilder\".",
    "smallSize": "Klein",
    "mediumSize": "Mittel",
    "largeSize": "Groß",
    "customSize": "Benutzerdefiniert",
    "embed": "Diese App in eine Website einbetten",
    "more": "Einbettungsoptionen",
    "changeShareSettings": "Freigabeeinstellungen ändern'",
    "shareLinkText": "Link zu dieser App freigeben",
    "linkOptions": "Link-Optionen",
    "linkOptionsUrlParameters": "Im Link enthaltene URL-Parameter auswählen",
    "currentMapExtent": "Aktuelle Kartenausdehnung",
    "chooseCenterWithLevel": "Auf die Karte klicken, um den Mittelpunkt der Karte mit Zoomstufe festzulegen",
    "chooseCenterWithScale": "Auf die Karte klicken, um den Mittelpunkt der Karte mit Kartenmaßstab festzulegen",
    "findLocation": "Die Position oder das Feature suchen und darauf zoomen",
    "findLocation_inputPlaceholder": "Ihr Ort oder Feature",
    "queryFeature": "Ein Feature abfragen und darauf zoomen",
    "addMarker": "Eine Markierung auf der Karte hinzufügen",
    "addMarker_titlePlaceholder": "Titel des Pop-ups für die Markierung",
    "addMarker_symbolURL": "URL des Markersymbols",
    "addMarker_label": "Markerbeschriftung",
    "popupTitle": "Pop-up-Titel",
    "zoomLevel": "Zoomfaktor",
    "overwirteMobileLayout": "Standardbildschirmgröße des mobilen Layouts überschreiben",
    "language": "Anzeigesprache der App festlegen",
    "auth": "Benutzer automatisch authentifizieren",
    "linkPreview": "Link-Vorschau",
    "useShortenLink": "Kurzer Link",
    "shareMapUrlExtent": "Aktuelle Kartenausdehnung freigeben",
    "shareToWebTips": "Diese App ist nicht für die Öffentlichkeit freigegeben. Sie wird Benutzern möglicherweise nicht angezeigt."
  },
  "webSceneLoader": {
    "webglSupportTip": "3D-Web-Apps werden in Ihrem Browser nicht unterstützt."
  },
  "map": {
    "basemapNotAvailable": "Grundkarte ist nicht verfügbar",
    "displayDefaultBasemap": "Stattdessen wird die Standardgrundkarte angezeigt"
  },
  "popup": {
    "relatedTables": "Zugehörige Tabellen:",
    "relatedRecords": "Zugehörige Datensätze:",
    "noRelatedRecotds": "Keine zugehörigen Datensätze gefunden"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Die Auswahl enthält zu viele Features. Das Abrufen aller Features und deren Anzeige auf der Karte kann einige Zeit in Anspruch nehmen.",
    "askForContinue": "Möchten Sie fortfahren?"
  },
  "colorPalette": {
    "transparent": "Transparent",
    "custom": "Benutzerdefiniert"
  },
  "noEditPrivileges": "Ihrem Konto sind keine Berechtigungen zum Erstellen oder Ändern von Daten zugewiesen.",
  "invalidConfiguration": "Das Widget wurde nicht konfiguriert oder die Layer in der Konfiguration sind nicht mehr in der Karte enthalten. Öffnen Sie die App im Builder-Modus, und konfigurieren Sie das Widget neu."
});