define({
  "defaultAreaUnit": "Standardenhed for område",
  "defaultLengthUnit": "Standardenhed for længde",
  "acres": "Acres",
  "sqMiles": "Kvadratmiles",
  "sqKilometers": "Kvadratkilometer",
  "hectares": "Hektar",
  "sqYards": "Kvadrat-yards",
  "sqFeet": "Kvadratfod",
  "sqFeetUS": "Kvadratfod (USA)",
  "sqMeters": "Kvadratmeter",
  "miles": "Miles",
  "kilometers": "Kilometer",
  "feet": "Fod",
  "feetUS": "Fod (USA)",
  "meters": "Meter",
  "yards": "Yards",
  "nauticalMiles": "Sømil",
  "showArea": "Område",
  "showDistance": "Afstand",
  "showLocation": "Position",
  "showtools": "Vis måleværktøjer:",
  "allHidedTips": "Mindst ét værktøj skal være valgt."
});