define({
  "defaultAreaUnit": "وحدة المنطقة الافتراضية",
  "defaultLengthUnit": "وحدة الطول الافتراضية",
  "acres": "فدان",
  "sqMiles": "أميال مربعة",
  "sqKilometers": "كيلومترات مربعة",
  "hectares": "هكتار",
  "sqYards": "ياردات مربعة",
  "sqFeet": "أقدم مربعة",
  "sqFeetUS": "قدم مربع (الولايات المتحدة)",
  "sqMeters": "أمتار مربعة",
  "miles": "أميال",
  "kilometers": "كيلومترات",
  "feet": "قدم",
  "feetUS": "قدم (الولايات المتحدة)",
  "meters": "مترات",
  "yards": "ياردات",
  "nauticalMiles": "أميال بحرية",
  "showArea": "المنطقة",
  "showDistance": "مسافة",
  "showLocation": "الموقع",
  "showtools": "عرض أدوات القياس:",
  "allHidedTips": "يجب تحديد أداة واحدة على الأقل."
});