define({
  "id": "ID",
  "state": "Podrazumevano, koordinate će se pokazati u koordinatnom sistemu trenutne mape. Da biste dobili koordinate u drugom koordinatnom sistemu, morate da ga dodate i navedete odgovarajuće transformacije.",
  "outputUnit": "Jedinica izlaznih rezultata",
  "wkid": "Izlazni WKID",
  "label": "Ime izlaznog koordinatnog sistema",
  "transformationWkid": "WKID transformacije",
  "transformationLabel": "Oznaka transformacije",
  "transformForward": "Prosleđivanje transformacije",
  "actions": "Radnje",
  "warning": "Unesite važeći WKID prostorne reference.",
  "tfWarning": "Unesite važeći WKID datumske transformacije podatka.",
  "spinnerLabel": "Zaokruživanje koordinata na: ",
  "decimalPlace": "decimale",
  "separator": "Prikaži separator hiljada",
  "getVersionError": "Ne mogu da dobijem verziju Geometry Service servisa",
  "add": "Dodaj koordinatni sistem izlaznih rezultata",
  "edit": "Izmeni koordinatni sistem",
  "output": "Koordinatni sistem izlaznih rezultata",
  "cName": "Ime koordinatnog sistema",
  "units": "Jedinice prikaza: ",
  "datum": "Datumska transformacija",
  "tName": "Ime transformacije",
  "tWKIDPlaceHolder": "WKID transformacije",
  "forward": "Koristi prosleđivanje transformacije",
  "ok": "U redu",
  "cancel": "Otkaži",
  "olderVersion": "Servis Geometry Service ne podržava radnju transformacije",
  "REPEATING_ERROR": " Koordinatni sistem postoji u listi izlaznih rezultata.",
  "Default": "Podrazumevano",
  "Inches": "Inči",
  "Foot": "Stope",
  "Yards": "Jardi",
  "Miles": "Milje",
  "Nautical_Miles": "Nautičke milje",
  "Millimeters": "Milimetri",
  "Centimeters": "Centimetri",
  "Meter": "Metri",
  "Kilometers": "Kilometri",
  "Decimeters": "Decimetri",
  "Decimal_Degrees": "Decimalni stepeni",
  "Degree_Minutes_Seconds": "Stepeni minuti sekunde",
  "MGRS": "Referentni sistem vojne pravougle koordinatne mreže (MGRS)",
  "USNG": "Nacionalna koordinatna mreža SAD (USNG)",
  "displayOrderLonLatTips": "Redosled prikaza koordinata:",
  "lonLatTips": "Geografska dužina / širina (X, Y)",
  "latLonTips": "Geografska dužina / širina (X, Y)"
});