define({
  "defaultAreaUnit": "Unit area default",
  "defaultLengthUnit": "Unit panjang default",
  "acres": "Acre",
  "sqMiles": "Mil persegi",
  "sqKilometers": "Kilometer persegi",
  "hectares": "Hektare",
  "sqYards": "Yard persegi",
  "sqFeet": "Kaki persegi",
  "sqFeetUS": "Kaki persegi (AS)",
  "sqMeters": "Meter persegi",
  "miles": "Mil",
  "kilometers": "Kilometer",
  "feet": "Kaki",
  "feetUS": "Kaki (AS)",
  "meters": "Meter",
  "yards": "Yard",
  "nauticalMiles": "Mil laut",
  "showArea": "Area",
  "showDistance": "Jarak",
  "showLocation": "Lokasi",
  "showtools": "Tampilkan alat pengukuran:",
  "allHidedTips": "Paling sedikit satu alat harus dipilih."
});