define({
  "common": {
    "apply": "適用",
    "ok": "OK",
    "cancel": "キャンセル",
    "yes": "はい",
    "no": "いいえ",
    "next": "次へ",
    "previous": "前へ",
    "back": "戻る",
    "selected": "選択",
    "name": "名前",
    "usage": "使用法",
    "settings": "設定",
    "home": "ホーム",
    "link": "リンク",
    "messages": "メッセージ",
    "outputs": "出力",
    "title": "タイトル",
    "thumbnail": "サムネイル",
    "url": "URL",
    "actions": "アクション",
    "layer": "レイヤー",
    "action": "アクション",
    "input": "入力",
    "output": "出力",
    "type": "タイプ",
    "required": "必須",
    "options": "オプション",
    "label": "ラベル",
    "tooltip": "ツールチップ",
    "visible": "表示",
    "symbol": "シンボル",
    "popup": "ポップアップ",
    "upload": "アップロード",
    "execute": "実行",
    "help": "ヘルプ",
    "executing": "実行中",
    "clear": "消去",
    "error": "エラー",
    "zoomTo": "ズーム",
    "attribute": "属性",
    "exports": "エクスポート",
    "check": "確認",
    "save": "保存",
    "close": "閉じる",
    "deleteText": "削除",
    "map": "マップ",
    "scene": "シーン",
    "reset": "リセット",
    "icon": "アイコン",
    "share": "共有",
    "view": "表示",
    "newText": "新規",
    "edit": "編集",
    "wkid": "WKID",
    "table": "テーブル",
    "zoomIn": "拡大",
    "zoomOut": "縮小",
    "continue1": "継続",
    "longitude": "経度",
    "latitude": "緯度"
  },
  "errorCode": "コード",
  "errorMessage": "メッセージ",
  "errorDetail": "詳細",
  "widgetPlaceholderTooltip": "これを設定するには、ウィジェットに移動して、対応するプレースホルダーをクリックします",
  "fieldStatistics": {
    "selectField": "フィールドの選択",
    "statistics": "統計",
    "field": "フィールド",
    "count": "値の数",
    "sum": "値の合計",
    "min": "最小値",
    "max": "最大値",
    "ave": "平均",
    "stddev": "標準偏差"
  },
  "symbolChooser": {
    "preview": "プレビュー",
    "basic": "基本",
    "arrows": "矢印",
    "business": "ビジネス",
    "cartographic": "カートグラフィック",
    "nationalParkService": "アメリカ国立公園",
    "outdoorRecreation": "野外レクリエーション",
    "peoplePlaces": "人と場所",
    "safetyHealth": "安全と衛生",
    "shapes": "形状",
    "transportation": "交通",
    "symbolSize": "シンボル サイズ",
    "color": "色",
    "alpha": "透過",
    "outlineColor": "アウトライン色",
    "outlineWidth": "アウトライン幅",
    "style": "スタイル",
    "width": "幅",
    "text": "テキスト",
    "fontColor": "フォントの色",
    "fontSize": "フォント サイズ",
    "transparency": "透過表示",
    "solid": "実線",
    "dash": "破線",
    "dot": "点線",
    "dashDot": "1 点鎖線",
    "dashDotDot": "2 点鎖線",
    "customImage": "カスタム画像",
    "chooseFile": "ファイルの選択",
    "noFileChoosen": "ファイルが選択されていません。"
  },
  "transparency": {
    "opaque": "不透明",
    "transparent": "透明"
  },
  "rendererChooser": {
    "domain": "ドメイン",
    "use": "使用",
    "singleSymbol": "単一シンボル",
    "uniqueSymbol": "個別値シンボル",
    "color": "色",
    "size": "サイズ",
    "toShow": "表示",
    "colors": "色",
    "classes": "等級",
    "symbolSize": "シンボル サイズ",
    "addValue": "値の追加",
    "setDefaultSymbol": "デフォルト シンボルの設定",
    "defaultSymbol": "デフォルト シンボル",
    "selectedSymbol": "選択時のシンボル",
    "value": "値",
    "label": "ラベル",
    "range": "範囲"
  },
  "drawBox": {
    "point": "ポイント",
    "line": "ライン",
    "polyline": "ポリライン",
    "freehandPolyline": "フリーハンド ポリライン",
    "triangle": "三角形",
    "extent": "範囲",
    "circle": "円",
    "ellipse": "楕円",
    "polygon": "ポリゴン",
    "freehandPolygon": "フリーハンド ポリゴン",
    "text": "テキスト",
    "clear": "消去"
  },
  "popupConfig": {
    "title": "タイトル",
    "add": "追加",
    "fields": "フィールド",
    "noField": "フィールドがありません",
    "visibility": "表示",
    "name": "名前",
    "alias": "エイリアス",
    "actions": "アクション"
  },
  "includeButton": {
    "include": "含む"
  },
  "loadingShelter": {
    "loading": "読み込んでいます"
  },
  "basicServiceBrowser": {
    "noServicesFound": "サービスが見つかりませんでした。",
    "unableConnectTo": "次に接続できません:",
    "invalidUrlTip": "入力した URL は無効であるか、アクセスできません。"
  },
  "serviceBrowser": {
    "noGpFound": "ジオプロセシング サービスが見つかりませんでした。",
    "unableConnectTo": "次に接続できません:"
  },
  "layerServiceBrowser": {
    "noServicesFound": "マップ サービスまたはフィーチャ サービスが見つかりませんでした",
    "unableConnectTo": "次に接続できません:"
  },
  "basicServiceChooser": {
    "validate": "整合チェック",
    "example": "例",
    "set": "設定"
  },
  "urlInput": {
    "invalidUrl": "無効な URL です。"
  },
  "urlComboBox": {
    "invalidUrl": "無効な URL です。"
  },
  "filterBuilder": {
    "addAnotherExpression": "フィルターの条件式を追加",
    "addSet": "式セットの追加",
    "matchMsg": "次の条件式の ${any_or_all} に一致するレイヤーのフィーチャを取得",
    "matchMsgSet": "このセットの次の条件式の${any_or_all}に当てはまります。",
    "all": "すべて",
    "any": "一部",
    "value": "値",
    "field": "フィールド",
    "unique": "個別値",
    "none": "なし",
    "and": "かつ",
    "valueTooltip": "値の入力",
    "fieldTooltip": "既存のフィールドから選択",
    "uniqueValueTooltip": "選択されたフィールドの個別値から選択",
    "stringOperatorIs": "に等しい",
    "stringOperatorIsNot": "に等しくない",
    "stringOperatorStartsWith": "で始まる",
    "stringOperatorEndsWith": "で終わる",
    "stringOperatorContains": "を含む",
    "stringOperatorDoesNotContain": "を含まない",
    "stringOperatorIsBlank": "空である",
    "stringOperatorIsNotBlank": "空でない",
    "dateOperatorIsOn": "である",
    "dateOperatorIsNotOn": "でない",
    "dateOperatorIsBefore": "より前である",
    "dateOperatorIsAfter": "より後である",
    "dateOperatorDays": "日",
    "dateOperatorWeeks": "週",
    "dateOperatorMonths": "月",
    "dateOperatorInTheLast": "以内である",
    "dateOperatorNotInTheLast": "以内でない",
    "dateOperatorIsBetween": "の間にある",
    "dateOperatorIsNotBetween": "の間にない",
    "dateOperatorIsBlank": "空である",
    "dateOperatorIsNotBlank": "空でない",
    "numberOperatorIs": "に等しい",
    "numberOperatorIsNot": "に等しくない",
    "numberOperatorIsAtLeast": "以上",
    "numberOperatorIsLessThan": "より小さい",
    "numberOperatorIsAtMost": "以下",
    "numberOperatorIsGreaterThan": "より大きい",
    "numberOperatorIsBetween": "の間にある",
    "numberOperatorIsNotBetween": "の間にない",
    "numberOperatorIsBlank": "空である",
    "numberOperatorIsNotBlank": "空でない",
    "string": "文字列",
    "number": "数値",
    "date": "日付",
    "askForValues": "値の確認",
    "prompt": "プロンプト",
    "hint": "ヒント",
    "error": {
      "invalidParams": "無効なパラメーターです。",
      "invalidUrl": "無効な URL です。",
      "noFilterFields": "レイヤーには、フィルターに使用できるフィールドがありません。",
      "invalidSQL": "無効な SQL 式です。",
      "cantParseSQL": "SQL 式を解析できません。"
    },
    "caseSensitive": "大文字/小文字を区別します",
    "notSupportCaseSensitiveTip": "ホスト サービスでは、大文字/小文字を区別するクエリはサポートされていません。",
    "setFilterTip": "フィルターを正しく設定してください。",
    "listValues": "リスト値",
    "cascadeFilterTip": "前の条件式でフィルター処理した値のみを表示",
    "noneCascadeFilterTip": "このフィールドのすべての個別値",
    "previousCascadeFilterTip": "前の条件式でフィルター処理した値",
    "allCascadeFilterTip": "他のすべての条件式でフィルター処理した値"
  },
  "featureLayerSource": {
    "layer": "レイヤー",
    "browse": "参照",
    "selectFromMap": "マップから選択",
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL を追加",
    "inputLayerUrl": "レイヤー URL を入力",
    "selectLayer": "現在のマップからフィーチャ レイヤーを選択",
    "chooseItem": "フィーチャ レイヤー アイテムを選択",
    "setServiceUrl": "フィーチャ サービスまたはマップ サービスの URL を入力",
    "selectFromOnline": "ArcGIS Online から追加",
    "chooseLayer": "フィーチャ レイヤーを選択します。"
  },
  "queryableLayerSource": {
    "layer": "レイヤー",
    "browse": "参照",
    "selectFromMap": "マップから選択",
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL の追加",
    "inputLayerUrl": "レイヤー URL を入力",
    "selectLayer": "現在のマップからレイヤーを選択します。",
    "chooseItem": "アイテムを選択します。",
    "setServiceUrl": "サービスの URL を入力します。",
    "selectFromOnline": "ArcGIS Online から追加",
    "chooseLayer": "レイヤーを選択します。"
  },
  "gpSource": {
    "selectFromPortal": "Portal for ArcGIS から追加",
    "addServiceUrl": "サービス URL の追加",
    "selectFromOnline": "ArcGIS Online から追加",
    "setServiceUrl": "ジオプロセシング サービスの URL を入力します。",
    "chooseItem": "ジオプロセシング サービス アイテムを選択します。",
    "chooseTask": "ジオプロセシング タスクを選択します。"
  },
  "itemSelector": {
    "map": "マップ",
    "selectWebMap": "Web マップの選択",
    "addMapFromOnlineOrPortal": "アプリケーションの Web マップを、ArcGIS Online のパブリック コンテンツから検索するか、ArcGIS Online または Portal のプライベート コンテンツから検索して追加します。",
    "searchMapName": "マップ名で検索...",
    "searchNone": "検索対象が見つかりませんでした。もう一度試してください。",
    "groups": "グループ",
    "noneGroups": "グループはありません",
    "signInTip": "ログイン セッションの期限が切れています。ブラウザーを更新して、ポータルにもう一度サイン インしてください。",
    "signIn": "サイン イン",
    "publicMap": "パブリック",
    "myOrganization": "組織",
    "myGroup": "マイ グループ",
    "myContent": "マイ コンテンツ",
    "count": "個数",
    "fromPortal": "ポータルから",
    "fromOnline": "ArcGIS.com から",
    "noneThumbnail": "サムネイルは使用できません",
    "owner": "所有者",
    "signInTo": "サイン イン",
    "lastModified": "最終更新日",
    "moreDetails": "詳細",
    "mostRecent": "新しい順",
    "mostViewed": "ビュー数が多い順",
    "highestRated": "評価の高い順",
    "viewItemDetails": "アイテム詳細の表示"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "サービスはクエリをサポートしていません。"
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "マップで利用できる適切なレイヤーがありません。"
  },
  "layerInfosMenu": {
    "titleBasemap": "ベースマップ",
    "titleLayers": "操作レイヤー",
    "labelLayer": "レイヤー名",
    "itemZoomTo": "ズーム",
    "itemTransparency": "透過表示",
    "itemTransparent": "透明",
    "itemOpaque": "不透明",
    "itemMoveUp": "上に移動",
    "itemMoveDown": "下に移動",
    "itemDesc": "説明",
    "itemDownload": "ダウンロード",
    "itemToAttributeTable": "属性テーブルを開く"
  },
  "imageChooser": {
    "unsupportReaderAPI": "TODO: ブラウザーはファイル リーダー API をサポートしていません",
    "readError": "ファイルの読み込みに失敗しました。",
    "unknowError": "操作を完了できません",
    "invalidType": "無効なファイル タイプです。",
    "cropImage": "画像のトリミング",
    "exceed": "ファイル サイズが 1024 KB を超えてはいけません。",
    "enableFlash": "画像を参照する前に、Adobe Flash を有効化してください。",
    "cropWaining": "少なくとも ${width} x ${height} ピクセルの写真を選択してください。",
    "toolTip": "一番見やすい画像サイズは、幅 ${width} ピクセル、高さ ${height} ピクセルです。その他のサイズでは自動的にサイズが調整されます。使用できる画像形式は、PNG、GIF、JPEG です。"
  },
  "simpleTable": {
    "moveUp": "上に移動",
    "moveDown": "下に移動",
    "deleteRow": "削除",
    "edit": "編集"
  },
  "urlParams": {
    "invalidToken": "無効なトークン",
    "validateTokenError": "無効なトークンまたはネットワーク エラー"
  },
  "exportTo": {
    "exportTo": "エクスポート",
    "toCSV": "CSV ファイルにエクスポート",
    "toFeatureCollection": "フィーチャ コレクションにエクスポート",
    "toGeoJSON": "GeoJSON にエクスポート"
  },
  "appState": {
    "title": "アプリの状態",
    "restoreMap": "クリックすると、マップ範囲およびオフにしていたレイヤーの表示設定を復元します。"
  },
  "featureActions": {
    "featureActions": "フィーチャ アクション",
    "ZoomTo": "ズーム",
    "PanTo": "画面移動",
    "Flash": "フラッシュ",
    "ShowPopup": "ポップアップの表示",
    "CreateLayer": "レイヤーの作成",
    "ShowStatistics": "統計情報...",
    "ClearSelection": "選択の解除",
    "ExportToCSV": "CSV ファイルにエクスポート",
    "ShowSelectedFeature": "選択フィーチャの表示",
    "ExportToFeatureCollection": "フィーチャ コレクションにエクスポート",
    "ExportToGeoJSON": "GeoJSON にエクスポート",
    "AddMarker": "マーカーの追加",
    "RemoveMarker": "マーカーの削除"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "関連レイヤー",
    "selectedFeatures": "選択フィーチャの使用",
    "drawShapesTip": "図形を描画してフィーチャを選択します",
    "pleaseDrawShapesTip": "図形を描画してフィーチャを選択してください",
    "allFeaturesTip": "レイヤー内のすべてのフィーチャ",
    "selectFeaturesOrDrawShapesTip": "このレイヤー内の選択フィーチャを使用するか、マップ上で図形を描画してフィーチャを制限してください。"
  },
  "searchDistance": {
    "applySearchDistance": "検索距離の適用",
    "applySearchDistanceToFeatures": "選択フィーチャまでの検索距離を適用します"
  },
  "units": {
    "miles": "マイル",
    "kilometers": "キロメートル",
    "feet": "フィート",
    "meters": "メートル",
    "yards": "ヤード",
    "nauticalMiles": "海里"
  },
  "featureSetChooser": {
    "select": "選択",
    "dragBox": "ドラッグ",
    "dragMouse": "マウスのドラッグ",
    "selectByRectangle": "四角形による選択",
    "selectFeaturesTip": "マップ上のフィーチャを囲むボックスをドラッグしてフィーチャを選択します",
    "newSelectionTip": "選択セットの新規作成",
    "addSelectionTip": "選択に追加",
    "removeSelectionTip": "選択セットから削除",
    "selectFromCurrentSelectionTip": "現在の選択セットから絞込選択",
    "unselectAllSelectionTip": "現在選択されているすべてのフィーチャを選択解除します",
    "selectByPolygon": "ポリゴンによる選択",
    "selectByCircle": "円による選択",
    "selectByLine": "ラインによる選択",
    "chooseSelectingTools": "選択ツールの選択",
    "darw": "描画",
    "drawShap": "図形の描画"
  },
  "widgetManager": {
    "createWidgetError": "ウィジェットの作成エラー",
    "createWidgetSettingPageError": "ウィジェット設定ページの作成エラー",
    "loadWidgetResourceError": "ウィジェットのリソースの読み込みエラー"
  },
  "shareOptions": {
    "shareMap": "このアプリを共有するユーザーを設定します",
    "shareMapTips": "アプリは現在、これらのユーザーと共有されています",
    "everyone": "すべてのユーザー",
    "theseGroups": "次のグループ"
  },
  "shareLink": {
    "email": "電子メール",
    "shareEmail": "電子メール",
    "facebook": "Facebook",
    "shareFacebook": "Facebook",
    "twitter": "Twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "Google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "このアプリの Web サイトへの埋め込み",
    "shareEmailSubject": "Web アプリの共有:",
    "shareEmailTxt1": "これは、Web AppBuilder for ArcGIS を使用して共有されている Web アプリです。",
    "shareEmailTxt2": "Esri Web AppBuilder for ArcGIS を使用して、独自の Web アプリを作成して共有することができます。",
    "shareEmailTxt3": "詳細については、http://www.esri.com/software/web-appbuilder をご参照ください。",
    "smallSize": "小",
    "mediumSize": "中",
    "largeSize": "大",
    "customSize": "カスタム",
    "embed": "このアプリの Web サイトへの埋め込み",
    "more": "埋め込みオプション",
    "changeShareSettings": "共有設定の変更",
    "shareLinkText": "このアプリへのリンクの共有",
    "linkOptions": "リンク オプション",
    "linkOptionsUrlParameters": "リンクに含まれる URL パラメーターを選択します",
    "currentMapExtent": "現在のマップ範囲",
    "chooseCenterWithLevel": "マップをクリックして、ズーム レベルを伴うマップの中心を定義します",
    "chooseCenterWithScale": "マップをクリックして、縮尺を伴うマップの中心を定義します",
    "findLocation": "位置またはフィーチャを検索し、それにズームします",
    "findLocation_inputPlaceholder": "場所またはフィーチャ",
    "queryFeature": "フィーチャを検索してズームします",
    "addMarker": "マーカーのマップへの追加",
    "addMarker_titlePlaceholder": "マーカーのポップアップのタイトル",
    "addMarker_symbolURL": "マーカー シンボルの URL",
    "addMarker_label": "マーカー ラベル",
    "popupTitle": "ポップアップ タイトル",
    "zoomLevel": "ズーム レベル",
    "overwirteMobileLayout": "モバイル レイアウトのデフォルトのスクリーン サイズを上書きします",
    "language": "アプリの表示言語を設定します",
    "auth": "ユーザーを自動的に認証します",
    "linkPreview": "リンク プレビュー",
    "useShortenLink": "ショート リンク",
    "shareMapUrlExtent": "現在のマップ範囲を共有",
    "shareToWebTips": "このアプリは、一般公開されていません。ユーザーが表示できない可能性があります。"
  },
  "webSceneLoader": {
    "webglSupportTip": "3D Web アプリは、使用中のブラウザーではサポートされていません。"
  },
  "map": {
    "basemapNotAvailable": "ベースマップは利用できません。",
    "displayDefaultBasemap": "代わりにデフォルトのベースマップを表示しています。"
  },
  "popup": {
    "relatedTables": "関連テーブル:",
    "relatedRecords": "関連レコード:",
    "noRelatedRecotds": "関連するレコードが見つかりませんでした"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "選択セット内のフィーチャが多すぎます。これらを取得してマップ上に表示するのに時間がかかる可能性があります。",
    "askForContinue": "続行しますか？"
  },
  "colorPalette": {
    "transparent": "透明",
    "custom": "カスタム"
  },
  "noEditPrivileges": "ご使用のアカウントには、データを作成/変更する権限がありません。",
  "invalidConfiguration": "ウィジェットが構成されていないか、構成で指定されたレイヤーがマップ内に存在しません。アプリをビルダー モードで開き、ウィジェットを再構成してください。"
});