define({
    root:{
     addOIC: "Add Oriented Imagery Catalog",
     selectPointOn: "Turn on to pick a focus point in scene to view image",
     selectPointOff: "Turn off to select features in scene",
     viewMode: "Choose view mode",
     twoD: "2D",
     threeD: "3D",
     exposurePoints: "Image exposure points",
     currentCoverage: "Current coverage",
     similarCoverage: "Additional coverage",
     coverageMap: "Coverage map",
     vectorLayer: "Vector layer(s)",
     addVector: "Add layer to the viewer",
     removeVector: "Remove layer from the viewer",
     viewGraphic: "Click here to view the selected feature in image.",
     removeImage: "Click here to remove image from scene",
     dialogTitle1: "Oriented Imagery Viewer",
     from: "From",
     agol: "ArcGIS Online",
     file: "File",
     itemUrl: "Item URL",
     content: "My Content",
     groups: "My Groups",
     folder: "Folder",
     group: "Group",
     oic: "OIC",
     add: "Add",
     remove: "Remove",
     selectOIC: "Select catalog",
     select: "Select",
     addAll: "Add all",
     delete: "Delete",
     update: "Update",
     notification1: "Please wait. Searching for image.",
     notification2: "Please wait! Connecting to ArcGIS Online...",
     error1: "Error! Invalid OIC File.",
     error2: "Error! Failed to load file",
     error3: "Error! Request to OIC Item failed.",
     error4: "Error! Invalid OIC.",
     error5: "Error! Item type is not OIC.",
     error6: "Error! Please enter a valid OIC item url."
    }
     
});