define({
  "defaultAreaUnit": "Προεπιλεγμένη μονάδα εμβαδού",
  "defaultLengthUnit": "Προεπιλεγμένη μονάδα μήκους",
  "acres": "Έικρ",
  "sqMiles": "Τετρ. μίλια",
  "sqKilometers": "Τετρ. χιλιόμετρα",
  "hectares": "Εκτάρια",
  "sqYards": "Τετρ. γιάρδες",
  "sqFeet": "Τετρ. πόδια",
  "sqFeetUS": "Τετρ. πόδια (US)",
  "sqMeters": "Τετρ. μέτρα",
  "miles": "Μίλια",
  "kilometers": "Χιλιόμετρα",
  "feet": "Πόδια",
  "feetUS": "Πόδια (US)",
  "meters": "Μέτρα",
  "yards": "Γιάρδες",
  "nauticalMiles": "Ναυτικά μίλια",
  "showArea": "Περιοχή",
  "showDistance": "Απόσταση",
  "showLocation": "Τοποθεσία",
  "showtools": "Εμφάνιση εργαλείων μέτρησης:",
  "allHidedTips": "Πρέπει να επιλεγεί τουλάχιστον ένα εργαλείο."
});