define({
  "defaultAreaUnit": "기본 면적 단위",
  "defaultLengthUnit": "기본 길이 단위",
  "acres": "에이커",
  "sqMiles": "제곱마일",
  "sqKilometers": "제곱킬로미터",
  "hectares": "헥타르",
  "sqYards": "제곱야드",
  "sqFeet": "제곱피트",
  "sqFeetUS": "제곱피트(미국)",
  "sqMeters": "제곱미터",
  "miles": "마일",
  "kilometers": "킬로미터",
  "feet": "피트",
  "feetUS": "피트(미국)",
  "meters": "미터",
  "yards": "야드",
  "nauticalMiles": "해리",
  "showArea": "면적",
  "showDistance": "거리",
  "showLocation": "위치",
  "showtools": "측정 도구 표시:",
  "allHidedTips": "최소 하나의 도구를 선택해야 합니다."
});