define({
  "common": {
    "apply": "Rakenda",
    "ok": "OK",
    "cancel": "Tühista",
    "yes": "Jah",
    "no": "Ei",
    "next": "Järgmine",
    "previous": "Eelmine",
    "back": "Tagasi",
    "selected": "valitud",
    "name": "Nimi",
    "usage": "Kasutus",
    "settings": "Seaded",
    "home": "Avaleht",
    "link": "Link",
    "messages": "Sõnumid",
    "outputs": "Väljundid",
    "title": "Pealkiri",
    "thumbnail": "Pisipilt",
    "url": "URL",
    "actions": "Tegevused",
    "layer": "Kiht",
    "action": "Tegevus",
    "input": "Sisend",
    "output": "Väljund",
    "type": "Tüüp",
    "required": "Nõutav",
    "options": "Valikud",
    "label": "Märgis",
    "tooltip": "Kohtspikker",
    "visible": "Nähtav",
    "symbol": "Sümbol",
    "popup": "Hüpikaken",
    "upload": "Laadi üles",
    "execute": "Käivita",
    "help": "Abi",
    "executing": "Teostamine",
    "clear": "Puhasta",
    "error": "Viga",
    "zoomTo": "Suumi",
    "attribute": "Atribuut",
    "exports": "Ekspordi",
    "check": "Kontrolli",
    "save": "Salvesta",
    "close": "Sule",
    "deleteText": "Kustuta",
    "map": "Kaart",
    "scene": "Stseen",
    "reset": "Lähtesta",
    "icon": "Ikoon",
    "share": "Jaga",
    "view": "Vaatamine",
    "newText": "Uus",
    "edit": "Muuda",
    "wkid": "WKID",
    "table": "Tabel",
    "zoomIn": "Suurenda",
    "zoomOut": "Vähenda",
    "continue1": "Jätka",
    "longitude": "Pikkuskraad",
    "latitude": "Laiuskraad"
  },
  "errorCode": "Kood",
  "errorMessage": "Sõnum",
  "errorDetail": "Detail",
  "widgetPlaceholderTooltip": "Seadistamiseks valige Vidinad ning klikkige vastavat kohatäidet",
  "fieldStatistics": {
    "selectField": "Vali väli",
    "statistics": "Statistika",
    "field": "Väli",
    "count": "Väärtuste hulk",
    "sum": "Väärtuste summa",
    "min": "Miinimum",
    "max": "Maksimaalne",
    "ave": "Keskmine",
    "stddev": "Standardhälve"
  },
  "symbolChooser": {
    "preview": "Eelvaade",
    "basic": "Esmane",
    "arrows": "Nooled",
    "business": "Äriettevõtted",
    "cartographic": "Kartograafia",
    "nationalParkService": "Rahvuspargi teenus",
    "outdoorRecreation": "Rekreatsioon",
    "peoplePlaces": "Inimeste asukohad",
    "safetyHealth": "Tervishoid",
    "shapes": "Kujundid",
    "transportation": "Transport",
    "symbolSize": "Sümboli suurus",
    "color": "Värv",
    "alpha": "Alfa",
    "outlineColor": "Äärejoone värv",
    "outlineWidth": "Äärejoone laius",
    "style": "Stiil",
    "width": "Laius",
    "text": "Tekst",
    "fontColor": "Fondi värv",
    "fontSize": "Fondi suurus",
    "transparency": "Läbipaistvus",
    "solid": "Pidev",
    "dash": "Katkendlik",
    "dot": "Punktiir",
    "dashDot": "Katkendlik punktiga",
    "dashDotDot": "Katkendlik kahe punktiga",
    "customImage": "Kohandatud pilt",
    "chooseFile": "Vali fail",
    "noFileChoosen": "Faili pole valitud."
  },
  "transparency": {
    "opaque": "Läbipaistmatu",
    "transparent": "Läbipaistev"
  },
  "rendererChooser": {
    "domain": "Domeen",
    "use": "Kasutus",
    "singleSymbol": "Üks sümbol",
    "uniqueSymbol": "Unikaalne sümbol",
    "color": "Värv",
    "size": "Suurus",
    "toShow": "Näita",
    "colors": "Värvid",
    "classes": "Klassid",
    "symbolSize": "Sümboli suurus",
    "addValue": "Lisa väärtus",
    "setDefaultSymbol": "Määra vaikesümbol",
    "defaultSymbol": "Vaikesümbol",
    "selectedSymbol": "Valitud sümbol",
    "value": "Väärtus",
    "label": "Märgis",
    "range": "Ulatus"
  },
  "drawBox": {
    "point": "Punkt",
    "line": "Joon",
    "polyline": "Murdjoon",
    "freehandPolyline": "Vabakäeline murdjoon",
    "triangle": "Kolmnurk",
    "extent": "Kuvaulatus",
    "circle": "Ring",
    "ellipse": "Ellips",
    "polygon": "Pind",
    "freehandPolygon": "Vabakäeline pind",
    "text": "Tekst",
    "clear": "Puhasta"
  },
  "popupConfig": {
    "title": "Pealkiri",
    "add": "Lisa",
    "fields": "Väljad",
    "noField": "Väli puudub",
    "visibility": "Nähtav",
    "name": "Nimi",
    "alias": "Alias",
    "actions": "Toimingud"
  },
  "includeButton": {
    "include": "Kaasatud"
  },
  "loadingShelter": {
    "loading": "Laen"
  },
  "basicServiceBrowser": {
    "noServicesFound": "Teenuseid ei leitud.",
    "unableConnectTo": "Ei õnnestu luua ühendust",
    "invalidUrlTip": "Sisestatud URL ei sobi või pole kättesaadav."
  },
  "serviceBrowser": {
    "noGpFound": "Geotöötluse teenuseid ei leitud.",
    "unableConnectTo": "Ei õnnestu luua ühendust"
  },
  "layerServiceBrowser": {
    "noServicesFound": "Kaardi- või objektiteenuseid ei leitud",
    "unableConnectTo": "Ei õnnestu luua ühendust"
  },
  "basicServiceChooser": {
    "validate": "Valideeri",
    "example": "Näide",
    "set": "Määra"
  },
  "urlInput": {
    "invalidUrl": "Vigane URL."
  },
  "urlComboBox": {
    "invalidUrl": "Vigane URL."
  },
  "filterBuilder": {
    "addAnotherExpression": "Lisa filtriavaldis",
    "addSet": "Lisa avaldise kirjeldus.",
    "matchMsg": "Too kihi objektid, millega ühtivad ${any_or_all} järgmised avaldised",
    "matchMsgSet": "${any_or_all} järgmistest avaldistest on tõesed",
    "all": "Kõik",
    "any": "Mõni",
    "value": "Väärtus",
    "field": "Väli",
    "unique": "Unikaalne",
    "none": "Pole",
    "and": "ja",
    "valueTooltip": "Sisesta väärtus",
    "fieldTooltip": "Vali olemasolevast väljast",
    "uniqueValueTooltip": "Vali valitud välja unikaalsetest väärtustest",
    "stringOperatorIs": "on",
    "stringOperatorIsNot": "ei ole",
    "stringOperatorStartsWith": "algab",
    "stringOperatorEndsWith": "lõpeb",
    "stringOperatorContains": "sisaldab",
    "stringOperatorDoesNotContain": "ei sisalda",
    "stringOperatorIsBlank": "on tühi",
    "stringOperatorIsNotBlank": "ei ole tühi",
    "dateOperatorIsOn": "on",
    "dateOperatorIsNotOn": "ei ole",
    "dateOperatorIsBefore": "on enne",
    "dateOperatorIsAfter": "on pärast",
    "dateOperatorDays": "päeva",
    "dateOperatorWeeks": "nädalat",
    "dateOperatorMonths": "kuud",
    "dateOperatorInTheLast": "viimases",
    "dateOperatorNotInTheLast": "mitte viimases",
    "dateOperatorIsBetween": "on vahemikus",
    "dateOperatorIsNotBetween": "ei ole vahemikus",
    "dateOperatorIsBlank": "on tühi",
    "dateOperatorIsNotBlank": "ei ole tühi",
    "numberOperatorIs": "on",
    "numberOperatorIsNot": "ei ole",
    "numberOperatorIsAtLeast": "on vähemalt",
    "numberOperatorIsLessThan": "on väiksem kui",
    "numberOperatorIsAtMost": "on kõige",
    "numberOperatorIsGreaterThan": "on suurem kui",
    "numberOperatorIsBetween": "on vahemikus",
    "numberOperatorIsNotBetween": "ei ole vahemikus",
    "numberOperatorIsBlank": "on tühi",
    "numberOperatorIsNotBlank": "ei ole tühi",
    "string": "String",
    "number": "Number",
    "date": "Kuupäev",
    "askForValues": "Küsi väärtustest",
    "prompt": "Kuvatav kirje",
    "hint": "Vihje",
    "error": {
      "invalidParams": "Vigased parameetrid.",
      "invalidUrl": "Vigane URL.",
      "noFilterFields": "Kihil puuduvad väljad, mida saaks filtreerimiseks kasutada.",
      "invalidSQL": "Vigane SQL-avaldis.",
      "cantParseSQL": "SQL-avaldise parsimine ei õnnestu."
    },
    "caseSensitive": "Tõstutundlik",
    "notSupportCaseSensitiveTip": "Majutatud teenused ei toeta tõstutundlikke päringuid.",
    "setFilterTip": "Määrake filter õigesti.",
    "listValues": "Loendi väärtused",
    "cascadeFilterTip": "Kuva ainult eelmiste avaldiste alusel filtreeritud väärtused.",
    "noneCascadeFilterTip": "Sellel välja kõik kordumatud väärtused",
    "previousCascadeFilterTip": "Eelmiste avaldiste alusel filtreeritud väärtused",
    "allCascadeFilterTip": "Kõigi muude avaldiste alusel filtreeritud väärtused"
  },
  "featureLayerSource": {
    "layer": "Kiht",
    "browse": "Sirvi",
    "selectFromMap": "Vali kaardilt",
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "inputLayerUrl": "Sisendkihi URL",
    "selectLayer": "Vali praeguse kaardi objektikiht.",
    "chooseItem": "Vali objektikihi sisu.",
    "setServiceUrl": "Sisesta objekti- või kaarditeenuse URL.",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "chooseLayer": "Valige objektikiht."
  },
  "queryableLayerSource": {
    "layer": "Kiht",
    "browse": "Sirvi",
    "selectFromMap": "Vali kaardilt",
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "inputLayerUrl": "Sisendkihi URL",
    "selectLayer": "Valige kiht praeguselt kaardilt.",
    "chooseItem": "Valige sisuüksus.",
    "setServiceUrl": "Sisestage teenuse URL.",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "chooseLayer": "Vali kiht."
  },
  "gpSource": {
    "selectFromPortal": "Lisa Portal for ArcGIS-ist",
    "addServiceUrl": "Lisa teenuse URL",
    "selectFromOnline": "Lisa ArcGIS Online’ist",
    "setServiceUrl": "Sisestage geotöötlusteenuse URL.",
    "chooseItem": "Valige geotöötlusteenuse objekt.",
    "chooseTask": "Valige geotöötluse ülesanne."
  },
  "itemSelector": {
    "map": "Kaart",
    "selectWebMap": "Vali veebikaart",
    "addMapFromOnlineOrPortal": "Saate rakenduses veebikaarti otsida ja selle lisada ArcGIS Online’i avalike ressursside kaudu või ArcGIS Online’i või Portali isikliku sisu kaudu.",
    "searchMapName": "Otsi kaardi nime järgi...",
    "searchNone": "Me ei leidnud seda, mida otsisite. Proovige uuesti.",
    "groups": "Grupid",
    "noneGroups": "Gruppe ei ole",
    "signInTip": "Teie sisselogimise seanss on aegunud, portaali uuesti sisse logimiseks värskendage brauserit.",
    "signIn": "Logi sisse",
    "publicMap": "Avalik",
    "myOrganization": "Minu organisatsioon",
    "myGroup": "Minu grupid",
    "myContent": "Minu sisu",
    "count": "Loend",
    "fromPortal": "portaalist",
    "fromOnline": "veebilehelt ArcGIS.com",
    "noneThumbnail": "Pisipilt ei ole saadaval",
    "owner": "omanik",
    "signInTo": "Logi sisse",
    "lastModified": "Viimati muudetud",
    "moreDetails": "Rohkem infot",
    "mostRecent": "Kõige hiljutisem",
    "mostViewed": "Enim vaadatud",
    "highestRated": "Kõrgeimini hinnatud",
    "viewItemDetails": "Vaata üksuse detaile"
  },
  "featureLayerChooserFromPortal": {
    "notSupportQuery": "Teenus ei toeta päringut."
  },
  "basicLayerChooserFromMap": {
    "noLayersTip": "Kaardi jaoks pole saadaval ühtegi sobivat kihti."
  },
  "layerInfosMenu": {
    "titleBasemap": "Aluskaardid",
    "titleLayers": "Töökihid",
    "labelLayer": "Kihi nimi",
    "itemZoomTo": "Suumi",
    "itemTransparency": "Läbipaistvus",
    "itemTransparent": "Läbipaistev",
    "itemOpaque": "Läbipaistmatu",
    "itemMoveUp": "Liiguta ülespoole",
    "itemMoveDown": "Liiguta allapoole",
    "itemDesc": "Kirjeldus",
    "itemDownload": "Laadi alla",
    "itemToAttributeTable": "Ava atribuuditabel"
  },
  "imageChooser": {
    "unsupportReaderAPI": "MÄRKUS. Brauser ei toeta faililugemise liidest.",
    "readError": "Faili lugemine nurjus.",
    "unknowError": "toiminguid ei saanud lõpule viia",
    "invalidType": "Sobimatut tüüpi fail",
    "cropImage": "Kärbi pilti",
    "exceed": "Faili maht võib olla kuni 1024 KB.",
    "enableFlash": "Enne pildini sirvimist lubage Adobe Flash.",
    "cropWaining": "Palun valige foto, mille mõõdud on vähemalt ${width} x ${height} pikslit.",
    "toolTip": "Parima tulemuse saamiseks peaks pildi laius olema ${width} pikslit ning kõrgus ${height} pikslit. Muud suurused kohandatakse parajaks. Sobivad pildiformaadid on PNG, GIF ja JPEG."
  },
  "simpleTable": {
    "moveUp": "Liiguta ülespoole",
    "moveDown": "Liiguta allapoole",
    "deleteRow": "Kustuta",
    "edit": "Muuda"
  },
  "urlParams": {
    "invalidToken": "Kehtetu võti",
    "validateTokenError": "Kehtetu võti või võrgu tõrge"
  },
  "exportTo": {
    "exportTo": "Ekspordi",
    "toCSV": "Ekspordi CSV failiks",
    "toFeatureCollection": "Eksport objektide kogumisse",
    "toGeoJSON": "Eksport GeoJSON formaati"
  },
  "appState": {
    "title": "Rakenduse olek",
    "restoreMap": "Klõpsake kaardi ulatuse ja kihtide nähtavuse taastamiseks poolelijäänud kohas."
  },
  "featureActions": {
    "featureActions": "Objektide tegevused",
    "ZoomTo": "Suumi",
    "PanTo": "Liiguta",
    "Flash": "Välgutamine",
    "ShowPopup": "Kuva hüpikaken",
    "CreateLayer": "Loo kiht",
    "ShowStatistics": "Statistika...",
    "ClearSelection": "Tühista valik",
    "ExportToCSV": "Ekspordi CSV failiks",
    "ShowSelectedFeature": "Kuva valitud objektid",
    "ExportToFeatureCollection": "Eksport objektide kogumisse",
    "ExportToGeoJSON": "Eksport GeoJSON formaati",
    "AddMarker": "Lisa tähis",
    "RemoveMarker": "Eemalda tähis"
  },
  "spatialFilterByFeatures": {
    "relatedLayer": "Seotud kiht",
    "selectedFeatures": "Kasuta valitud objekte",
    "drawShapesTip": "Joonistage kujundid objektide valimiseks",
    "pleaseDrawShapesTip": "Joonistage kujundid objektide valimiseks",
    "allFeaturesTip": "Kõik selle kihi objektid",
    "selectFeaturesOrDrawShapesTip": "Kasutage selles kihis valitud objekte või joonistage objektide piiramiseks kaardile kujundid."
  },
  "searchDistance": {
    "applySearchDistance": "Rakenda otsingu vahemaa",
    "applySearchDistanceToFeatures": "Rakenda otsingu vahemaa valitud objektideni"
  },
  "units": {
    "miles": "Miili",
    "kilometers": "Kilomeetrit",
    "feet": "Jalga",
    "meters": "Meetrit",
    "yards": "Jardi",
    "nauticalMiles": "Meremiili"
  },
  "featureSetChooser": {
    "select": "Vali",
    "dragBox": "Lohista",
    "dragMouse": "Lohista hiirt",
    "selectByRectangle": "Vali ristkülikuga",
    "selectFeaturesTip": "Valige objektid, lohistades kaardile markeeritud kasti",
    "newSelectionTip": "Loo uus valik",
    "addSelectionTip": "Lisa valikule",
    "removeSelectionTip": "Eemalda valikust",
    "selectFromCurrentSelectionTip": "Vali praegusest valikust",
    "unselectAllSelectionTip": "Tühista kõigi praegu valitud objektide selekteering",
    "selectByPolygon": "Vali polügooni järgi",
    "selectByCircle": "Vali ringi järgi",
    "selectByLine": "Vali joone järgi",
    "chooseSelectingTools": "Vali selekteerimise tööriistad",
    "darw": "Joonista",
    "drawShap": "Joonista kujund"
  },
  "widgetManager": {
    "createWidgetError": "Vidina loomise viga",
    "createWidgetSettingPageError": "Vidina seadistuslehe loomise viga",
    "loadWidgetResourceError": "Vidina ressursi laadimise viga"
  },
  "shareOptions": {
    "shareMap": "Valige, kes saavad seda rakendust vaadata",
    "shareMapTips": "Rakendus on hetkel antud neile inimestele ühiskasutusse",
    "everyone": "Igaüks",
    "theseGroups": "Need grupid"
  },
  "shareLink": {
    "email": "e-mail",
    "shareEmail": "E-post",
    "facebook": "facebook",
    "shareFacebook": "Facebook",
    "twitter": "twitter",
    "shareTwitter": "Twitter",
    "googlePlus": "google+",
    "shareGooglePlus": "Google+",
    "EmbedTips": "Manusta see rakendus veebisaidile",
    "shareEmailSubject": "Ühiskasutusse antud veebirakendus:",
    "shareEmailTxt1": "Siin on veebirakendus, mis on antud rakenduse Web AppBuilder for ArcGIS abil teile ühiskasutusse.",
    "shareEmailTxt2": "Esri rakenduse Web AppBuilder for ArcGIS abil saate luua oma veebirakenduse ja anda selle ühiskasutusse.",
    "shareEmailTxt3": "Üksikasjalikku teavet leiate veebilehelt http://www.esri.com/software/web-appbuilder.",
    "smallSize": "Väike",
    "mediumSize": "Keskmine",
    "largeSize": "Suur",
    "customSize": "Kohandatud",
    "embed": "Manusta see rakendus veebisaidile",
    "more": "Manusta atribuudid",
    "changeShareSettings": "Muuda jagamise seadeid.",
    "shareLinkText": "Jaga selle rakenduse linki",
    "linkOptions": "Lingi valikud",
    "linkOptionsUrlParameters": "Vali linki kaasatavad URL-i parameetrid",
    "currentMapExtent": "Kaardi praegune ulatus",
    "chooseCenterWithLevel": "Klõpsake kaarti, et määratleda kaardi keskpunkt koos suumitasemega",
    "chooseCenterWithScale": "Klõpsake kaarti, et määratleda kaardi keskpunkt koos kaardi mõõtkavaga",
    "findLocation": "Leidke asukoht või objekt ja suumige seda",
    "findLocation_inputPlaceholder": "Teie koht või objekt",
    "queryFeature": "Tehke objektipäring ja suumige sellele",
    "addMarker": "Lisa sümbol kaardile",
    "addMarker_titlePlaceholder": "Sümboli hüpikakna pealkiri",
    "addMarker_symbolURL": "Punktsümboli URL",
    "addMarker_label": "Sümboli märgis",
    "popupTitle": "Hüpikakna nimi",
    "zoomLevel": "Suumitase",
    "overwirteMobileLayout": "Kirjuta üle mobiilseadmete paigutuse kuva vaikesuurus",
    "language": "Määra rakenduse kuvamiskeel",
    "auth": "Autendi kasutaja automaatselt",
    "linkPreview": "Lingi eelvaade",
    "useShortenLink": "Lühike link",
    "shareMapUrlExtent": "Jaga praeguse kaardi kuvaulatust",
    "shareToWebTips": "See rakendus pole avalik. Inimesed ei pruugi saada seda vaadata."
  },
  "webSceneLoader": {
    "webglSupportTip": "Teie brauser ei toeta 3D-veebirakendusi."
  },
  "map": {
    "basemapNotAvailable": "Aluskaart ei ole kättesaadav.",
    "displayDefaultBasemap": "Selle asemel kuvatakse vaikimisi aluskaart."
  },
  "popup": {
    "relatedTables": "Seotud tabelid:",
    "relatedRecords": "Seotud kirjed:",
    "noRelatedRecotds": "Seotud kirjeid ei leitud"
  },
  "queryFeatures": {
    "tooManyFeaturesTip": "Valikus on liiga palju objekte. Nende toomine ja kaardil kuvamine võib kaua aega võtta.",
    "askForContinue": "Kas soovite jätkata?"
  },
  "colorPalette": {
    "transparent": "Läbipaistev",
    "custom": "Kohandatud"
  },
  "noEditPrivileges": "Teie kontol puudub andmete loomise või muutmise õigus.",
  "invalidConfiguration": "Vidin on konfigureerimata või pole konfiguratsioonis sisalduvad kihid enam kaardil. Avage rakendus koosturirežiimis ja konfigureerige vidin uuesti."
});