define({
  "defaultAreaUnit": "Numatytasis ploto vienetas",
  "defaultLengthUnit": "Numatytasis ilgio vienetas",
  "acres": "Akrai",
  "sqMiles": "Kv. mylios",
  "sqKilometers": "Kv. kilometrai",
  "hectares": "Hektarai",
  "sqYards": "Kv. jardai",
  "sqFeet": "Kv. pėdos",
  "sqFeetUS": "Kv. pėdos (JAV)",
  "sqMeters": "Kv. metrai",
  "miles": "Mylios",
  "kilometers": "Kilometrai",
  "feet": "Pėdos",
  "feetUS": "Pėdos (JAV)",
  "meters": "Metrai",
  "yards": "Jardai",
  "nauticalMiles": "Jūrmylės",
  "showArea": "Plotas",
  "showDistance": "Atstumas",
  "showLocation": "Vieta",
  "showtools": "Rodyti matavimo įrankius:",
  "allHidedTips": "Būtina pasirinkti bent vieną įrankį."
});